### ISSUE TITLE
Error: unknown option: --config-file

### ISSUE THREAD

**Issue by ajtrichards** [cypress-io/github-action#102]
**GH Action Config**
```
javascript-e2e-tests:
    name: JS e2e Tests
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          runTests: false
          working-directory: MY_DIR
      - name: Run e2e tests
        uses: cypress-io/github-action@v1
        with:
          install: false
          working-directory: MY_DIR
``` 

**Problem**
The first steps run fine - checkout and installation of the dependencies. When GH actions starts to run the `Run e2e tests` step it errors with the following:

```
Skipping install because install parameter is false
Cypress test command: npx cypress run --config-file cypress.json
/usr/local/bin/npx cypress run --config-file cypress.json

  error: unknown option: --config-file
```
