### ISSUE TITLE
Session / Cookies not cleared between tests

### ISSUE THREAD

**Issue by thibautvdu** [cypress-io/github-action#1023]
I use a custom login command, as follow : 

```
Cypress.Commands.add("login", (email: string) => {
  cy.session(`login ${email}`, () => {
    const now = Date.now();

    cy.visit("/login");
    cy.get('[data-test="login-email"]').type(email);
    cy.get('[data-test="login-submit"]').click();
   ...
  });
});
```

When running locally, with cypress:run, everything is working perfectly fine and the tests start with a signed out user regardless of the previous ones. However when running it through github actions, the signed in session persists between my tests and thus create chaos all around. Is there any additional configuration necessary to ensure test isolation with this github action ?

**Comment by thibautvdu** [comment]
Thanks for your answer @MikeMcC399 
Here is my workflow : 

```
name: ci preview
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [deployment_status]
jobs:
  e2e:
    # only runs this job on successful deploy
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm i -g vercel@latest
      - name: Link preview alias url to new deployment
        run: vercel alias --token=${{ secrets.VERCEL_TOKEN }} --scope=${{secrets.VERCEL_ORG_ID}} set ${{ github.event.deployment_status.target_url }} ${{ secrets.PREVIEW_URL }}
      - name: Run Cypress 🌲
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_BASE_URL: https://${{ secrets.PREVIEW_URL }}
          CYPRESS_IMAP_EMAIL: ${{ secrets.CYPRESS_IMAP_EMAIL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Upload Cucumber Report
        run: npm run cypress:upload
```

It is worth mentioning I'm using https://github.com/badeball/cypress-cucumber-preprocessor ; however since test isolation is working perfectly fine with it locally I do not suspect it to be at cause.
