### ISSUE TITLE
Error: The runs.using key in action.yml must be one of:

### ISSUE THREAD

**Issue by erikc96** [cypress-io/github-action#1030]
Error: 
```

Error: The runs.using key in action.yml must be one of: [composite docker node12 node16], got node20
```

Hello, I'm getting this error with this config:

```
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run DB with Docker
        run: docker-compose -f docker-compose.yaml up -d db elasticsearch init-es-index

      - name: Install prerequisites
        run: cd app && npm install --include dev

      - name: Set Up DB
        run: cd app && npx prisma generate && npx prisma migrate reset --force

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          working-directory: app-test
```

Action.yml seems to be a file in this codebase, so not sure how to fix.
