### ISSUE TITLE
Component test do not wait for initial compilation using Electron

### ISSUE THREAD

**Issue by ekrapfl** [cypress-io/github-action#1031]
I am hookup up a GitHub Action to run my Cypress component tests for Angular.  I started out using the default browser (electron), and I found that my tests would run fine, but the first test kept telling me that it had timed out.

The build output would look something like this:
<img width="1004" alt="image" src="https://github.com/cypress-io/github-action/assets/5939413/f832040c-8a6d-4c4e-ad55-f88d48fa793d">

Followed by all of the Angular compilation output:
<img width="1032" alt="image" src="https://github.com/cypress-io/github-action/assets/5939413/203a75fe-ec7e-4371-9d55-48919c394411">

...
<img width="1112" alt="image" src="https://github.com/cypress-io/github-action/assets/5939413/0fa98f03-35c3-4a21-8b06-c216d33c6e9d">

And then all subsequent tests would pass.

I racked my brain for quite a while on this, and then finally, I tried simply switching to chrome.  To my surprise, it worked.  Every time, it seems to work with chrome, but fail with electron.  The difference appears to be that with chrome, it waits until Angular compilation is done before attempting to see if the first test timed out.

Chrome output:
<img width="1190" alt="image" src="https://github.com/cypress-io/github-action/assets/5939413/130dffa8-8356-47b3-94f0-9e370ee9b4a6">

...
<img width="994" alt="image" src="https://github.com/cypress-io/github-action/assets/5939413/e29d54e9-0b6c-4fd0-9bdd-cc1bb3df7950">

This seems like a bug to me.  With component tests for Angular, chrome waits for the Angular compilation to finish before starting the test timeout timer.  Electron does not.

Full step being used:
```yml
- name: Cypress.io
  uses: cypress-io/github-action@v6
  with:
    record: true
    component: true
    config-file: cypress.config.ts
    # These tests fail when run on electron.
    # They time out for at least the first test due to Angular compilation.
    # Chrome seems to understand to not start timing the test until after Angular compilation has completed.
    browser: chrome
    ci-build-id: ${{ needs.prepare.outputs.uuid }}
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    NODE_OPTIONS: --max_old_space_size=9500
    TZ: 'America/Chicago'
```
