### ISSUE TITLE
Cannot find config-file

### ISSUE THREAD

**Issue by Christian-Oleson** [cypress-io/github-action#1046]
In my local setup, I have cypress setup:
reponame/cypress/config/myConfig.json

I've tried the `config-file` option, including specifying the directories, subdirectories, etc.
e.g.,
```yaml
config-file: myConfig.json
```
and nothing seems to resolve the file. I keep getting this error:
```shell
DevTools listening on ws://127.0.0.1:42869/devtools/browser/765dff37-7f7b-490f-9a4e-b18bdb5c1079
Could not find a Cypress configuration file.

We looked but did not find a myConfig.json file in this folder: /home/runner/work/reponame/reponame
```
What is the recommended setup for config files in this runner? Where is the runner starting from in terms of its local directory? e.g. repo root?

**Comment by MikeMcC399** [comment]
@Christian-Oleson 

The most likely reason for your problem would be if you are using the `command` parameter. See the [README > Custom install command](https://github.com/cypress-io/github-action#custom-test-command) where it says:

"Caution: using the action parameter command causes multiple other parameters to be ignored including: auto-cancel-after-failures, browser, ci-build-id, command-prefix, component, config, config-file, env, group, headed, parallel, project, publish-summary, quiet, record, spec and tag."

If that is not the case, then please post your workflow.

Note that 
> DevTools listening on ws://127.0.0.1:42869/devtools/browser/765dff37-7f7b-490f-9a4e-b18bdb5c1079

is not an error. It is an informational message which is unrelated to your problem.
- See https://github.com/cypress-io/cypress/issues/26753

**Comment by Christian-Oleson** [comment]
Thanks for the comment @MikeMcC399 . I am not using the command parameter. Here is my workflow:
```yaml
name: Cypress Tests
on:
  push:
    branches:
      - 'main'
      - 'feature**'
  workflow_dispatch:
    inputs:
      branch:
        config: 'The config to use'
        required: true
        default: "staging"

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config: --env configFile=${{ github.event.inputs.environment }}
          spec: |
            **/*Catalog.cy.js
            **/*Catalog.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
