### ISSUE TITLE
Running the Action without End-to-End Tests (i.e. Component-Tests Only)

### ISSUE THREAD

**Issue by KyleKing** [cypress-io/github-action#1051]
For a project that has both End-to-End and Component tests, I would like to run component tests on every PR that changed front end code, while only running both when part of the deployment workflow

It would be great if there was a boolean Action input of `end-to-end` that defaults to True, like there is one for component today:

https://github.com/cypress-io/github-action/blob/09bb8f7a6f0da4d27d435775ed647ddd69e7166e/action.yml#L90-L93

---

The current workaround that I've seen separate E2E tests like this: https://github.com/cypress-io/github-action/issues/703#issuecomment-1505594534

- https://github.com/noisy/portfolio/blob/1b4e6ece4732bd4a880fb52eb4f8662ccd66e299/.github/workflows/cypress-tests-on-master-branch.yml
- https://github.com/noisy/portfolio/blob/1b4e6ece4732bd4a880fb52eb4f8662ccd66e299/cypress.config.ts
- https://github.com/noisy/portfolio/blob/1b4e6ece4732bd4a880fb52eb4f8662ccd66e299/cypress.config.e2e.ts
- https://github.com/noisy/portfolio/blob/1b4e6ece4732bd4a880fb52eb4f8662ccd66e299/cypress.config.components.ts

**Comment by MikeMcC399** [comment]
@KyleKing 

```yml
component: true   # runs Cypress in component test mode
component: false  # runs Cypress in E2E test mode
# no component parameter specified runs Cypress in E2E test mode by default
```

Since component test and E2E test mode are mutually exclusive, only one parameter is necessary. If an extra parameter `end-to-end` were introduced, then additional checks would need to be implemented to ensure that `component` and `end-to-end` parameters were not conflicting.
