### ISSUE TITLE
Failed on running action with node version 18.18.1

### ISSUE THREAD

**Issue by lucasbatier** [cypress-io/github-action#1052]
Here is the error message on my github actions: 
```
The engine "node" is incompatible with this module. Expected version "18.18.1". Got "18.18.0"
```

Here is the workflow file

```yaml
name: Manual Cypress Tests

on:
    workflow_dispatch:

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cypress run
              uses: cypress-io/github-action@v6
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
              with:
                  config: "viewportWidth=${{ matrix.viewport[0] }},viewportHeight=${{ matrix.viewport[1] }}"
                  browser: ${{ matrix.browser }}
                  group: ${{ matrix.browser }}-${{ matrix.viewport[0] }}x${{ matrix.viewport[1] }}
                  build: yarn run build
                  start: yarn start_dev
                  wait-on: "http://localhost:3000"
                  wait-on-timeout: 300
                  record: true
                  parallel: true
        strategy:
            matrix:
                browser: [chrome, firefox, edge]
                viewport: [[1920, 1080], [375, 667]]
                include:
                    - browser: chrome
                    - viewport: [1920, 1080]
```

Here is the beggining of the package.json file

```json
{
  "name": "vadimap-client-platform",
  "version": "2.0.0",
  "private": true,
  "engines": {
    "node": "^18.18.0"
  },
  ...
}
```
