### ISSUE TITLE
Intermittent EPIPE write failure uploading media

### ISSUE THREAD

**Issue by michael1visser** [cypress-io/github-action#1060]
In the past several months we have seen intermittent failures of cypress container test runs because of an error related to uploading videos and images. All tests pass but the container fails the test run fails because of the error. 

It does not always fail on the same test file, nor does there appear to be any specific pattern to the failures. We'll see several in a day or week, and then none for the following week. 

```
write EPIPE
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writevGeneric (node:internal/stream_base_commons:143:3)
    at Socket._writeGeneric (node:net:815:11)
    at Socket._writev (node:net:824:8)
    at doWrite (node:internal/streams/writable:406:12)
    at clearBuffer (node:internal/streams/writable:561:5)
    at Writable.uncork (node:internal/streams/writable:348:7)
    at p.sendFrame (<embedded>:2404:495920)
    at p.dispatch (<embedded>:2404:495107)
    at p.send (<embedded>:2404:494940)
    at A.send (<embedded>:2404:505537)
    at _._enqueueCommand (<embedded>:2404:525846)
    at <embedded>:2404:523361
    at new Promise (<anonymous>)
    at _.send (<embedded>:2404:523335)
    at k.send [as sendDebuggerCommandFn] (<embedded>:4557:77430)
    at _.<anonymous> (<embedded>:4557:50879)
    at _.emit (node:events:527:28)
    at _._handleMessage (<embedded>:2404:525699)
    at A.<anonymous> (<embedded>:2404:525307)
    at A.emit (node:events:527:28)
    at g.U (<embedded>:2404:510587)
    at g.emit (node:events:527:28)
    at g.dataMessage (<embedded>:2404:490962)
    at <embedded>:2404:490494
    at <embedded>:2404:481816
    at <embedded>:2404:482768
    at afterWrite (node:internal/streams/writable:497:5)
    at onwrite (node:internal/streams/writable:477:7)
    at Zlib.cb (node:internal/streams/transform:202:7)
    at Zlib.processCallback (node:zlib:611:8)
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

our setup in the action is as follows:

```
jobs:
  cypress-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2,3,4,5]
      services:
           etc....
```

```
steps
    - name: Cypress run
          uses: cypress-io/github-action@v4
          with:
              start: yarn start:e2e
              wait-on: 'http://localhost:3000'
              wait-on-timeout: 200
              record: true
              parallel: true
          env:
             <our_variables>
```
Please let me know if you need anything else to troubleshoot.
