### ISSUE TITLE
NX monorepo missing package manager lockfile

### ISSUE THREAD

**Issue by Lezzio** [cypress-io/github-action#1079]
Hi,

I'm running a NX monorepo with pnpm as a package manager and I wish to use Cypress cloud with this GitHub action integration to trigger the tests on chosen apps.

I have a folder apps which contains all our web applications, I try to run Cypress as such in a workflow:

```
on:
  pull_request:
    types: [opened, synchronize, reopened]

name: ⛷ Preview Tests

permissions:
  actions: read
  contents: read
  deployments: write
  id-token: write
  packages: write
  security-events: write
  statuses: read

defaults:
  run:
    shell: bash

jobs:
  test-preview-env:
    name: 💨 Run Smoke Tests
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      AKAMAI_CLIENT_ID: [YOUR_AKAMAI_CLIENT_ID]
      AKAMAI_OWNER_CLIENT_ID: [YOUR_AKAMAI_OWNER_CLIENT_ID]
      APP_URL: [YOUR_APP_URL]
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ARN_GITHUB_TEST }}
          aws-region: us-east-1
      - name: '🌳 Setup job environment variables'
        run: |
          app_id=$(aws amplify list-apps --query "apps[?name=='HCP Portal'].appId" --output text)
          echo "APP_ID=$app_id" >> $GITHUB_ENV
      - name: Extract AKAMAI_FR_ACCESS
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          FR_ACCESS=$(echo "${{ secrets.AKAMAI_SECRETS }}" | base64 --decode | jq -r '.fr.access')
          echo "AKAMAI_FR_ACCESS=$FR_ACCESS" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref }}
      - uses: pnpm/action-setup@v2.2.4
        with:
         version: 8.3.1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'
      - name: Configure .npmrc file
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - name: Install Dependencies
        run: pnpm install
      - name: Cypress run smoke tests
        uses: cypress-io/github-action@v6
        with:
          install: true
          working-directory: ./apps/campus
          command: pnpm cypress run
          config-file: cypress.config.ts
          spec: cypress/smoke/**/*
          config: baseUrl=[YOUR_BASE_URL]
          wait-on: https://pr-${{ env.PR_NUMBER }}.${{ env.APP_URL }}
          wait-on-timeout: 900
          group: "UI - Chrome"
          browser: chrome
          record: true
          parallel: false # Runs test in parallel using settings above
          env: AKAMAI_OWNER_CLIENT_SECRET=${{ env.AKAMAI_FR_ACCESS }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.HCP_PORTAL_CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
```

However, I am getting the following error:
`Error: Action failed. Missing package manager lockfile. Expecting one of package-lock.json (npm), pnpm-lock.yaml (pnpm) or yarn.lock (yarn) in working-directory /home/runner/work/hcpportal-front-web/hcpportal-front-web/apps/campus`

Which is expected given the code:
https://github.com/cypress-io/github-action/pull/848

How can we make it work and compatible with monorepos ?  The package manager lockfile is only at the root of the monorepo and not in each of its application. Would it be possible to configure the location of the package manager lockfile ?
