### ISSUE TITLE
Can't run Firefox in tests and use docker containers

### ISSUE THREAD

**Issue by vanbenj** [cypress-io/github-action#109]
To run Firefox we need to use:

```
container:
  image: cypress/browsers:node12.16.1-chrome80-ff73
  options: --user node
```

but this image does not have ```docker-compose``` installed

**Comment by bahmutov** [comment]
I tried to just specify the user - but GitHub Actions don't allow you to do something like

```yaml
runs-on: ubuntu-latest
container:
  # "magical" user id that matches id for created home folder
  # https://github.com/cypress-io/github-action/issues/104
  options: --user 1001
```

or even switch user inside the container.

So any outside help is welcome!
