### ISSUE TITLE
new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);

### ISSUE THREAD

**Issue by CaiqueCoelho** [cypress-io/github-action#1100]
I'm getting the following error when running the cypress-io/github-action on v5 or v6:

```
Signal received: 0, errno: 0
################################################################################
Stack trace:
################################################################################
/home/runner/work/openid_server_code/openid_server_code/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_backtrace_print+0x41) [0x7f004fc16a71]
/home/runner/work/openid_server_code/openid_server_code/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0x82c73) [0x7f004f8adc73]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7f005def0420]
node() [0xa963ba]
node(_ZN2v88internal7Isolate38RunHostImportModuleDynamicallyCallbackENS0_6HandleINS0_6ScriptEEENS2_INS0_6ObjectEEENS0_11MaybeHandleIS5_EE+0x101) [0xed1141]
node(_ZN2v88internal25Runtime_DynamicImportCallEiPmPNS0_7IsolateE+0x9b) [0x12e78db]
node() [0x170e0b4]
/home/runner/work/_actions/cypress-io/github-action/v5/dist/index.js:3900
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                        ^

Error: The process '/opt/hostedtoolcache/node/18.19.0/x64/bin/npm' failed with exit code 255
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v5/dist/index.js:3900:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v5/dist/index.js:3883:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v5/dist/index.js:3777:27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

Looks like this problem is happening for more users on the following issue on Cypress repository https://github.com/cypress-io/cypress/discussions/24296

Cypress Version: 12.6.0
runs-on: ubuntu-20.04

My worklow.yml:
```
name: Cypress Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, unlocked]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  cypress-raidiam:
    runs-on: ubuntu-20.04 # needed for mongo import
    if: github.event.pull_request.draft == false
    timeout-minutes: 15
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Mongo
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: 6
          mongodb-replica-set: test-rs

      - name: Launch Localstack
        run: |
          echo "Install aws localstack"
          pip install awscli-local==0.21
          pip install localstack-client==2.5
          pip install awscli==1.29.73
          pip install boto3==1.28.73
          pip install docutils==0.16
          pip install botocore==1.31.73
          pip install rsa==4.7.2
          pip install s3transfer==0.7.0
          pip install jmespath==1.0.1
          pip install python-dateutil==2.8.2
          echo "awscli and awslocal installed"
          echo "Starting Local Stack"
          docker compose -f docker-compose-localstack.yml up -d
          sleep 10
          bash .aws/localstack.sh
          bash create-resources.sh

      - name: Cypress Run Raidiam
        uses: cypress-io/github-action@v5 # needed for node v18
        with:
          build: npm run build:cypress
          start: npm run cypress:test
          wait-on: 'http://localhost:9000/session/end'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: false
          group: ${{ env.TAG }}
          tag: ${{ env.TAG }}
        env:
          CYPRESS_grepTags: ${{ env.TAG }}
```
