### ISSUE TITLE
Commit message missing from Cypress Cloud when cypress/included container is used in GitHub Actions

### ISSUE THREAD

**Issue by verheyenkoen** [cypress-io/github-action#1129]
### Description

When we let Cypress tests run on the container cypress/included, commit message is no longer logged in Cypress Cloud. The commit hash is still there but no link to click.

### URL of Issue(s)

https://cloud.cypress.io/projects/fm8w1c/runs/71/overview

### Steps to replicate

1. Add these last two lines to your workflow yaml file for a recorded run as [described here](https://docs.cypress.io/guides/continuous-integration/github-actions#Testing-with-Cypress-Docker-Images):

```yml
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/included
```

2. Commit and push to GitHub
3. Rerun the workflow on GitHub Actions
4. Commit message is missing from Cypress Cloud

<img width="720" alt="image" src="https://github.com/cypress-io/cypress-documentation/assets/599538/d46701b9-126b-4bb3-9149-3f7a4bd7dc81">

When you remove these again, the necessary information reappears.

### Browser

n/a

### Device

- [ ] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

GITHUB token is provided as an ENV variable, like so: https://github.com/ugent-library/deliver/blob/fa660f2f7eb801315311c00de37263d6cf53aacf/.github/workflows/cypress-tests.yml#L35

**Comment by MikeMcC399** [comment]
@verheyenkoen 

Thanks for reporting the issue that the commit message is missing in Cypress Cloud if you are using a Cypress Docker container like this:

```yml
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/included
```

It seems that this is a permissions issue, as I am able to reproduce the situation:
- no commit MESSAGE shown on Cypress Cloud
- Numerical COMMIT is shown on Cypress Cloud, however it is not a hyperlink back to the GitHub repo

After adding the Docker user `1001` as below the commit MESSAGE was shown and the COMMIT was a hyperlink.

```yml
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:latest
      options: --user 1001
```

Would you like to try this?

I also have some other comments on your workflow. Let's get the main point sorted out first if possible though.

**Comment by MikeMcC399** [comment]
https://github.com/cypress-io/github-action#docker-image

![image](https://github.com/cypress-io/github-action/assets/66998419/c4ebfd99-f0af-4bf1-b44e-dc69f67293ac)

**Comment by verheyenkoen** [comment]
Yes, this worked, thanks!

**Comment by gkatsanos** [comment]
Hey, having the same issue. Workflow:

```yaml
jobs:
  cypress:
    runs-on: default-visable
    container:
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001
    env:
      GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}
      PUBLIC_API_URL: "https://api.staging.visable.io"
      IS_CYPRESS: "true"
      BASE_URL: "https://www.wlw-staging.de"
      REQUESTS_INTERNAL_API: "https://requests-service.internal.wlw-1.staging.visable.cloud/requests_service/internal_api"
      RECAPTCHA_SITE_KEY: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
      RECAPTCHA_SECRET_KEY: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.3
      - name: Define proper Checkout REF
        shell: bash
        run: echo "ref=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF}})" >> $GITHUB_OUTPUT
        id: extract_ref
      - uses: actions/checkout@v4
        with:
          ref: "${{ steps.extract_ref.outputs.ref }}"
      - name: setup github packages authentication
        run: 'echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}" > ~/.npmrc'
      - uses: cypress-io/github-action@v6
        id: cypress
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}
          COMMIT_INFO_BRANCH: ${{ github.ref_name }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          build: pnpm build
          start: pnpm start
          browser: chrome
      - name: cleanup repo files
        if: always()
        run: find . -mindepth 1 -delete
```
