### ISSUE TITLE
Cypress binary randomly missing with pnpm

### ISSUE THREAD

**Issue by enjikaka** [cypress-io/github-action#1138]
Branching out my case from https://github.com/cypress-io/github-action/issues/1054

I added the cypess GH action a few days ago in this repo and it has run fine, until I open a PR with a version bump to a package in the monorepo and it suddenly decided to fail on the cypress binary being missing.

I've tried the following solutions after looking through old issues here:
- Add PNPM cache 
- Add Cypress binary cache
- Switch cypress gh action to `install: true`
- Tried `working-dir:` with `pnpm command` instead of `pnpm --dir workdir command`

Neither yield any different result. Still:
```
> @tidal-music/player@0.1.3 internal:cypress:run /home/runner/work/tidal-sdk-web/tidal-sdk-web/packages/player
> pnpm cypress run

The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /home/runner/.cache/Cypress/13.6.6/Cypress/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /home/runner/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/runner/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error
```

Mr PR with alot of different commits where I've tried different combos: https://github.com/tidal-music/tidal-sdk-web/pull/80

I hope someone is able to help finding out the issue :)

**Comment by enjikaka** [comment]
Disabled the cypress workflow in that branch and enabled it here in a new one instead: https://github.com/tidal-music/tidal-sdk-web/pull/82

Run: https://github.com/tidal-music/tidal-sdk-web/actions/runs/8157333147/job/22296765645

**Comment by MikeMcC399** [comment]
@enjikaka 

The branch https://github.com/tidal-music/tidal-sdk-web/tree/player-release/0.1.3  which I was going to look at has been deleted, so it's difficult for me to investigate your latest attempt.  (OK - I saw you just moved it.)

- In the meantime I reviewed the result of the issue https://github.com/cypress-io/github-action/issues/1054 which you tagged on to and there is a working example for a pnpm workspace in https://github.com/markoleavy/cypress-test/blob/main/.github/workflows/run_test.yml

```yml
jobs:
  run-test:
    runs-on: ubuntu-22.04
    name: Run test
    timeout-minutes: 60
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Set up Cypress binary cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: |
          pnpm i --frozen-lockfile

      - name: Test
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: ./packages/test/
          browser: chrome
```

That would probably work in principle for you too, updating the versions of the actions used and changing the directory from `test` to `player`.

**Comment by MikeMcC399** [comment]
You can let me know if you want to try that out for yourself, or if you want me to work on your branch https://github.com/tidal-music/tidal-sdk-web/tree/re-enable-cypress.

**Comment by enjikaka** [comment]
I tried that in this commit: https://github.com/tidal-music/tidal-sdk-web/blob/2f296807920c63dfffe5108b3c03112977065310/.github/workflows/cypress.yml

Output for that run was the same: https://github.com/tidal-music/tidal-sdk-web/actions/runs/8153523957/job/22285090231

**Comment by MikeMcC399** [comment]
@enjikaka 

I ran the following successfully in a fork of your repo. I suspect this failed for you previously due to the pnpm cache preventing the Cypress binary installing.

If you cache the pnpm store and then you add caching for Cypress without allowing for Cypress to install and run the postinstallation script to install the Cypress binary, then the Cypress binary will never be installed and can't be cached.

If you delete the relevant cache from https://github.com/tidal-music/tidal-sdk-web/actions/caches after you have added Cypress binary caching then pnpm will reinstall everything and Cypress will get its binary installed and cached.

```yml
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/build-projects
      - name: Prepare test user for player tests
        id: json
        run: |
          echo ${{ env.TEST_USER }} | base64 -d > test-user.json
          json=$(cat test-user.json)
          replacement=${{ secrets.PLAYER_REFRESH_TOKEN }}
          fixed_json="$(echo ${json/\[TOKEN\]/$replacement})"
          encoded_json=$(echo "$fixed_json" | base64 | tr -d '\n')
          echo "encoded=\"$encoded_json\"" >> $GITHUB_OUTPUT
        env:
          TEST_USER: ${{ secrets.PLAYER_TEST_USER }}

      - name: Set up Cypress binary cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm --dir packages/player/ cypress:cache:path
      - run: pnpm --dir packages/player/ cypress:cache:list
      - run: pnpm --dir packages/player/ cypress:verify

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_TEST_USER: ${{ steps.json.outputs.encoded }}
        with:
          install: false
          browser: chrome
          start: pnpm --dir packages/player/ dev
          wait-on: 'http://localhost:5173/demo/test-case-1.html'
          command: pnpm --dir packages/player/ internal:cypress:run

```
