### ISSUE TITLE
App frontend is not reachable, on random test runs

### ISSUE THREAD

**Issue by ydennisy** [cypress-io/github-action#1141]
Hi!

We have certain test runs, and usually a single machine from our parallel split where around 70% of tests fail, the failures are all the same where cypress cannot connect to the homepage of the app.

We are using the cypress GH action v6, `wait-on` runs and confirms both server and ui are up.

```
Skipping install because install parameter is false
start server command "npm run dev"
current working directory "/home/runner/work/studio/studio/app"
waiting on "http://localhost:3000,http://localhost:8000/app-backend/api/health" with timeout of 120 seconds
/opt/hostedtoolcache/node/20.11.1/x64/bin/npm run dev

> web-app@0.0.266 dev
> CONTEXT=local vite

[sentry-vite-plugin] Info: Sending error and performance telemetry data to Sentry.
[sentry-vite-plugin] Info: To disable telemetry, set `options.telemetry` to `false`.

  VITE v4.5.2  ready in 559 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
It looks like this is your first time using Cypress: 13.6.2

[STARTED] Task without title.
[SUCCESS] Task without title.

Opening Cypress...

DevTools listening on ws://127.0.0.1:40329/devtools/browser/a439dd4d-0435-4bc2-9ee4-6797a[58](https://github.com/AirGrid/studio/actions/runs/8188017819/job/22389735399?pr=3349#step:9:59)3b82e
[8372:0307/122804.674439:ERROR:object_proxy.cc([59](https://github.com/AirGrid/studio/actions/runs/8188017819/job/22389735399?pr=3349#step:9:60)0)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: unknown error type:
```

one of the specs:

```
0 passing (31s)
  13 failing

  1) Audience performance
       Audience performance page
         should load audience performance page with mock data:
     CypressError: `cy.visit()` failed trying to load:

http://localhost:3000/login

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:3000

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:130947:74)
      at visitFailedByErr (http://localhost:3000/__cypress/runner/cypress_runner.js:130[339](https://github.com/AirGrid/studio/actions/runs/8188017819/job/22389735399?pr=3349#step:9:340):12)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:130946:11)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:1519:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:1576:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:1621:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:1697:18)
      at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:2407:12)
      at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:2400:9)
      at Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:2416:5)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:2286:14)
  From Your Spec Code:
      at signInUser (webpack://web-app/./cypress/support/commands.ts:129:5)
      at Context.eval (webpack://web-app/./cypress/support/commands.ts:177:2)
  
  From Node.js Internals:
    Error: connect ECONNREFUSED 127.0.0.1:3000
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```

Has anyone seen this sort of behaviour before?

**Comment by MikeMcC399** [comment]
@ydennisy 

Could you share your workflow?

**Comment by ydennisy** [comment]
@MikeMcC399 sure thanks for the speedy reply!

```yaml
name: "[Studio] E2E test"

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - app/**
      - backend/**
    types:
      - opened
      - reopened
      - ready_for_review

  workflow_dispatch: {}

jobs:
  test-app-e2e:
    name: Run e2e tests
    if: ${{ github.event.pull_request.draft == false && (contains(github.head_ref, 'release/') && github.base_ref == 'develop') == false}}
    runs-on: ubuntu-latest-m
    strategy:
      fail-fast: false
      matrix:
        containers:
          [1, 2, 3, 4]
    env:
      GCP_PROJECT: ******
      GCP_REGION: europe-west1
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_DEV }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Google Cloud Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_CREDENTIALS }}

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install & start supabase
        working-directory: backend
        run: |
          wget https://github.com/supabase/cli/releases/download/v1.136.3/supabase_1.136.3_linux_amd64.deb
          sudo dpkg -i supabase_1.136.3_linux_amd64.deb
          supabase start -x imgproxy,edge-runtime,studio,storage-api

      - name: Install frontend deps
        working-directory: app
        run: npm ci

      - name: Install backend deps, build, seed & run
        working-directory: backend
        run: |
          npm ci
          npm run build
          npm run prisma:seed
          npm start &
        env:
          .... removed

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.ci.ts
          config: '{"e2e": { "excludeSpecPattern": [ "cypress/e2e/xandr/**/*.e2e.ts", "cypress/e2e/**/google.e2e.ts","cypress/e2e/smoke/**/*.e2e.ts"] }}'
          browser: chrome
          # we have already installed all dependencies above
          install: false
          start: npm run dev
          working-directory: app
          record: true
          parallel: true
          group: "FullE2E"
          wait-on: http://localhost:3000,http://localhost:8000/app-backend/api/health
          wait-on-timeout: 120

        env:
          HOSTNAME: localhost
          PORT: 3000
          HTTPS: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
          ENV_NAME: testing
          .... removed
```
