### ISSUE TITLE
`project` not working

### ISSUE THREAD

**Issue by fhnaumann** [cypress-io/github-action#1174]
I have a monorepo and in one folder of main repo I have my website with cypress tests. I want to use this action to run e2e tests in the folder. 

```yml
name: Cypress E2E

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: ./folder
          build: npm run build
          start: npm start
```

This workflow fails in the cypress run step with the following message:
```
Error: Action failed. Missing package manager lockfile. Expecting one of package-lock.json (npm), pnpm-lock.yaml (pnpm) or yarn.lock (yarn) in working-directory /home/runner/work/NewChallenges/NewChallenges
```
I suspect this is because the action tries to do stuff in the root folder and not the specified subfolder. How can I solve this?
