### ISSUE TITLE
adding user 1001 throws EACCES permission issue

### ISSUE THREAD

**Issue by gkatsanos** [cypress-io/github-action#1175]
I tried adding `      options: --user 1001` to ensure commit name / information are shown on my cypress cloud runs.
But doing so, throws an EACCES permission issue.

```yaml
jobs:
  cypress:
    runs-on: default-visable
    container:
      image: cypress/browsers:node-18.14.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
      options: --user 1001
    env:
      GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}
      PUBLIC_API_URL: "https://api.staging.visable.io"
      IS_CYPRESS: "true"
      BASE_URL: "https://www.wlw-staging.de"
      REQUESTS_INTERNAL_API: "https://requests-service.internal.wlw-1.staging.visable.cloud/requests_service/internal_api"
      RECAPTCHA_SITE_KEY: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
      RECAPTCHA_SECRET_KEY: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.3
      - name: Define proper Checkout REF
        shell: bash
        run: echo "ref=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF}})" >> $GITHUB_OUTPUT
        id: extract_ref
      - uses: actions/checkout@v4
        with:
          ref: "${{ steps.extract_ref.outputs.ref }}"
      - name: setup github packages authentication
        run: 'echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}" > ~/.npmrc'
      - uses: cypress-io/github-action@v6
        id: cypress
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}
          COMMIT_INFO_BRANCH: ${{ github.ref_name }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          build: pnpm build
          start: pnpm start
          browser: chrome
      - name: cleanup repo files
        if: always()
        run: find . -mindepth 1 -delete
```

![image](https://github.com/cypress-io/github-action/assets/1768834/16b69da0-d775-41c0-a836-d2d7f4e5e472)

I also tried to do what was suggested in https://github.com/cypress-io/github-action/issues/1129#issuecomment-1944303998 add options: --user 1001 but I get permissions issues.

**Comment by MikeMcC399** [comment]
The [Docker image](https://github.com/cypress-io/github-action?tab=readme-ov-file#docker-image) section of the documentation says:

> Include `options: --user 1001` to avoid permissions issues.

This is missing from the workflow posted above.

**Comment by gkatsanos** [comment]
sure, trying that just to make it clearer:

```yaml
jobs:
  cypress:
    runs-on: default-visable
    container:
      image: cypress/browsers:node-18.14.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
      options: --user 1001
    env:
      GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}
      PUBLIC_API_URL: "https://api.staging.visable.io"
      IS_CYPRESS: "true"
      BASE_URL: "https://www.wlw-staging.de"
      REQUESTS_INTERNAL_API: "https://requests-service.internal.wlw-1.staging.visable.cloud/requests_service/internal_api"
      RECAPTCHA_SITE_KEY: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
      RECAPTCHA_SECRET_KEY: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.3
      - name: Define proper Checkout REF
        shell: bash
        run: echo "ref=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF}})" >> $GITHUB_OUTPUT
        id: extract_ref
      - uses: actions/checkout@v4
        with:
          ref: "${{ steps.extract_ref.outputs.ref }}"
      - name: setup github packages authentication
        run: 'echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}" > ~/.npmrc'
      - uses: cypress-io/github-action@v6
        id: cypress
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}
          COMMIT_INFO_BRANCH: ${{ github.ref_name }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          build: pnpm build
          start: pnpm start
          browser: chrome
      - name: cleanup repo files
        if: always()
        run: find . -mindepth 1 -delete
```

ci output:

```
0s
Run pnpm/action-setup@v3
/usr/bin/docker exec  d7472bbeaff8694ddc8da[1](https://github.com/visable-dev/requests-frontend/actions/runs/9001862118/job/24728966119#step:3:1)641958f6af298fe18bad1f83ffbe64038a2fd1006f sh -c "cat /etc/*release | grep ^ID"
Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_c5aa5db7-4546-4d2d-95eb-fc1f342[16](https://github.com/visable-dev/requests-frontend/actions/runs/9001862118/job/24728966119#step:3:17)615'
    at Object.open (node:internal/fs/sync:78:18)
    at Object.openSync (node:fs:565:17)
    at Object.writeFileSync (node:fs:2288:35)
    at Object.appendFileSync (node:fs:2350:6)
    at Object.issueFileCommand (/__w/_actions/pnpm/action-setup/v3/dist/index.js:1:14731)
    at saveState (/__w/_actions/pnpm/action-setup/v3/dist/index.js:1:12889)
    at main (/__w/_actions/pnpm/action-setup/v3/dist/index.js:1:425)
    at 276 (/__w/_actions/pnpm/action-setup/v3/dist/index.js:1:539)
    at __nccwpck_require__ (/__w/_actions/pnpm/action-setup/v3/dist/index.js:10:243127)
    at /__w/_actions/pnpm/action-setup/v3/dist/index.js:10:243312 {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/__w/_temp/_runner_file_commands/save_state_c5aa5db7-4546-4d2d-95eb-fc1f34[21](https://github.com/visable-dev/requests-frontend/actions/runs/9001862118/job/24728966119#step:3:22)6615'
}
Error: Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_c5aa5db7-4546-4d2d-95eb-fc1f34216615'
```
