### ISSUE TITLE
Nested projects example + docs are incorrect

### ISSUE THREAD

**Issue by JessicaSachs** [cypress-io/github-action#119]
**Summary**
Documentation for handling nested projects is out of date/incorrect.

The README example for the [working-directory option](https://github.com/cypress-io/github-action#working-directory) shows that the folder structure below should work with a configuration that sets `working-directory: e2e`. This is not the case.

**File structure:**
```
repo/
  app/
  e2e/
    cypress
    cypress.json
  package.json
```

**README's proposed Github Action yml:**
```yml
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        with:
          start: npm start
          working-directory: e2e
```

When following the example above, you get an error because `e2e/package-lock.json` doesn't exist. ([reproduction](https://github.com/JessicaSachs/cypress-test-nested-projects/actions/runs/63394918/workflow))

This installation behavior is likely needed for the related submodules example, where both the root of the application and the subdirectory have a `package.json`.

To get the nested project structure working, a workaround is outlined in an [example project](https://github.com/bahmutov/cypress-gh-action-monorepo/blob/master/.github/workflows/test.yml) and it requires the user to separate the install and the test running into two different steps.

**Proposed solution**
1. We could update the docs to reflect the workaround and continue to require two steps
2. We could implement the existing `--project` flag (used in the [nested-project example](https://github.com/cypress-io/cypress-test-nested-projects/blob/master/package.json#L8-L10)) and add better support for nested projects
