### ISSUE TITLE
Question: are artifacts shared across parallel jobs?

### ISSUE THREAD

**Issue by afontcu** [cypress-io/github-action#122]
_(Feel free to close this up if GH issues is not the place to ask this kind of questions 😄)_

Hi! 👋 

I'm running tests in parallel, and I noticed all runs take almost the same time. I'd expect artifacts to be shared across runs (both `node_modules` but also the build artifact as I'm using the `build` key).

Am I right expecting so? 

Just in case, this is my action config:

```yml
name: Cypress tests

on: ['push']

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build:staging
          start: npm run nuxt:start
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Thank you very much! 😃
