### ISSUE TITLE
option to always return SUCCESS to GHA job step

### ISSUE THREAD

**Issue by irbrad** [cypress-io/github-action#1237]
I have a suite of tests that are acceptable if they fail and I'd like to have always have a green bubble on that actions job step to remove confusion of what appears to be a failing step.  Would it be possible (or does this already exist) to always return a SUCCESS?  I think Actions is picking up the text "Error" in the log output and changing that to a ❌.

My current workaround is just to name the Actions job as "nonblocking" but it seems like there should be a better way to do this.

**Comment by MikeMcC399** [comment]
@irbrad 

Could you please post your workflow?

**Comment by irbrad** [comment]
> Could you please post your workflow?

The Cypress portion of the workflow is as follows.  This area of the workflow does have _continue-on-error_ enabled.  `new_desktop_run_tests` is generated with a bash step that searches for specific tags in the specs using _cypress-grep_.  The action step isn't necessarily blocking deployments but it appears like it is.  These are new tests that we are inserting into our CI process that need to be proved out before we move them into a position that they can block the deployment pipeline.

```yaml
      - name: ${{ 'test pr-${{ github.event.number }} ${{needs.prep.outputs.short_sha}}' }}
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./test
          browser: chrome
          record: ${{ inputs.record }}
          parallel: true
          install: false
          runTests: ${{ needs.prep.outputs.new_desktop_run_tests }}
          group: "Integration - Chrome - Desktop"
          spec: ${{ needs.prep.outputs.new_desktop_files }}
          config: '{"e2e": { "excludeSpecPattern": "cypress/integration/**/*.skip-ci.spec.js" } }'
          tag: ${{ inputs.cypress-cloud-base-tag }}
          ci-build-id: "${{ inputs.ci-build-id }}-new"
          publish-summary: false
```
