### ISSUE TITLE
Fail gracefully if `GITHUB_TOKEN` is set with non-working permissions

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#1272]
## What would you like?

If `GITHUB_TOKEN` is passed to the action when recording to Cypress Cloud and permissions are restricted, the workflow may fail with an error such as:

> Unable to fetch related PR data for commit: '46a72ff9cd29aeaa59f536eee6c008e3ffbcf56d':  RequestError [HttpError]: Resource not accessible by integration

Make the error message more user friendly, including suggestions on how to remedy.

Possibly also allow the workflow to continue with reduced functionality.

## Why is this needed?

As documented in the README [Automatic PR number and URL detection](https://github.com/cypress-io/github-action/blob/master/README.md#automatic-pr-number-and-url-detection), if the `GITHUB_TOKEN` is set when recording to Cypress Cloud, PR information is extracted.

Restrictive [permissions for the GITHUB_TOKEN](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) can however have been set in the enterprise, organization, repository or workflow which prevent this working.

Users are sometime confronted with this error and do not know what to do.

### Related issues

- https://github.com/cypress-io/github-action/issues/1208

**Comment by MikeMcC399** [comment]
This is a topic for the Cypress Cloud team.

**Comment by VolodymyrSmahliuk** [comment]
I'm not sure where to post my findings, but this issue seems related.

When working with [Cypress Test in Parallel mode](https://github.com/marketplace/actions/cypress-io#parallel), we faced the permissions issue. I'm going to list the error and appropriate permissions to fix

(FYI, we have the next GitHub Repository Workflow permissions)

![Image](https://github.com/user-attachments/assets/b2827349-ead9-4715-8d3e-b7efcfea5343)

---

The basic GitHub Actions permissions were:

```yaml
permissions:
  id-token: write # This is required for requesting the JWT (OIDC with AWS)
  contents: read # This is required for actions/checkout
```

We get the `Resource not accessible by integration` ERROR with additional context:

```js
Unable to fetch related PR data for commit: '036ae73a1d19191920992eea737e69adc760014d':  RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:41021:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async detectPrNumber (/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:98218:22)
    at async runTests (/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:98489:3) {
  status: 403,
```

```js
headers: {
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-github-permissions': 'pull_requests=read',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
}
```

According to the GitHub headers (**which are extremely informative**) the fix was adding the `pull-requests: read` permission:

```yaml
permissions:
  id-token: write # This is required for requesting the JWT (OIDC with AWS)
  contents: read # This is required for actions/checkout
  pull-requests: read # This is required for Cypress run
```

After that, the same ERROR, but no context in the logs anymore

![Image](https://github.com/user-attachments/assets/5ee733cb-f092-47cf-8db8-4fb68eb5e544)

After some investigation by updating the permissions, I found the required one (`actions: write`):

```yaml
permissions:
  id-token: write # This is required for requesting the JWT (OIDC with AWS)
  contents: read # This is required for actions/checkout
  pull-requests: read # This is required for Cypress run
  actions: write # This is required for Cypress run
```

Now I have the job result

![Image](https://github.com/user-attachments/assets/17140598-70d7-468e-94f5-03d1f6300bde)

**I hope it will help to anyone** 🎉

PS: let's like the https://github.com/cypress-io/github-action/issues/1273 Issue to provide documentation update!
