### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:5173

### ISSUE THREAD

**Issue by CaiqueCoelho** [cypress-io/github-action#1280]
I'm trying to add a container image for cypress/browsers and setting browser as chrome to run Cypress tests in the GHA with cypress-io/github-action@v6 but I'm getting the following error

`Error: connect ECONNREFUSED 127.0.0.1:5173`

This is my config:
```
jobs:
  cypress-super-user:
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node-20.18.0-chrome-129.0.6668.89-1-ff-131.0.2-edge-129.0.2792.65-1
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    timeout-minutes: 180
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          submodules: recursive
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Install Dependencies
        run: npm i

      - name: Run directory_ui
        run: npm run serve &

      - name: Cypress Tests 🧪
        uses: cypress-io/github-action@v6.7.6
        with:
          record: true
          parallel: true
          browser: chrome
          wait-on: "http://localhost:5173/"
          wait-on-timeout: 180
          env: userType=userSuperAdminType
          group: Raidiam - Super Admin
          config: baseUrl=http://localhost:5173
```

If I remove the container from the job Cypress is able to connect to 127.0.0.1:5173 and all tests pass

Additional Information:
I'm using VUE version 2.7.14 and VITE version 5.4.6
Cypress version 13.15.0
