### ISSUE TITLE
wait-on does not detect my running server in my turborepo project

### ISSUE THREAD

**Issue by tomitrescak** [cypress-io/github-action#1286]
Hello, I followed your advice to run the server on 0.0.0.0 but the server is still not detected that it runs.
This is the message how it hangs up:

![image](https://github.com/user-attachments/assets/b6dd3fec-cb2c-4589-8ff4-20fd5c9c81c1)

AND THIS IS MY ACTION. Not that I have a monorepo with cypress in a separate folder, not sure how can I make this run ;(

```yaml
name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0
      - uses: pnpm/action-setup@v2
        with:
          version: 9.4.0
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Install dependencies 🧪
        uses: cypress-io/github-action@v6
        with:
          # just perform install
          runTests: false
      - name: Build the project 🏗
        run: pnpm turbo build
      - name: Start the server 🚀
        working-directory: apps/web/
        run: nohup pnpm start -H 0.0.0.0 &
      - name: Run Cypress tests 🧪
        uses: cypress-io/github-action@v6
        with:
          working-directory: apps/cypress/
          install: false
          browser: chrome
          wait-on: "http://0.0.0.0:3000" # Waits for abov

```
