### ISSUE TITLE
Cypress Component Tests Timing Out in Github Action

### ISSUE THREAD

**Issue by LiamF-FS** [cypress-io/github-action#1298]
# Summary

I am encountering a time out within all cypress component tests when running tests via a Github Action. This error does NOT occur locally.

This is Vue3/Vite Project, I am using nyc & istanbul for code coverage.

The Action is using Node 20.11.0 & `cypress-io/github-action@v6.1.0`.

I have tried to increase the `defaultCommandTimeout`, initialize retries, etc. 

Any and all feedback would be greatly appreciated - the error, an example test, and the Action I am running can be seen below.

## Error

```
1) 
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `.asset-drawer-container`, but never found it.
      at Context.<anonymous> (AssetDrawer.cy.js:37:62)
      at runnable.fn (http://localhost:5173/__cypress/runner/cypress_runner.js:138202:19)
      at callFn (http://localhost:5173/__cypress/runner/cypress_runner.js:156818:21)
      at Runnable.run (http://localhost:5173/__cypress/runner/cypress_runner.js:156805:7)
      at <unknown> (http://localhost:5173/__cypress/runner/cypress_runner.js:162729:30)
      at PassThroughHandlerContext.finallyHandler (http://localhost:5173/__cypress/runner/cypress_runner.js:4072:23)
      at PassThroughHandlerContext.tryCatcher (http://localhost:5173/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://localhost:5173/__cypress/runner/cypress_runner.js:1519:31)
```

## Example Test

```
    it('drawer opens and closes', function() {
        this.assetStore.drawerOpen = true;        
        cy.get('.asset-drawer-container').should('exist').and('have.class', 'open');
        
        cy.get('[data-cy=close-icon]').click();

        cy.get('.asset-drawer-container').should('exist').and('have.class', 'closed');
    });
```

## Github Action

```
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./client
    name: Cypress Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'
      - name: Run Cypress component tests
        uses: cypress-io/github-action@v6.1.0
        with:
          working-directory: ./client
          component: true
          browser: electron
          
```
