### ISSUE TITLE
Cypress timing out inside Github action 

### ISSUE THREAD

**Issue by BilalBudhani** [cypress-io/github-action#1306]
# Issue 

We have been running Cypress inside Github actions CI successfully for a couple of years. However, a couple of months ago it started failing without any updates in the CI script itself. 

Here are the details of our setup 

ci.yml

```yaml
cypress:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: [ '5432:5432' ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: yarn

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "0.0.0.0 lvh.me" | sudo tee -a /etc/hosts
          sudo echo "0.0.0.0 js.lvh.me" | sudo tee -a /etc/hosts

      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/development
          PG_USER: postgres
          RAILS_ENV: test
          APP_URL: http://lvh.me:3000
          SCRIPT_URL: http://js.lvh.me:3000
          APP_PROTOCOL: http
          PORT: 3000
          CYPRESS: 1
          DEBUG: 'cypress:server:run'
        with:
          build: bundle exec rails test:prepare db:test:prepare assets:precompile
          browser: chrome
          start: bundle exec rails server
          wait-on: 'http://lvh.me:3000, http://js.lvh.me:3000'
```

Snippets from the logs 

```
Cypress:        9.7.0                                                                          │
  │ Browser:        Chrome 130 (headless)                                                          │
  │ Node Version:   v20.13.1 (/home/runner/runners/2.320.0/externals/node20/bin/node)              
```

```
Running:  script/cookies.spec.js                                                          (1 of 8)
  cypress:server:run video recording has been disabled. video: false +1ms
  cypress:server:run waiting for socket to connect and browser to launch... +1ms
  cypress:server:run waiting for socket connection... { id: 'jjkkh' } +0ms
  cypress:server:run setting Chrome properties { shouldWriteVideo: false } +0ms
  cypress:server:run browser launched +0ms
  cypress:server:run got socket connection { id: 'jjkkh' } +2s
  cypress:server:run socket connected { socketId: 'jjkkh' } +1ms
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

  Visitor Cookies
    Fresh Cookies
      when visitor makes a new visit
2024-11-14T09:23:36.545Z pid=2714 tid=5oeu INFO: Sidekiq 7.3.2 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://localhost:6379/0", :network_timeout=>5}
Error: The action 'Cypress run' has timed out after 10 minutes.
```

It seems like the Cypress is not able to launch Chrome browser and hence timing out but I'm not exactly sure. 

What could be wrong with this setup? How do I debug this further to be able to provide more context on the issue?
