### ISSUE TITLE
Error: missing lockfile prevents dependency installation

### ISSUE THREAD

**Issue by xinyu-hou** [cypress-io/github-action#1308]
Hi,

I am encountering an issue with the cypress-io/github-action in my GitHub Actions script. I have chosen not to commit the "package-lock.json" file in my GitHub repository, as I can generate one using the "npm install" command.

However, this seems to cause a problem when I attempt to use the cypress-io/github-action. Below is my current GitHub Actions script:

```
name: Cypress Component Tests

on:
  push:
  workflow_dispatch:

jobs:
  cypress-component-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Cypress component tests
        uses: cypress-io/github-action@v6
        with:
          install-command: npm install
          component: true
```

Here is the error message I encountered:

`Error: Action failed. Missing package manager lockfile. Expecting one of package-lock.json (npm), pnpm-lock.yaml (pnpm) or yarn.lock (yarn) in working-directory /runner/_work/xinyu-cypress-action-investigation/xinyu-cypress-action-investigation`

It appears that despite specifying the install-command, the cypress-io/github-action does not install the dependencies before running the component tests. I am curious if a "package-lock.json" file is indeed required to use the cypress-io/github-action.

Thank you for your assistance!

**Comment by MikeMcC399** [comment]
@xinyu-hou 

The default use of `cypress-io/github-action` requires a package manager lockfile to be present. This is used to install dependencies and to key caches.

According to the npm documentation, [package-lock.json](https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json) is intended to be committed into source repositories.

If you do not want to follow the recommendations of the npm documentation, and do not commit a [package-lock.json](https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json) file, then you must install dependencies before using `cypress-io/github-action` and then disable installation in the action:

```yml
uses: cypress-io/github-action@v6
with:
  install: false
```
