### ISSUE TITLE
Issue with 2 step install / restore

### ISSUE THREAD

**Issue by wyardley** [cypress-io/github-action#1351]
I'm running a 2-step install / run job on a couple projects that are using `pnpm`. This project had previously used the GH cache action directly to cache both `node_modules` and the Cypress cache, and I was trying to simplify; I was initially trying to use a simple example like https://github.com/cypress-io/github-action?tab=readme-ov-file#pnpm, but ran into issues because of running a separate build and run step.

So then I started trying to use something along the lines of:
https://github.com/cypress-io/github-action?tab=readme-ov-file#split-install-and-tests

That mostly works, but because I have some jobs that use the regular `setup-node` action with `cache: pnpm` set, I was running into some issues in terms of order of operations, and tried to switch the jobs to use a custom `cache-key`.

Slightly simplified / sanitized config:
```yaml
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          # I've also tried cache: pnpm here
      - name: Install dependencies only
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          cache-key: cypress-pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
        # Some build / cache steps here
  run:
    name: Run
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      # some restore steps from the next build here
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # [...]
          record: true
          install: false
          cache-key: cypress-pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
```

I'm getting various downstream errors with Cypress or other dependencies not being installed in the downstream job. The exact error seems to vary.

Is there a simple way to do what I'm trying to do, or is it better to continue using `actions/cache@v4` directly?
