### ISSUE TITLE
Pass value for command-prefix the output resultsUrl doesn't get set

### ISSUE THREAD

**Issue by fwyattblake** [cypress-io/github-action#1377]
When I set the input parameter: `command-prefix` the output `resultsUrl` is not set

example
```
- name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          record: true
          command-prefix: 'percy exec -- npx'
          spec: ${{ inputs.specPattern }}
          config:  baseUrl=${{inputs.baseUrl}}
          env: percy=true,degug=${{ inputs.debug }},testName=${{ inputs.testName }}
          tag: ${{ inputs.testName }}
        env:
          CYPRESS_RECORD_KEY: ${{ inputs.cypress_record_key }}
          CYPRESS_PROJECT_ID: ${{ inputs.cypress_project_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_TOKEN: ${{ inputs.percy_token }}

      - name: Print Cypress Cloud URL
        if: always()
        run: |
          echo See results at ${{ steps.cypress.outputs.resultsUrl }}

```

output

```
Recorded Run: https://cloud.cypress.io/projects/XXXXXX/runs/87 

[percy] Finalized build #22: https://percy.io/xxxxx/web/xxxxxxxx-73b3439a/builds/38645566'
[percy] Build's CLI and CI logs sent successfully. Please share this log ID with Percy team in case of any issues - 38645566_build_xxxxxxx
```

resultURL is blank.

If I remove the command-prefix, the results will be set.
