### ISSUE TITLE
CreateCacheEntry Warning

### ISSUE THREAD

**Issue by molynerd** [cypress-io/github-action#1382]
We're getting the following warning when running the action:

> Failed to save: Failed to CreateCacheEntry: Received non-retryable error: Failed request: (409) Conflict: cache entry with the same key, version, and scope already exists

Step:

```yaml
      - name: run cypress
        id: cypress
        uses: cypress-io/github-action@v6
        timeout-minutes: 20
        with:
          working-directory: foo
          browser: chrome
          record: true
          summary-title: 'My Summary'
          spec: cypress/**.spec.ts
          group: my-test-group
          ci-build-id: development-${{ needs.another-step.uuid }}
          parallel: true
          tag: report,development
          env: configFile=development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_ENV: development
          CYPRESS_INSTALL_BINARY: 0
          CYPRESS_AUTH0_CLIENT_SECRET: ${{ secrets.A }}
          CYPRESS_AUTH0_FTP_DAS_CLIENT_SECRET: ${{ secrets.B }}
          CYPRESS_FTP_PASSWORD: ${{ secrets.C }}
          CYPRESS_GUIDEWIRE_API_KEY: ${{ secrets.D }}
          CYPRESS_PROJECT_ID: redact
          CYPRESS_RECORD_KEY: ${{ secrets.E }}
          CYPRESS_SLACK_THREAD_TS: ${{ needs.another-step.thread_ts }}
          CYPRESS_SLACK_DEV_BOT_TOKEN: ${{ secrets.F }}
```

I'm not sure if this is causing any problems or just adding annoying annotations to every GHA run. We're dealing with a separate issue where GHA is failing the workflow because an internal error, and I want to whittle down the possible causes.
