### ISSUE TITLE
spec: folder?

### ISSUE THREAD

**Issue by stoplion** [cypress-io/github-action#139]
Does the `with.spec` point to a file (like on the docs) or can it point to a folder?
My project has a custom `integration` folder (I'm using Cypress-on-Rails gem).

```
name: End to end tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup-and-run:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:10
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install deps
        run: sudo apt-get install libpq-dev

      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create RAILS_ENV=test
          bundle exec rake db:schema:load RAILS_ENV=test
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v1
        with:
          start: bundle exec rails s -e test
          wait-on: http://localhost:3000
          spec: spec/cypress/integration
```

getting a ...

```
/usr/local/bin/npx cypress run --spec spec/cypress/integration --config-file cypress.json
Can't run because no spec files were found.

We searched for any files matching this glob pattern:

spec/cypress/integration
Error: The process '/usr/local/bin/npx' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1188:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1171:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1071:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
##[error]The process '/usr/local/bin/npx' failed with exit code 1
```

**Comment by jennifer-shehane** [comment]
The `with.spec` accepts the same arguments as the `spec` arg outlined in the docs: https://docs.cypress.io/guides/guides/command-line.html#cypress-run

A file, glob, or comma-separated files. This should be relative to your project root.

**Comment by stoplion** [comment]
For whatever reason, the action is not finding any spec files.

The spec files are in `spec/cypress/integration`

Trying with `with.spec`:

```
name: End to end tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup-and-run:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:10
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install deps
        run: sudo apt-get install libpq-dev

      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create RAILS_ENV=test
          bundle exec rake db:schema:load RAILS_ENV=test
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v1
        env:
          PORT: 5000
          APP_NAME: APPNAME
          ALGOLIA_API_KEY: ${{secrets.ALGOLIA_API_KEY}}
          ALGOLIA_APPLICATION_ID: ${{secrets.ALGOLIA_APPLICATION_ID}}
          ALGOLIA_ADMIN_API_KEY: ${{secrets.ALGOLIA_ADMIN_API_KEY}}
          ALGOLIA_TAG_INDEX: Tags_development
          ALGOLIA_CALC_INDEX: Calc_development
          MAX_TAG_LIST_LENGTH: 5
          MAX_TAG_STRING_LENGTH: 25
          BASE_URL: localhost:5000
        with:
          start: bundle exec rails s -e test
          wait-on: http://localhost:5000
          config-file: cypress.json
          spec: spec/cypress/integration/**/*

```

Also I've set the config file integrationFolder to point the correct folder..
```
{
  "baseUrl": "http://localhost:5000",
  "integrationFolder": "spec/cypress/integration",
  "defaultCommandTimeout": 10000,
  "projectId": "eeDee12"
}
```

Still getting a the same error.

I've also tried to get the `integrationFolder` directly in the action..

```
....
- name: Run Cypress Tests
        uses: cypress-io/github-action@v1
        with:
          start: bundle exec rails s -e test
          wait-on: http://localhost:3000
          integrationFolder: spec/cypress/integration
```

Same error..
