### ISSUE TITLE
Tests not ran: Getting "Run finished" immediately when re-running tests

### ISSUE THREAD

**Issue by MaximeHeckel** [cypress-io/github-action#147]
Hi 👋 

I'm getting a weird behavior: when re-running the Github workflow including the cypress Github action, my tests are not being ran:

```
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    4.0.1                                                                              │
  │ Browser:    Chrome 81 (headless)                                                               │
  │ Specs:      10 found (...)                                                                                  │
  │ Params:     Tag: false, Group: false, Parallel: true                                           │
  │ Run URL:    https://dashboard.cypress.io/projects/47f16h/runs/1333                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)
```

"Run finished" appears immediately after the test run has started. The task is then marked as successful

I'm using Cypress `4.0.1` with the following workflow file:

```
name: Run E2E Tests without recording
        uses: cypress-io/github-action@v1
        with:
          working-directory: ./ui
          browser: chrome
          record: true
          headless: true
          parallel: true
          start: yarn serve-built-files
          wait-on: "http://localhost:8081"
          config: defaultCommandTimeout=100000,pageLoadTimeout=100000,watchForFileChanges=false,video=false
        env:
          NODE_ENV: "test"
          CI: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Any idea what could be happening here?
