### ISSUE TITLE
wait on fails with self-signed certificates

### ISSUE THREAD

**Issue by Weetbix** [cypress-io/github-action#154]
Firstly, thanks for the great action. It's amazing to compare how much code around setup and support was required for our puppeteer tests compared to using cypress and this action so big ups for this 👍 

Currently: 
When using wait-on and a url with a self signed certificate wait on will fail with `DEPTH_ZERO_SELF_SIGNED_CERT`. This can be a bit annoying when switching to https for dev servers which is required when using subtle crypto etc. 

Wanted:
Either work by default or provide a configurable option

**Comment by trymbill** [comment]
The API I'm working against requires all front-end applications to come from a "secure" (even if it's self-signed) source and I feel like this has become more and more prevalent in the last few months.

Is there no way to bypass this issue before it's officially fixed?

**Comment by trymbill** [comment]
Actually, never mind, found a fix. Node.js has `NODE_TLS_REJECT_UNAUTHORIZED` that can be set to `0`, which seems to silence this error. So for `cypress-io/github-action@v2`, you can add `NODE_TLS_REJECT_UNAUTHORIZED: 0` in `env` like so:

```yml
- name: 'Run tests'
  uses: cypress-io/github-action@v2
  with:
    browser: chrome
    start: yarn start
    wait-on: 'https://www.domain.com'
  env:
    NODE_TLS_REJECT_UNAUTHORIZED: 0
```

That at least worked for me. Might be worth adding to the `README`.
