### ISSUE TITLE
Running custom command also runs default command in parallel

### ISSUE THREAD

**Issue by Hoopra** [cypress-io/github-action#161]
![image](https://user-images.githubusercontent.com/25965072/84876745-da6ef600-b087-11ea-981c-cfbdf702b879.png)

```
      - uses: cypress-io/github-action@v1
        with:
          command: npm run test:ci
```

Using the above code causes the behaviour shown in the image. Even though the runner uses my command for a run it also runs the default command (`npx cypress run --config-file cypress.json`) in parallel. It is possible to get around this by adding the following:

```
      - uses: cypress-io/github-action@v1
        with:
          command: npm run test:ci
          parallel: false
          record: false
          spec: none/spec.js
```

However this seems like unexpected behaviour.
