### ISSUE TITLE
Support for Yarn Berry

### ISSUE THREAD

**Issue by faustbrian** [cypress-io/github-action#170]
At the moment yarn berry is not supported which will result in an error on installation.

```
➤ YN0050: The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead
```

A solution could be the below code.

```ts
      return exec.exec(quote(yarnPath), ['--version']).then(version => {
        return exec.exec(
          quote(yarnPath),
          version.startsWith('2.') ? ['--immutable', '--immutable-cache'] : ['--frozen-lockfile'],
          cypressCommandOptions
        )
      })
```

**Comment by nnennajohn** [comment]
Hi. Is there any update on this? Thank you.

**Comment by jennifer-shehane** [comment]
No updates. We're open to pull requests.

**Comment by nicholaschiang** [comment]
@jennifer-shehane there you go!

**Comment by nicholaschiang** [comment]
@nnennajohn you should be able to just temporarily use [my fork of this GitHub action](https://github.com/tutorbookapp/github-action) like so:
```yaml
      # This action installs and caches dependencies (including Cypress), runs
      # the build, and then runs our integration tests.
      # @see {@link https://github.com/cypress-io/github-action}
      # @see {@link https://github.com/cypress-io/github-action/pulls/195}
      - uses: tutorbookapp/github-action@master
        with:
          record: true
          parallel: true
          build: yarn build
          command: yarn test
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Using your own options OFC, but you get the general idea!
