### ISSUE TITLE
`env: CYPRESS_BASE_URL` is not respected

### ISSUE THREAD

**Issue by thisismydesign** [cypress-io/github-action#174]
Action:
```
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on: 'https://myapp.herokuapp.com/'
          wait-on-timeout: 120
          working-directory: packages/web
          env: CYPRESS_BASE_URL=https://componently-marketplace-mvp.herokuapp.com/
```

`cypress.json`
```
{
  "baseUrl": "http://localhost:3000"
}
```

Output:
```
waiting on "myapp.herokuapp.com/" with timeout of 120 seconds
Cypress could not verify that this server is running:

  > http://localhost:3000

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.
```

Meanwhile running `CYPRESS_BASE_URL=https://componently-marketplace-mvp.herokuapp.com/ cypress run` works.
