### ISSUE TITLE
How do I get this to run within a monorepo?

### ISSUE THREAD

**Issue by CodyBontecou** [cypress-io/github-action#179]
I'm trying to run this action within a monorepo [here](https://github.com/CodyBontecou/OurMap), and I can't seem to get the package to locate my package.json that is within my frontend directory.

Here is what the `.yml` file looks like:

```
name: Parallel Cypress Tests

on: [push]

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machines: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          parallel: true
          group: 'Cypress Actions'
```

The action is looking for the package.json file within the root directory rather than within the frontend directory (that I believe I setup correctly), resulting in an error and broken action.
