### ISSUE TITLE
Firefox causes uv_os_passwd SystemError

### ISSUE THREAD

**Issue by caseybaggz** [cypress-io/github-action#189]
Hello! I'm currently running multiple cypress/browser tests in my GH workflow using Chrome, FF, and Edge. All are using the same cypress settings per OS. Chrome and Edge are working fine, but the FF job always returns what appears to be a [docker error](https://stackoverflow.com/questions/61961485/a-system-error-occurred-uv-os-get-passwd-returned-enoent-no-such-file-or-direc?noredirect=1#comment109603079_61961485).

Workflow Job:
```
cypress_firefox:
    name: E2E Tests / Firefox
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.18.0-chrome83-ff77
      options: --user 1001 --shm-size=2g
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: cypress-io/github-action@v2
        with:
          browser: firefox
          build: yarn build:staging
          command: yarn cypress:run-staging
          config-file: frontend/cypress.json
          start: yarn serve:staging
          wait-on: 'http://localhost:3000'
          working-directory: frontend
```

Error:
```
ERROR:
Parse error: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory) in "App/Table/Table.tsx"
error Command failed with exit code 100.
```

Just wondering if there is something on my side re the config that might be contributing to this?
