### ISSUE TITLE
Can't run 'start' in background

### ISSUE THREAD

**Issue by thiagobrez** [cypress-io/github-action#19]
Hi!

I'm using this action as follows:

```yml
name: Tests
on: push
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://cypress/browsers:chrome69

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install && cd e2e && yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: yarn start
          wait-on: http-get://localhost:4200
```
And this is my folder structure (Angular project):

![image](https://user-images.githubusercontent.com/26878038/68861765-ec8c4e80-06ca-11ea-8642-5bc9a50b4eb1.png)

Cypress is separated into it's own package to avoid conflicts with TypeScript.

The issue is that `yarn start` never passes away to cypress run, running infinitely. Also, I have a doubt that this action would work with my different cypress setup?

In my root `package.json`:
"cypress:run": "cd e2e && yarn cypress:run",

In `e2e/package.json`:
"cypress:run": "cypress run --browser chrome"

Thanks in advance!

**Comment by thiagobrez** [comment]
Solved by adapting my scripts:

> NOTE '&' at the end of a command in shell means that it can be executed in background, where '&&' can't

tests.yml
```yml
name: Tests
on: push
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://cypress/browsers:chrome69

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install && cd e2e && yarn install

      - name: Start app and run tests
        run: yarn e2e:ci
```

package.json
```json
scripts: {
  "e2e:ci": "yarn start & wait-on http-get://localhost:4200/ && npm run e2e",
}
```
