### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by jarretmoses** [cypress-io/github-action#190]
Hello I am currently using this action and parallelizing my tests. While everything is working fine I do notice this warning popping up all over the place and according to the error stack it looks to be related to this action. I am not exactly sure what is going on it just creates a lot of noise in the console output.
<img width="1278" alt="Screen Shot 2020-08-14 at 3 35 24 PM" src="https://user-images.githubusercontent.com/4745679/90287412-d4a64e80-de45-11ea-9223-5b2469b767d9.png">

My setup is as follows
```
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          record: true
          parallel: true
          run: npm run cy:run
        env:
          CYPRESS_MODE: 'ci'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
```
