### ISSUE TITLE
pull_request as trigger shows no Cypress run information on my Pull Requests

### ISSUE THREAD

**Issue by covertbert** [cypress-io/github-action#191]
Trigger is `pull_request`

Passing the following environment variables to the action:

```
        env:
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_BRANCH: ${{ github.head_ref }}
          COMMIT_INFO_SHA: ${{ github.sha }}
          CYPRESS_BASE_URL: example.com
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I expected that I was giving Cypress enough information so that it could display comments and Cypress run information on my PR but it doesn't. However, runs do show up in the dashboard with the correct meta information.

Changing the trigger to `push` works but we don't want that as part of our workflow.
