### ISSUE TITLE
Option to run a command AFTER suite is finished?

### ISSUE THREAD

**Issue by stoplion** [cypress-io/github-action#192]
Hello, 

Is there any option to run a command **_after_** the Cypress test suite finishes? In cases where you need to stop / restart the server? 

For example..
```
    with:
          start: npx nps server.test
          wait-on: http://localhost:5000
          config-file: spec/cypress.ci.indexing.json
          headless: true
```

`npx nps server.test` 
// starts Rails Server with ENABLE_INDEXING
`config-file: spec/cypress.ci.indexing.json` 
// runs all tests for search

```
    with:
          start: npx nps server.test.no_indexing
          wait-on: http://localhost:5000
          config-file: spec/cypress.ci.json
          headless: true
```

`npx nps server.test.no_indexing` 
// starts Rails Server with ENABLE_INDEXING to **FALSE** 
`config-file: spec/cypress.ci.json` 
// runs all tests for that **don't need** indexing, because it's too slow 

In the following example, the Rails server is already running when it hits the second test, and it fails.

**Comment by bahmutov** [comment]
Not sure I understand the question. This action starts the server process in the background, but does not terminate it when Cypress tests finish, instead it leaves it to GitHub Actions engine to clean them up at the end. Do you want to stop the background process at the end of the run so that the second run can start?

**Comment by bahmutov** [comment]
Closing as unclear.

**Comment by mellis481** [comment]
> @bahmutov ...instead it leaves it to GitHub Actions engine to clean them up at the end.

I believe I'm having the same issue that the author of this post is getting at.  I currently have the following steps in my workflow:

```
- name: Run Cypress mocked-api tests
  uses: cypress-io/github-action@v2
  with:
    wait-on: "https://localhost:9001"
    start: npm run start:test
    command: npm run cypress:run:test
    install: false
  env:
    NODE_TLS_REJECT_UNAUTHORIZED: 0
- name: Run Cypress end-to-end tests
  uses: cypress-io/github-action@v2
  with:
    wait-on: "https://localhost:9001"
    command: npm run cypress:run:e2e:test
    install: false
  env:
    NODE_TLS_REJECT_UNAUTHORIZED: 0
```

In my second step, webpack-devserver is still running on port 9001 from the first `cypress-io/github-action@v2` step.  When you say "GitHub Actions engine to clean them up at the end" I'm guessing you mean at the end of a _job_, not after any _step_ in which `cypress-io/github-action@v2` is used.
