### ISSUE TITLE
Comment PR with artifacts: screenshot and video on failure

### ISSUE THREAD

**Issue by freddydumont** [cypress-io/github-action#193]
I'm not super familiar with GitHub actions, but figuring it out as needed.

I'm looking for a way to upload artifacts directly as github comments when the cypress run fails.

Is there a way to achieve that? Surely posting a comment with the screenshot of the failed run is feasible?

**Comment by yoonwaiyan** [comment]
This is the script I use to upload artifacts once cypress run fails:

```
- name: Upload Cypress Screenshots and Videos
  uses: actions/upload-artifact@v2
  with:
    name: cypress-artifacts
    path: |-
      spec/cypress/screenshots
      spec/cypress/videos
  if: ${{ failure() }}
```

but I'm not sure about showing the screenshot directly in the comments. I'm afraid there's a limitation on uploading images to Github using API though.
