### ISSUE TITLE
Action fails with "Your system is missing the dependency: Xvfb"

### ISSUE THREAD

**Issue by joonashak** [cypress-io/github-action#197]
While trying to run this action, I am getting the error `Your system is missing the dependency: Xvfb`. I ran into this couple of times earlier and it seemed to appear intermittently for others as well, so I did not think much of it. However, now I have started to get it on every run with a workflow that should be working fine.

Here is the .yml in question:

```
name: Test trunk
on:
  push:
    branches: trunk
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: node:14.8

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Wait until postgres has started.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      cms:
        image: joonashak/reclab-cms:0.0.5
        env:
          NODE_ENV: development
          PORT: 3001
          DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
          JWT_SECRET: asd
        # Wait until cms has started.
        options: >-
          --health-cmd "curl -sS 127.0.0.1:3001 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run serve
          wait-on: 'http://localhost:9000'
        env:
          NODE_ENV: test
          CMS_URL: http://cms:3001
```

And here is the error message in CI:

![Screenshot 2020-09-11 at 17 54 18](https://user-images.githubusercontent.com/18666321/92940506-e1738d80-f457-11ea-9fd2-1369ef970b04.png)

What do you make of this? Is it a problem with Cypress or the action or just my configuration?

Some remedies I have unsuccessfully tried:

- Running Cypress with `run-xvfb`.
- Running with `ubuntu-16.04` instead of `ubuntu-latest`.
- ???

Thank you for your help!
