### ISSUE TITLE
Inconsistent Running and Install from Windows

### ISSUE THREAD

**Issue by chryton** [cypress-io/github-action#199]
I have been having intermittent issues with the Cypress task runner using standard Windows box from GitHub, which is causing massive spikes in cost to be able to run Cypress for cross-browser testing.

Here is my action setup:

```yml
  test-windows-edge:
#     needs: test-ff
    needs: test-chrome
    runs-on: windows-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 2 copies of the current job in parallel
        containers: [1, 2]
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CY_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          record: true
          parallel: true
          env: baseUrl=https://test.com/,projectId=${{ secrets.CY_PROJECT_ID }}
          browser: edge
          group: 'Edge'
```

Recent logs of the group run from the action above:

## Container 1
<img width="1048" alt="Screen Shot 2020-09-16 at 12 13 29 PM" src="https://user-images.githubusercontent.com/2627689/93364616-c2d61380-f816-11ea-806e-452780d5c807.png">

## Container 2
<img width="1046" alt="Screen Shot 2020-09-16 at 12 28 47 PM" src="https://user-images.githubusercontent.com/2627689/93365831-480df800-f818-11ea-8cf1-e5410ff5979f.png">

As you can see the initial container completes in a reasonable amount of time but then stays up for 6 hours for no apparent reason. My project's Run Completion Delay is set to 480s (due to how long it sometimes takes the GH Actions to build Windows containers) so it should not drag on past that, 

Regardless, I also have noticed this consistent error every time the Cypress container gets build:
```
Wed, 16 Sep 2020 07:08:08 GMT
C:\windows\system32\tar.exe -cz --force-local -f D:/a/_temp/382e25df-dd63-49d1-922c-e10c73d3215a/cache.tgz -C C:/Users/runneradmin/.cache/yarn .
Wed, 16 Sep 2020 07:08:08 GMT
tar.exe: Option --force-local is not supported
Wed, 16 Sep 2020 07:08:08 GMT
Usage:
Wed, 16 Sep 2020 07:08:08 GMT
  List:    tar.exe -tf <archive-filename>
Wed, 16 Sep 2020 07:08:08 GMT
  Extract: tar.exe -xf <archive-filename>
Wed, 16 Sep 2020 07:08:08 GMT
  Create:  tar.exe -cf <archive-filename> [filenames...]
Wed, 16 Sep 2020 07:08:08 GMT
  Help:    tar.exe --help
Wed, 16 Sep 2020 07:08:08 GMT
##[warning]The process 'C:\windows\system32\tar.exe' failed with exit code 1
Wed, 16 Sep 2020 07:08:08 GMT
saving cache path C:\Users\runneradmin\.cache\Cypress
Wed, 16 Sep 2020 07:08:08 GMT
primary key cypress-win32-x64-24a0825fc846cbc9ec6eb1d324bc0174ada5cbc2c874a6ed8e374116f5f0f078329771177e6d5c2973073deef86b7dbbc7f65cd55cb2021ca72c099dae6ffe90
Wed, 16 Sep 2020 07:08:08 GMT
C:\windows\system32\tar.exe -cz --force-local -f D:/a/_temp/84cc0fce-2097-4012-b163-b7fa121e2206/cache.tgz -C C:/Users/runneradmin/.cache/Cypress .
Wed, 16 Sep 2020 07:08:08 GMT
tar.exe: Option --force-local is not supported
Wed, 16 Sep 2020 07:08:08 GMT
Usage:
Wed, 16 Sep 2020 07:08:08 GMT
  List:    tar.exe -tf <archive-filename>
Wed, 16 Sep 2020 07:08:08 GMT
  Extract: tar.exe -xf <archive-filename>
Wed, 16 Sep 2020 07:08:08 GMT
  Create:  tar.exe -cf <archive-filename> [filenames...]
Wed, 16 Sep 2020 07:08:08 GMT
  Help:    tar.exe --help
Wed, 16 Sep 2020 07:08:10 GMT
##[warning]The process 'C:\windows\system32\tar.exe' failed with exit code 1
```
