### ISSUE TITLE
Run Action in a Docker Container that is not the same container as the runner

### ISSUE THREAD

**Issue by shicholas** [cypress-io/github-action#222]
It would be awesome to be able to configure this action like this:

```
      - name: Run Cypress tests for the Interface
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./packages/interface
          container: cypress/browsers:node12.13.0-chrome78-ff70
```

Specifying the container in the job itself is different than the current [Docker Image](https://github.com/cypress-io/github-action#docker-image) documentation because there would be two different environments for the Cypress step and the rest of the steps in the job workflow. The biggest benefit for us is that we wouldn't need a `yarn install` step because everything is already pre-installed in the Docker container, and we could technically start a web server with non-node processes, like using Hugo.
