### ISSUE TITLE
Cypress build never completes possibly due to wait-on

### ISSUE THREAD

**Issue by TatsumiSuenaga** [cypress-io/github-action#225]
Hey all, as of 3 days ago, our Cypress tests have been not passing in our CI build. The build would run for 6hrs if left untouched, and would be auto-cancelled by GitHub. We haven't changed anything since the first time we've set it up, but noticed that Github is deprecating `set-env` so we thought that was the issue.

We then bumped up our version from `v1` to `v2.3.1`, but that did not fix our issue. Next we tried updating the `.yml` (added a custom run command, shortened `wait` time, removed `wait-on`), but the only change that led to a different result was when we removed the `wait-on`.

We're not sure what happened in the past couple of days, but may have a hunch that we are not properly setting up `wait-on`. Would appreciate it if some one can help us out with our issue.

Our `.yml`:
```
name: Continuous Integration

on:
  [ push ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.16.0
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
      - name: Install NPM dependencies
        run: npm install
      
      
  lint_and_format:
    needs: [ install ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Load node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Lint and format the code
        run: npm run format

  test_enzyme:
    needs: [ install ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Load node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Run unit tests
        run: npm test
      - name: Report to Code Climate
        run: |
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t lcov coverage/lcov.info
          ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  test_cypress:
    needs: [ install ]

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Load node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2.3.1
        with:
          start: npm start
          wait-on: 'http://localhost:8000'
          env: APP_URL=http://localhost:8000
        env:
          GATSBY_FACEBOOK_PIXEL_ID: redacted
          GATSBY_UNBOUNCE_ID: redacted
          GATSBY_PRISMIC_REPOSITORY_NAME: redacted
          GTM_AUTH: redacted
          GTM_ID: redacted
          GTM_PREVIEW: redacted
          INTERCOM_APP_ID: redacted
          MAILCHIMP_API_ENDPOINT: http://test-url.com
          PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}
          STAGING_PASSWORD: redacted
          STAGING_USERNAME: redacted

```

Error message without `wait-on`:
```
  Navigation
    Global navigation
      1) "before each" hook for "Visit home page from nav"


  0 passing (348ms)
  1 failing

  1) Navigation
       Global navigation
         "before each" hook for "Visit home page from nav":
     CypressError: `cy.visit()` must be called with a `url` or an `options` object containing a `url` as its 1st argument
``` 

Code snippet of where it errors:
```
describe('Navigation', () => {
  beforeEach(() => {
    cy.visit(Cypress.env('APP_URL'));
  });

 ...

});
```
