### ISSUE TITLE
Specify node version

### ISSUE THREAD

**Issue by prescottprue** [cypress-io/github-action#23]
Even when using the node setup action before this action, node 12.13 is still being used:

```yml
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Cypress Run
      uses: cypress-io/github-action@v1
      with:
        record: true
      env:
        # pass the Dashboard record key as an environment variable
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
```

The error that includes node version:

![image](https://user-images.githubusercontent.com/2992224/68980858-bb497680-07cf-11ea-96d2-5d4153b12e55.png)

Is there a way to set node version that I am missing? If not, it would awesome if this was an input
