### ISSUE TITLE
Accept list for envvars setting

### ISSUE THREAD

**Issue by vimkin** [cypress-io/github-action#241]
As it's stated in the [docs](https://github.com/cypress-io/github-action#env) the action currently expects an env parameter(s) to be set only as a string. If the list is passed instead, the action throws following err: `line 55: cannot unmarshal !!map into string`. I think it would be handy if both formats (list and string) are supported for the property.

### The following code is expected to work without errors
```yaml
- name: Cypress tests
  uses: cypress-io/github-action@v2
  with:
    browser: chrome
    headless: true
    wait-on: ${{ steps.generated_URL }}
    wait-on-timeout: 300
    env:
      BASE_URL: ${{ steps.generated_URL }}
      ENV_1: "foo"
      ENV_2: ${{ secrets.VERY_SECRET }}
```

**Comment by bahmutov** [comment]
It would be nice, but does the github action allow such env list as arguments? I don't think, or at least I have never seen this in their docs.

**Comment by vimkin** [comment]
I'm not sure if the actions toolkit provides you such capabilities, because I've never written github-action yet, but from the consumer side they do have a consistent approach concerning [envvars](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-7). 

Possibly this could be addressed differently from design perspective. In the current state there are 2 spots to specify envvars: first natively for the runner (can get it from `process.env`, the way you do with e.g. GITHUB_TOKEN) and secondly for cypress run itself (the value is pulled out in [here](https://github.com/cypress-io/github-action/blob/master/index.js#L502)). Why wouldn't you feed all the global envvars from `process.env` to the cypress run?

Then instead of:
```yaml
- name: Cypress run with env
  uses: cypress-io/github-action@v2
  with:
    env: host=api.dev.local,port=4222
  env:
    # pass the Dashboard record key as an environment variable
    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    # pass GitHub token to allow accurately detecting a build vs a re-run build
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

We could specify env just once:
```yaml
- name: Cypress run with env
  uses: cypress-io/github-action@v2
  env:
    host: api.dev.local
    port: 4222
    # pass the Dashboard record key as an environment variable
    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    # pass GitHub token to allow accurately detecting a build vs a re-run build
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

...and you would also save a couple of lines on parsing.
