### ISSUE TITLE
The Github Action now fails with Cypress 5.6 and 6.0

### ISSUE THREAD

**Issue by fbiville** [cypress-io/github-action#255]
I have multiple repositories depending on Cypress for a shared (well, duplicated) set of end-to-end tests and every Dependabot bump from 5.6 to 6.0 results in a failing build (see an example [here](https://github.com/neo4j-examples/movies-javascript-bolt/pull/48/checks?check_run_id=1478452728)).

What's worse is that 5.6 builds do not seem to work anymore either. I just re-ran this successful [build from 11 days ago](https://github.com/neo4j-examples/movies-javascript-bolt/runs/1478452724?check_suite_focus=true) today and it failed.

The basic test works but the data retrieved by async calls must be failing, causing the other tests to fail.

Apart from that, I cannot tell much more as logs are scarce.

I also cannot reproduce the problem locally (I'm on Mac OS though while my CI runs on Ubuntu).

Did a regression occur in recent commits of this repo?

For reference, here is an example of the full setup:
```yaml
name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run clean
      - run: npm run build
  e2e:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x ]
        neo4j-version: [ "4.0", "4.0-enterprise", "4.1", "4.1-enterprise" ]
    services:
      neo4j:
        image: neo4j:${{ matrix.neo4j-version }}
        ports: [ "7687:7687" ]
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4J_AUTH: "neo4j/abcde"
        options: >-
          --name neo4j-e2e
          --health-cmd "cypher-shell -u neo4j -p abcde 'RETURN 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-start-period 10s
          --health-retries 5
          --volume /tmp:/movies
    steps:
      - name: Download dataset
        run: curl --output /tmp/movies.cypher https://raw.githubusercontent.com/neo4j-graph-examples/movies/master/scripts/import.cypher
      - name: Import dataset
        run: docker exec --interactive neo4j-e2e cypher-shell -u neo4j -p abcde --file /movies/movies.cypher
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        env:
          NEO4J_URI: bolt://localhost
          NEO4J_DATABASE: "neo4j"
          NEO4J_USER: neo4j
          NEO4J_PASSWORD: abcde
        with:
          start: npm start
          browser: chrome
          headless: true
          spec: cypress/integration/movies.spec.js
```
