### ISSUE TITLE
start command failure does not exit if wait_on is provided

### ISSUE THREAD

**Issue by prescottprue** [cypress-io/github-action#27]
My `start` command is failing due to unrelated issues, but since I provide a `wait_on` the github action waits indefinitely. After seeing it run for over an hour, I manually quit the action, then I was able to see the logs explaining why the `start`command failed.

Not sure how possible it is, but if we could exit the action if the `start` command fails/exits regardless of whether the `wait_on` is set. It could be really helpful for folks to debug issues with starting up the dev server like what I am experiencing.

**Comment by bahmutov** [comment]
Yeah, it would be nice to pass `--timeout` argument to wait-on https://github.com/jeffbski/wait-on

I am thinking we could do the following to give the most power: allow you to specify arbitrary command to run in `wait-on`. For example if we detect that you use `npx` or `yarn` inside `wait-on` string, then run it as a general command

```
# runs "npx wait-on http://localhost:4200
wait-on: http://localhost:4200
# runs wai-ton with timeout of 30 seconds and using HTTP GET method
wait-on: npx wait-on http-get://localhost:4200 --timeout 30
```

**Comment by rbuetzer** [comment]
As a workaround, try this:

```yml
name: Cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: "npm start & npx wait-on: http://localhost:4200 --timeout 30"
```
