### ISSUE TITLE
Cannot run Cypress tests with GitHub Actions with paths-ignore keyword

### ISSUE THREAD

**Issue by haase1020** [cypress-io/github-action#288]
When I try to run a GitHub Action with paths-ignore, I get a message next to each test in GitHub (I am running tests in parallel): "Expected — Waiting for status to be reported". When I make changes and push to a path that is not in the path to be ignored, the tests run, but otherwise they stay in this "wating for status to be reported". I would like to be able to ignore certain paths on pushes and would love recommendations on how to create this behavior. The following is the code I changed in my GitHub Action:
```
name: e2e-tests
on:
  push:
    paths-ignore:
      - "stats-api/**"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2, 3, 4, 5]
```

**Comment by bahmutov** [comment]
The paths-ignore - is this a GitHub workflow parameter to NOT run the action workflow if only those field changed? I don't see how it would influence and change the cypress behavior once it runs. Can you post link to the action output? Maybe enable debugging too to show more information?

**Comment by haase1020** [comment]
Is there an easy way to enable debugging in the yml file without setting an environment variable? It looks like the documentation says to set the secret "ACTIONS_RUNNER_DEBUG" to true. Not sure what "setting the secret" means...

**Comment by bahmutov** [comment]
Go to repo’s settings there is a section for secrets

**Comment by haase1020** [comment]
I have found the issue - the GitHub status for our repo is set to require certain checks before merging, but when I set paths conditionally (in my case I am using `paths-ignore`) GitHub still is expecting those checks to pass. Since they do not run, the checks do not pass. Is there a way to change this behavior? Here is the error in GitHub: 
![image](https://user-images.githubusercontent.com/58481829/106573887-35b30300-6508-11eb-99b0-b81c9bc07161.png)

**Comment by haase1020** [comment]
I tried using a GitHub action for this issue, but it is still not working: This is the first part of my cypress.yml file with the github action from https://github.com/marketplace/actions/skip-duplicate-actions:
```
name: e2e-tests
on: [push]
jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      -id: skip_check
      uses: fkirc/skip-duplicate-actions@master
      with:
        paths_ignore: '["**/README.md", "**/docs/**", stats-api/**, "**.yml"]'
  cypress-run:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
```
