### ISSUE TITLE
Passing multiple specs

### ISSUE THREAD

**Issue by DamienCassou** [cypress-io/github-action#289]
`cypress run` allows [passing multiple specs as arguments](https://docs.cypress.io/guides/guides/command-line.html#cypress-run) by separating them with a comma. That also works with GitHub Actions:

```yaml
- name: Run Cypress
  uses: cypress-io/github-action@v2
  with:
    working-directory: ${{ env.client-directory }}
    group: 'Cypress UI from GitHub Actions'
    spec: 'cypress/integration/**/*_spec.ui.js,cypress/component/**/*_spec.js'
```

However, this is arguably hard to read. I suggest leveraging YAML syntax to specify multiple specs:

```yaml
- name: Run Cypress
  uses: cypress-io/github-action@v2
  with:
    working-directory: ${{ env.client-directory }}
    group: 'Cypress UI from GitHub Actions'
    spec: |
      cypress/integration/**/*_spec.ui.js
      cypress/component/**/*_spec.js
```

I would like the above to work but it doesn't. Cypress says no spec file are found.
