### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#292]
Use checkout v2 and ubuntu-20.04 in the examples

```
runs-on: ubuntu-20.04
steps:
  - name: Checkout
    uses: actions/checkout@v2
```
