### ISSUE TITLE
Cypress not connecting to my backend

### ISSUE THREAD

**Issue by nixton9** [cypress-io/github-action#296]
Hey!
I'm pretty new to Github Actions and I'm trying to set up a simple workflow just to run some Cypress tests on my app. The problem is that my backend is separated from my frontend, and when Cypress is running my tests, it's not being able to connect to this backend. I've inserted a curl request to my backend on the workflow, and the response is correct so I believe the problem is not with my backend. This is what I'm doing:

```
jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v2
        with:
          repository: nixton9/*****
          token: ${{ secrets.REPO_TOKEN }}
          path: backend

      - name: Set up Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend
        working-directory: ./backend
        run: node server.js &
        env:
          APP_SECRET: ${{ secrets.BE_APP_SECRET }}
          NODE_ENV: ${{ secrets.BE_NODE_ENV }}
          DATABASE_URL: ${{ secrets.BE_DATABASE_URL }}
          
      - name: Check if we can access BE
        run: curl http://localhost:4000

      - name: Checkout frontend repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:3000, http://localhost:4000'
          config: baseUrl=http://localhost:3000
        env:
          REACT_APP_NODE_ENV: test

```

All the tests are failing since my frontend can't connect to my backend, but I'm not seeing any errors related to this. Any idea what might wrong?
Thanks!
