### ISSUE TITLE
Conditional recording to dashboard?

### ISSUE THREAD

**Issue by karfau** [cypress-io/github-action#306]
I'm trying to connect to cypress dashboard for the first time.

We are running some test per PR and only run all test suites on tag push.
I would love to also only record on tag push, so I tried the following:

```yml
on:
  pull_request:
    branches: ['master']
  # Triggers the workflow only on tags creation (after git push origin --tags)
  push:
    tags: ['*']
jobs:
  e2e-login:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Run login e2e tests against CI stage
        uses: cypress-io/github-action@v2
        with:
          config: video=false
          spec: "cypress/integration/login/**/*"
          # only record to cypress dashboard when run on master
          # https://github.com/cypress-io/github-action#record-test-results-on-cypress-dashboard
          record: ${{ github.event_name == 'push' }}

          # also didn't work:
          # record: ${{ github.event_name == 'push' || false }}

          # https://github.com/cypress-io/github-action#tag-recordings
          # the ref should indicate the tag pushed by jenkins
          tag: ${{ github.ref }}
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # [...]
  scenario2:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    # [...]
```
But this approach fails with the following message:
```
You passed the --ci-build-id, --group, --tag, or --parallel flag without also passing the --record flag.
```

Would it be possible to either only pass those flags when `--record` is passed, or pass `--record false` together with those other flags or document how to use the `--record` flag in a conditional way?

Thank you
