### ISSUE TITLE
env vars not recognized when using Checkout

### ISSUE THREAD

**Issue by schw4rzlicht** [cypress-io/github-action#312]
Hey there,

we use follwing workflow:
```yaml
name: Scheduled e2e tests
on: [push] # will be schedule
jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        browser: [electron, firefox]
        branch: [dev, staging]
    env:
      VUE_MODE: e2e-${{ matrix.branch }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - run: echo $VUE_MODE
      - run: echo $CI
      - uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          headless: true
          start: npm run serve -- --mode $VUE_MODE
          wait-on: "http://localhost:8080"
```

The problem with this workflow is that
1. we need to have access to `CI` since our Vue-config uses it to determine whether to output webpack progress and
2. we need to use `VUE_MODE` to use different `.env`-files depending on the environment we want to test against.

When using checkout as in the example above, either of the one is recognized. Webpack config is printed to the logs and no `.env` is loaded. When commenting out
```yaml
        with:
          ref: ${{ matrix.branch }}
```
everything works as expected, without checking out the right branch of course.

What I've tried so far:
* defining `env` on all possible places
* using the `env` input of the cypress-action
* using Ubuntu 18.04 explicitly

I'm not sure if this a Cypress-issue at all but it might be since both `echo` commands between the actions return the expected result.

Any help appreciated :)
