### ISSUE TITLE
wait-on-timeout Value Doesn't Appear to Be Used

### ISSUE THREAD

**Issue by chriswsh** [cypress-io/github-action#313]
With these settings:

```
uses: cypress-io/github-action@v2
with:
  start: npm start
  wait-on: "http://localhost:3000"
  wait-on-timeout: 300
```

I get these logs in Github actions:

```
start server "npm start command "npm start"
current working directory "/home/runner/work/badger-frontend/badger-frontend"
waiting on "http://localhost:3000" with timeout of 60 seconds
```

I'd expect that the wait time for `http://localhost:3000` would be the `wait-on-timeout` value.

Possibly related to the behavior in https://github.com/cypress-io/github-action/issues/286
