### ISSUE TITLE
warning Error from chokidar - Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by abohannon** [cypress-io/github-action#317]
After running the dev server and before the Cypress run I get thousands of logs about exceeding file watchers.
![Screen Shot 2021-03-11 at 5 25 35 PM](https://user-images.githubusercontent.com/889536/110877824-eabaa700-828e-11eb-86d7-5c23d7e72cc6.png)

Curious if this is something that can be rectified via the plugin interface somehow or if it's an issue with Github Actions? The test eventually runs fine, but in order to see the results you have to scroll through thousands of logs to find them.

Workflow config
```
name: Cypress end-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run clean && npm start
          wait-on: http://localhost:4000
          wait-on-timeout: 6000

```
