### ISSUE TITLE
Error with tar cache.tgz in self-hosted runner

### ISSUE THREAD

**Issue by carlosds** [cypress-io/github-action#318]
Hi,

I am getting this error launching Cypress on my self-hosted runners:

> 25l[07:57:52]  Verifying Cypress can run /home/runner/.cache/Cypress/6.2.0/Cypress [started]
> [07:57:54]  Verifying Cypress can run /home/runner/.cache/Cypress/6.2.0/Cypress [completed]
> 25h25h::debug::saving NPM modules
> /bin/tar --posix -z -cf cache.tgz -P -C /work/project/project --files-from manifest.txt
> Error: The operation was canceled.

These are my steps:

```
- name: Install npm dependencies
  working-directory: ${{ github.workspace }}/code/config_test/e2e/definitions/cypress
  run: |
          export CYPRESS_INSTALL_BINARY=https://myorg.com/artifactory/node-thirdparty-local/cypress/cypress-${{ env.CYPRESS_VERSION }}.zip
          rm -rf /home/runner/.cache/Cypress
          npm install

- name: Run e2e tests with Cypress        
  uses: cypress-io/github-action@v2
  with:
          working-directory: ${{ github.workspace }}/code/config_test/e2e/definitions/cypress
          browser: chrome
          #build: npm run build
          #start: npm run start
  env:
          CYPRESS_host: localhost
          CYPRESS_port: 8080
```

It seems that "manifest.txt" does not exists, any idea?

Thank you!
