### ISSUE TITLE
Provide option to upload videos/screenshots as Artifacts

### ISSUE THREAD

**Issue by JasonEtco** [cypress-io/github-action#33]
Hello! This is rad, I'm excited to try it out! One thing I've played with in my own usage of Cypress + Actions is uploading the generated videos/screenshots as Artifacts, using [`actions/upload-artifact`](https://github.com/actions/upload-artifact).

```yml
# Run the e2e tests (cypress run)
- run: npm run test:e2e
- uses: actions/upload-artifact@v1
  with:
    name: cypress-videos
    path: cypress/videos
```

This works great as-is, but when a step fails it doesn't move on to the next step, which _would_ be uploading those videos. Workflows can leverage [`continue-on-error`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error), but it gets weird pretty quickly (you need to capture the exit code to ensure a failed test run causes a failed Actions run).

This action looks like it would have more control over when/how the step exits, so it could make for a great addition!

**Comment by bahmutov** [comment]
yeah, I am not sure how to implement this - because screenshots could be generated on failure or normal run, and same for video. If anyone has a good idea how to do this (aside from using Cypress Dashboard with `record: true` parameter), I would be very interested

**Comment by JasonEtco** [comment]
I've learned some new tricks since opening this - apparently, you can use `if: always()` to instruct a step to always run, regardless of whether or not the steps before it pass:

```yml
- uses: cypress-io/github-action
- uses: actions/upload-artifact@v1
  if: always()
  with:
    name: cypress-videos
    path: cypress/videos
```

So, I think that because `actions/upload-artifact` uses some special Actions magic, it might be better left to that two-step solution. However, I think it'd be a great addition to the docs for this repo; I've already been helped by being able to download the video recordings of a build in CI.
