### ISSUE TITLE
Sometimes the test fails because it cannot find the generated video.

### ISSUE THREAD

**Issue by redshoga** [cypress-io/github-action#337]
SSIA

The project uses Cypress Dashboard and cypress-io/github-action@v2.
All tests are passing, but the test fails about 20% of the time because the generated operation video is not found.
The following is a detailed description of the operating environment.

Error Log

```
// ...

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     18 seconds                                                                       │
  │ Estimated:    17 seconds                                                                       │
  │ Spec Ran:     auth.spec.ts                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /home/runner/work/<repo-name>/<repo-name>/e2e/cyp    (6 seconds)
                          ress/videos/auth.spec.ts.mp4                                              


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  editCompany.spec.ts                                                             (2 of 2)


  企業情報
  -  Finished processing: /home/runner/work/<repo-name>/<repo-name>/e2e/cyp    (9 seconds)
                          ress/videos/auth.spec.ts.mp4                                              

[OperationalError: ENOENT: no such file or directory, stat '/home/runner/work/<repo-name>/<repo-name>/e2e/cypress/videos/auth.spec.ts-compressed.mp4'

] {
  cause: [Error: ENOENT: no such file or directory, stat '/home/runner/work/<repo-name>/<repo-name>/e2e/cypress/videos/auth.spec.ts-compressed.mp4'
  
  ] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/home/runner/work/<repo-name>/<repo-name>/e2e/cypress/videos/auth.spec.ts-compressed.mp4'
  },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/runner/work/<repo-name>/<repo-name>/e2e/cypress/videos/auth.spec.ts-compressed.mp4'
}
Error: ENOENT: no such file or directory, stat '/home/runner/work/<repo-name>/<repo-name>/e2e/cypress/videos/auth.spec.ts-compressed.mp4'

```

`e2e/package.json`

```json
{
  "name": "e2e",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "cypress:staging:open": "cypress open -C cypress.staging.json",
    "cypress:staging:run": "cypress run -C cypress.staging.json"
  },
  "dependencies": {
    "cypress": "^6.6.0",
    "typescript": "^4.2.3"
  }
}
```

`.github/workflows/cypress.yml`

```
name: Cypress tests

on:
  schedule:
    - cron: '0 0 * * 1-5'

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          working-directory: e2e
          start: yarn cypress:staging:run
          config-file: cypress.staging.json
          cache-key: node-v${{ matrix.node }}-on-${{ runner.os }}-hash-${{ hashFiles('yarn.lock') }}

        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          # https://docs.github.com/ja/actions/reference/authentication-in-a-workflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

**Comment by bahmutov** [comment]
I have never seen such error, not sure why it would happen

**Comment by GeorgeXCV** [comment]
Setup Cypress Action for first time in our project and same error:
```
ENOENT: no such file or directory, stat '/home/runner/work/core-cypress/core-cypress/cypress/videos/core/login.cy.ts-compressed.mp4'
Error: ENOENT: no such file or directory, stat '/home/runner/work/core-cypress/core-cypress/cypress/videos/core/login.cy.ts-compressed.mp4'


Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

Action (CYPRESS_RECORD_KEY is stored as GitHub Secret):
```
name: Daily Regression Tests

on:
  schedule:
    #https://crontab.guru/#0_0_*_*_*
    - cron: "0 0 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start --record
```

**Comment by lalomartins** [comment]
Same here, should add, it's not consistent, sometimes it works, sometimes it fails to find the file. Even rerunning a failed job usually makes it pass. It's kind of critical for us right now, I might have to disable videos to have a working CI.

**Comment by DisasterMan78** [comment]
I'm getting the exact same problem too.

**Comment by REX500** [comment]
Yes! same here... 

ENOENT: no such file or directory, stat '/root/project/cypress/videos/test.cy.js-compressed.mp4'
Error: ENOENT: no such file or directory, stat '/root/project/cypress/videos/test.cy.js-compressed.mp4'

**Comment by MikeMcC399** [comment]
@REX500 

> same here when running cypress version: 11.2.0

Which browser / version are you running against?

**Comment by mdrmuhaimin** [comment]
I have the same issue as well how did you solve it? This is my cypress config

```yaml
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container: cypress/included:cypress-12.7.0-node-18.14.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: automated_tests
          build: npm install
          start: npx cypress run
```

The error is 

```
  -  Video output: /__w/foo/foo/automated_tests/cypress/videos/API/searchProperty.cy.js.mp4

ENOENT: no such file or directory, stat '/__w/foo/foo//automated_tests/cypress/videos/API/searchProperty.cy.js-compressed.mp4'
Error: ENOENT: no such file or directory, stat '/__w/foo/foo/automated_tests/cypress/videos/API/searchProperty.cy.js-compressed.mp4'
```
