### ISSUE TITLE
Add support for Percy visual testing

### ISSUE THREAD

**Issue by dominicroessner** [cypress-io/github-action#35]
We just switched to using the Cypress GitHub Action as opposed to setting it up and running it manually in our workflow. We are now looking to integrate visual testing into our Cypress E2E tests using Percy – https://docs.percy.io/docs/cypress.

The Cypress GitHub Action runs `cypress run` while Percy requires `percy exec -- cypress run` and so Percy currently won't work with this.

**Comment by dominicroessner** [comment]
Will use the Cypress GitHub Action only for setup:

```
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          runTests: false
```

Then use a separate step to run the tests that doesn't use the Cypress GitHub Action.
