### ISSUE TITLE
Cypress 7.0 - how to run component tests in Github action?

### ISSUE THREAD

**Issue by yann-combarnous** [cypress-io/github-action#352]
With the release of Cypress 7.0, component testing now has a dedicated runner, but I could not find any documentation on how to indicate to Github action if we want to launch integration tests or component tests or both.

Could the documentation be updated to clarify this point? Thanks

**Comment by bahmutov** [comment]
You can run the [Cypress component tests](https://on.cypress.io/component-testing) after running E2E tests by calling the action again with a custom command:

```yml
- name: Run E2E tests 🧪
  uses: cypress-io/github-action@v2

- name: Run Component tests 🧪
  uses: cypress-io/github-action@v2
  with:
    # we have already installed everything
    install: false
    # to run component tests we need to use "cypress run-ct"
    command: yarn cypress run-ct
```

See the example project [cypress-react-component-example](https://github.com/bahmutov/cypress-react-component-example)
