### ISSUE TITLE
Problem with ubuntu-latest - GitHub Actions

### ISSUE THREAD

**Issue by wozniaklukasz** [cypress-io/github-action#355]
Hello.
I tried to run my cypress tests on GH Action with following script:
```yml
name: End-to-end tests
on:
  push:
    branches: [master, develop, cypress]
  pull_request:
    branches: [master, develop]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm run develop:test
          wait-on: http://localhost:3030
```
On every run I got errors like: `AssertionError: Timed out retrying after 4000ms: Expected to find element: 'a[data-cy=link-home]', but never found it.`.

After changing the image to `runs-on: ubuntu-16.04` tests finally works.
