### ISSUE TITLE
Action never reports when parallelization is enabled?

### ISSUE THREAD

**Issue by drj17** [cypress-io/github-action#356]
I'm not sure if this is an issue with this action but it only happened once I enabled parallelization.  Both checks seem to pass but the action is never reported as "completed"

```
name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn api, yarn start:test
          wait-on: 'http://localhost:3000, http://localhost:8081/cypress'
          wait-on-timeout: 120
          install: false
          record: true
          parallel: true
          group: 'E2E Tests'
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload images
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
```
(I truncated the yml to only show the cypress stuff)

Both containers run and pass, but the status is never reported.  Am I doing something wrong here?

![Screen Shot 2021-04-21 at 4 12 31 PM](https://user-images.githubusercontent.com/13426126/115615005-62cbb200-a2bc-11eb-9b43-f8e489e4da75.png)
