### ISSUE TITLE
Does the server started with the start parameter shut down at the end?

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#360]
Seems from https://github.com/bahmutov/cypress-grep-example results that not:

```yml
name: ci
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Install dependencies 📦
        uses: cypress-io/github-action@v2
        with:
          # just perform install
          runTests: false

      # run just the smoke tests with "@smoke" string in their names
      - name: Smoke tests 💨
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install: false
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:8888'
          # pass the grep string
          env: grep=@smoke
          # record the results on the Cypress Dashboard
          # https://on.cypress.io/dashboard-introduction
          record: true
          # tag the smoke tests for quick find
          tag: smoke
        # environment variables while running Cypress
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # if smoke tests passed, run all the tests
      - name: E2E tests 💨
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install: false
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:8888'
          # record the results on the Cypress Dashboard
          # https://on.cypress.io/dashboard-introduction
          record: true
          tag: all
        # environment variables while running Cypress
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The smoke tests pass just fine, but the second action launch is showing an error

![Screen Shot 2021-04-29 at 12 12 13 PM](https://user-images.githubusercontent.com/2212006/116583261-2a435e00-a8e4-11eb-9e70-3c0efff276f0.png)

```
