### ISSUE TITLE
Send ci build id when using --group parameter

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#363]
In https://github.com/bahmutov/cypress-gh-action-small-example I hit a problem: when using the custom test command like this:

```yml
- name: Cypress run
  uses: cypress-io/github-action@v2
  with:
    command: npx cypress run --record --group custom
  env:
    # pass the Dashboard record key as an environment variable
    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    # pass GitHub token to allow accurately detecting a build vs a re-run build
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

the dashboard keeps the group open, and if we re-run the CI job, then It gets an error

```
Using custom test command: npx cypress run --record --group custom
run tests command "npx cypress run --record --group custom"
current working directory "/home/runner/work/cypress-gh-action-small-example/cypress-gh-action-small-example"
/usr/local/bin/npx cypress run --record --group custom
You passed the --group flag, but this group name has already been used for this run.

The existing run is: https://dashboard.cypress.io/projects/xv6u1o/runs

The --group flag you passed was: custom

If you are trying to parallelize this run, then also pass the --parallel flag, else pass a different group name.

https://on.cypress.io/run-group-name-not-unique
```

We should always send the ci-build-id if the user has not specified it, even in the custom command
