### ISSUE TITLE
wait-on ignore 403 response code

### ISSUE THREAD

**Issue by Kokogino** [cypress-io/github-action#367]
I have a workflow with the (for this example relevant) steps:
```
- name: Start BE containers for E2E tests
  run: ./gradlew backendDockerRun --stacktrace

- name: Cypress run UI tests
  uses: cypress-io/github-action@v2
  with:
    start: npm run mock-server, npm run start
    working-directory: proj-web/webapp
    wait-on: 'http://localhost:4200, http://localhost:8060, http://localhost:8070, http://localhost:8080, http://localhost:8090'
```

The first step starts multiple backends in different docker containers.
The cypress action should then wait for the backends to be running on ports 8060, 8070 etc.
The problem is that the backends return a 403 Forbidden when waited on and the cypress action's wait-on times out.
Technically a 403 means that the server is reachable and thus wait-on should succeed.
Maybe a flag `wait-on-ignore: 403` would help with this problem.
Or is there already a solution for this?
