### ISSUE TITLE
Cache stores the app BEFORE "build" step

### ISSUE THREAD

**Issue by mleszcz** [cypress-io/github-action#371]
That causes we are unable to cache anything we generate in the build action, eg assets.

Expected behaviour: on the initial build, cache the app AFTER build step.

BTW: everything else seem to work very nice and smoothly :+1:

**Comment by bahmutov** [comment]
We have never intended for the cache to store additional artifacts like the built site. Think about the folders the action caches - it is just NPM modules and the Cypress binary, not additional user-defined folders.

In fact, I would say caching the built folder is probably an anti-pattern. You want your CI to build the site again, right?

**Comment by mleszcz** [comment]
We got a rails app. We'd like to cache our assets (bundle exec rake assets:precompile).
Unfortunatelly turned out that even if we run above rake task and run actions/cache before cypress-io/github-action it's been then overwriten by cypress-io action's cache restore.

I suspect cypress-io action's cache store (when the first GHA build occurs) step stores just some specific folders, and misses our public/assest public/packs-test folders here:
```
25l[12:27:27]  Verifying Cypress can run /home/runner/.cache/Cypress/7.2.0/Cypress [started]
[12:27:29]  Verifying Cypress can run /home/runner/.cache/Cypress/7.2.0/Cypress [completed]
25h25h::debug::saving NPM modules
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/splash-brands/splash-brands --files-from manifest.txt
Cache Size: ~98 MB (102531192 B)
Cache saved successfully
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/splash-brands/splash-brands --files-from manifest.txt
Cache Size: ~187 MB (196234792 B)
Cache saved successfully
```

Then it's always been restored without it, and infact even if restored before by action/cache it got overwritten by cypress-io cache restore.

Maybe you could take a look and would have some suggestion how can we cache our assets.

```
      - name: Extract branch name (used by assets-cache)
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Cache assets
        id: assets-cache
        uses: actions/cache@v2
        with:
          path: |
            public/assets
            public/packs
            public/packs-test
          key: ${{ runner.os }}-assets-${{ steps.extract_branch.outputs.branch }}
      - name: Precompile assets if not cached
        if: steps.assets-cache.outputs.cache-hit != 'true'
        run: bundle exec rake assets:precompile
      - uses: cypress-io/github-action@v2
        with:
          start: bundle exec rails server -e test -p 5017
          wait-on: "http://localhost:5017"
```

We added
```
      - uses: cypress-io/github-action@v2
        with:
          build: bundle exec rake assets:precompile
          start: bundle exec rails server -e test -p 5017
```

this should detect assets (if restored properly) and quickly skip the step, but unfortunatelly it compiles it once again which takes additional 2 minutes.
