### ISSUE TITLE
Cookies not beeing set

### ISSUE THREAD

**Issue by Renato66** [cypress-io/github-action#372]
## Cookies not beeing set
Locally and at actions/setup-node@v1 action it works as expected but at the cypress-io/github-action@v2 this occurs
### Steps:
- preserve cookies after each test
- intercept every post request to graphql and generate an alias
- create an user
  - send email/password
  - recive a token setted by backend
  - send 2fa code to backend
  - retrive error on api because no token was found

### Files:

<details><summary>actions/setup-node@v1</summary>

```yml
name: E2E test

on:
  push:
    branches:
      - feature/*-e2e

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: yarn install && test
      run: |
        yarn
        yarn dev& yarn test:e2e:ci --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
```

</details>

<details><summary>cypress-io/github-action@v2</summary>

```yml
name: E2E develop integration test

on:
  push:
    branches:
      - feature/*-e2e
jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - run: node -p 'os.cpus()'
  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: "Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install: false
          start: yarn dev
          wait-on: "http://localhost:4000"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: false
          headless: false
          config: defaultCommandTimeout=15000
          group: "Integration - Chrome"
          spec: tests/e2e/integration/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

</details>

<details><summary>code files</summary>

```ts
// dbScripts.ts
export async function seedUser(user: UserSignUpInfo): Promise<UserSignUpInfo> {
  await sendGraphqlPost(createUser, 'getToken')
  await sendGraphqlPost(useEmailCode, 'useToken')
  await sendGraphqlPost(updateUser, 'useToken')
  // [...]
  await sendGraphqlPost(logout, 'removeToken')
  return user
}
export function sendGraphqlPost(body: any, token: any) {
  console.log(token)
  return axios.post(baseUrl(), body, {withCredentials: true})
}

```
```ts
// commands.ts
import { seedUser } from './dbScripts'

Cypress.Commands.add('createUser', (user = getFakeUser()) => {
  let userLogin = null
  signIn.visit().then(() => {
    seedUser(user).then((createdUser) => {
      userLogin = createdUser
    })
  })
  cy.wait('@logoutUser', {
    requestTimeout: 30000
  }).then(() => {
    return cy.wait(500).then(() => {
      return userLogin
    })
  })
})
```

```ts
// support/index.ts
import './commands'
import { LoginUserInput } from './types'

/**
 * Before all test intercept graphql
 * and set an alias to the POST request
 * @example cy.wait('@createUser');
 */
 before(() => {
  Cypress.Cookies.defaults({
    preserve: 'token',
  })
  cy.intercept('POST', '/graphql', req => {
    if (req.body.operationName) {
      req.alias = req.body.operationName
    }
  })
  cy.createUser().then((user) => {
    // [...]
    console.log(user)
    cy.clearCookies()
  })
})
```

```ts
// back end code
setCookies.push({
  name: 'token',
  value: ',
  options: {
    expires: 2021-06-11T14:49:05.998Z,
    httpOnly: false,
    sameSite: undefined,
    secure: false
  }
} )
```
</details>
