### ISSUE TITLE
Component-testing - tag and group option discarded at runtime

### ISSUE THREAD

**Issue by yann-combarnous** [cypress-io/github-action#383]
I followed the example for Component testing, running it after my integration tests, but I cannot get the 2 runs to group together.

This is my setup:
```
      - name: Cypress run e2e
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          cache-key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          install-command: yarn install --prefer-offline --frozen-lockfile
          group: 'Chrome - Integration testing'
          record: true
          start: yarn start
          tag: 'PR - Integration'
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 240
      - name: Cypress run ct
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          command: yarn test:ct --record
          group: 'Chrome - Component testing'
          install: false
          record: true
          tag: 'PR - Component'
```
But when component testing runs, console displays the following:
```
  │ Params:       Tag: false, Group: false, Parallel: false                                        │
```
And in Cypress dashboard, the 2 runs show on separate rows, and tag / group are not set for E2E, indeed.
