### ISSUE TITLE
Google Cloud DB connection not recognized when Cypress starts running

### ISSUE THREAD

**Issue by NevenaCukucan** [cypress-io/github-action#394]
Hi,

I am trying to set a scheduled Cypress test run which requires a connection to the Google Cloud DB as a pre-requisite.
This is my workflow file:

```
name: Overnight Regression
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:  
  regression:
    name: Cypress Regression
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2

    - name: Google Cloud DB connect
      uses: mattes/gce-cloudsql-proxy-action@v1.0.1
      with:
        creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        instance: ${{ secrets.INSTANCE_NAME }}

    - name: Cypress run
      uses: cypress-io/github-action@v2.11.5
      with:
        browser: chrome
        command: npm run cy:reg
        working-directory: tests
    - if: always()
```
When GitHub Actions run this job, the logs show a successful db connection step; however, when Cypress starts running tests, I get a connection error as soon as Cypress tries to execute a db query:
```
CypressError: `cy.task('queryDb')` failed with the following error:
> connect ECONNREFUSED 127.0.0.1:3360
```

Any idea how to solve this? Thanks!
