### ISSUE TITLE
Cucumber Tag filtering is not working

### ISSUE THREAD

**Issue by MatiDiez** [cypress-io/github-action#406]
I'm using cucumber-preprocessor and have tags for all my scenarios.
If I execute my tests from the terminal it runs correctly using `npx cypress-tags run --env TAGS=@Rewrite`

Following the docs here, I got to this configuration, but it is not working. It is running all specs (features) Even though it does recognize it.   `│ Params:     Tag: @Rewrite, Group: false, Parallel: false`

```
...
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          tag: "@Rewrite"
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Am I missing something or it doesn't support cucumber-proprocessor tags?

**Comment by juliosaraiva** [comment]
I also would like to know about that.

**Comment by juliosaraiva** [comment]
I was taking a look in docs, I guess this tag option is different from what we expect, it's to add a tag to the cypress dashboard.

**Comment by chestercharles** [comment]
@MatiDiez do you determine a solution for this? I'm passing `TAGS` as an environment variable but it is still not working.
```
name: Run acceptance tests
uses: cypress-io/github-action@v2
with:
  working-directory: e2e
  install: false
  browser: chrome
  record: true
  parallel: true
  spec: cypress/**/*.feature
env:
  CYPRESS_frontend_base_url: http://localhost:9014
  CYPRESS_admin_frontend_base_url: http://localhost:3000
  CYPRESS_api_base_url: http://localhost:9000
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  ELASTICSEARCH_HOST: elasticsearch:9200
  POSTGRES_HOST: postgres
  NODE_PATH: ./cypress
  TAGS: 'not @in-process and not @third-party'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

With this configuration, the cypress dashboard still runs tests with the `@in-process` tag.

**Comment by chestercharles** [comment]
The solution to my issue was adding the TAGS value to the `cypress.json`:
```
{
    "env": {
        "TAGS": "not @in-process and not @third-party"
    },
}
```

I was under the impression that running the cypress command with a `TAGS` environment variable was equivalent to passing in a value for the cypress `env` parameter, which is not the case.

**Comment by MatiDiez** [comment]
@chestercharles good one. I actually solved it by running NPM scripts I add to my package.json, passing the env variables there. So in my GHA I gust do: 
```
- name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm run recordStaging
```
And for other envs I have different npm scripts.

**Comment by kpturner** [comment]
Try this.  Works for me
```
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          env: TAGS="@Rewrite"
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 ```
