### ISSUE TITLE
wait-on times out, even tough app is ready

### ISSUE THREAD

**Issue by rbuetzer** [cypress-io/github-action#41]
First of all: It's awesome to see how much effort the Cypress team invests into creating examples and bindings for all kinds of tools and services. Thank you.

Now for the issue: I have an app with the following configuration:

```yml
cypress-run:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        start: yarn run parcel src/index.html
        wait-on: http://localhost:1234
```
Full configuration: https://github.com/rbuetzer/kinder/blob/4e3ce07bf651ab5f8f9edcdeda0666d7c93c67da/.github/workflows/run-tests.yml

**Observed behaviour:**

wait-on times out after 60 seconds, even tough the app is ready after <30 seconds.

```
starting server with command "yarn run parcel src/index.html"
current working directory "/home/runner/work/kinder/kinder"
/usr/bin/yarn run parcel src/index.html
waiting on "http://localhost:1234" with timeout of 60 seconds
/usr/local/bin/npx wait-on --timeout 60000 "http://localhost:1234"
yarn run v1.19.1
$ /home/runner/work/kinder/kinder/node_modules/.bin/parcel src/index.html
Server running at http://localhost:1234 
✨  Built in 22.57s.
Error: Timeout
    at Timeout._onTimeout (/home/runner/.npm/_npx/2839/lib/node_modules/wait-on/lib/wait-on.js:113:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

Full log: https://github.com/rbuetzer/kinder/runs/316750720

**Expected behaviour**

wait-on does not time out.

**Analysis**

***Edit**: Ignore the analysis below. Turns out the `&` variant does not work on GH pages. See https://github.com/cypress-io/github-action/issues/41#issuecomment-558032339*

If I use wait-on with a background process instead of using the configuration, the test runs successfully.

```yml
start: yarn run parcel src/index.html & npx wait-on http://localhost:1234
```

Full configuration: https://github.com/rbuetzer/kinder/blob/13e239b1f055fd1e7b222f0697343d0510679085/.github/workflows/run-tests.yml

Successful run: https://github.com/rbuetzer/kinder/runs/316749597

App version which has the issue:
https://github.com/rbuetzer/kinder/tree/4e3ce07bf651ab5f8f9edcdeda0666d7c93c67da

App version which does not have the issue:
https://github.com/rbuetzer/kinder/tree/13e239b1f055fd1e7b222f0697343d0510679085

Diff between the two:
https://github.com/rbuetzer/kinder/compare/4e3ce07bf651ab5f8f9edcdeda0666d7c93c67da..13e239b1f055fd1e7b222f0697343d0510679085
