### ISSUE TITLE
Starting multiple server multiline approach does not work

### ISSUE THREAD

**Issue by Adeynack** [cypress-io/github-action#421]
Documentation for [starting multiple servers](https://github.com/cypress-io/github-action#start-multiple-servers) states:

> You can place the start commands in separate lines
> 
> ```yaml
> with:
>   start: |
>     npm run api
>     npm run web
> ```
> 

However, my configuration having those lines fail.

```yaml
with:
  start: |
    bundle exec rails server
    npm start
```

rake is failing, about no task called:

```
server
npm
```

existing, with the line change as part of the task name passed to `rails` (`rake`).

Comma-Separated is also failing, since the comma is passed along to `bundle exec rails server,` and no task is called `server,` (with the comma).

```yaml
        with:
          start: bundle exec rails server, npm start
```

Multi-line support, as documented, would be really nice. Or accepting a YAML array of things to start and listen to.

```yaml
# Suggestion
        with:
          start:
            - bundle exec rails server
            - npm start
          wait-on:
            - http://localhost:3000
            - http://localhost:8080
```

Thanks in advance to whomever will address this.
