### ISSUE TITLE
Github Actions + Cypress + React Portals isn't working

### ISSUE THREAD

**Issue by wuz** [cypress-io/github-action#425]
Hi there! I'm trying to build out an integration test using Cypress on Github Actions for the React Autocomplete component from [antd](https://ant.design). 
The Autocomplete component creates a React Portal for the completion suggestions, which is mounted to the document body. I've avoided testing the implementation details of the autocomplete component, instead relying on the `type` function to type into the input, press the down key, and then press the enter key. The test runs just fine locally, both with `cypress run` and `cypress open`, but as soon as it hits Github Actions, the portaled suggestions just never appear, so pressing down and enter doesn't do anything. The portals only appear when the input element is focused, but it doesn't ever lose focus from what I can tell.

Here is the video of the test typing into the component locally:

https://user-images.githubusercontent.com/2363236/134538596-d5d98f1b-97ef-4c6c-bd92-ccf33fc24e3b.mp4

And here is a video of it running on Github actions:

https://user-images.githubusercontent.com/2363236/134538371-2a108cdc-e94b-43f4-b483-5f5d01e1d4de.mp4

I'm using the cypress action - here is the relavant configuration:

```
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          browser: chrome
          install: false
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          config-file: frontend/cypress-ci.json
          config: baseUrl=http://localhost:4000, apiUrl=http://localhost:3000
          command: yarn cypress:ci:run --browser chrome
```
