### ISSUE TITLE
Github Actions Firefox : error while loading shared libraries: libgbm.so.1

### ISSUE THREAD

**Issue by QuentinDouarre** [cypress-io/github-action#439]
With this workflow : 

```
name: Cypress
on: [push]
jobs:
  chrome:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node12.13.0-chrome78-ff70
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start
          config: videoRecording=false,screenshotOnRunFailure=false

  firefox:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: firefox
          start: npm start
          config: videoRecording=false,screenshotOnRunFailure=false

  edge:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: edge
          start: npm start
          config: videoRecording=false,screenshotOnRunFailure=false

```

I have this error in firefox : 
```
start server "npm start command "npm start"
current working directory "/__w/SIGL-IHM/SIGL-IHM"
/usr/local/bin/npm start
/github/home/.cache/Cypress/8.6.0/Cypress/Cypress: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
Test run failed, code 127
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

Chrome and Edge work perfectly
