### ISSUE TITLE
Yarn Plug and Play Zero-Installs: Cannot Cy with github actions

### ISSUE THREAD

**Issue by ZeroPie** [cypress-io/github-action#441]
Same cannot get it to work. A timeout occurs during pipe run:

```
Opening Cypress...
[1965:1017/182222.115087:ERROR:node_bindings.cc(278)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[1965:1017/182222.115179:ERROR:node_bindings.cc(278)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[1965:1017/182224.237041:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1965:1017/182224.237078:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2138:1017/182224.258717:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[1965:1017/182224.491841:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1965:1017/182224.516792:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
```

.yml
```
name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path    
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Yarn Install if no cache hit
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn add --cached

    - name: Eslint
      run: yarn lint
            
    - name: Run Component tests 🧪
      uses: cypress-io/github-action@v2
      with:
        install-command : yarn install --immutable --immutable-cache
        command: yarn cypress run-ct 
  ```
