### ISSUE TITLE
Cypress github actions not running in subfolder

### ISSUE THREAD

**Issue by JonasHendel** [cypress-io/github-action#443]
I have a project with a client and a proxy server. The tests are only in the client folder. So I wrote the workflow like this:

```name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.11.7
        with:
          project: ./client
          build: npm run build
          start: npm start
```

However, this results in this error:

```
Run cypress-io/github-action@v2.11.7
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/work/test2/test2/package-lock.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Function.module.exports.hasha.fromFileSync (/home/runner/work/_actions/cypress-io/github-action/v2.11.7/dist/index.js:18048:54)
    at lockHash (/home/runner/work/_actions/cypress-io/github-action/v2.11.7/dist/index.js:6729:26)
    at getNpmCache (/home/runner/work/_actions/cypress-io/github-action/v2.11.7/dist/index.js:6739:16)
    at restoreCachedNpm (/home/runner/work/_actions/cypress-io/github-action/v2.11.7/dist/index.js:6784:21)
    at installMaybe (/home/runner/work/_actions/cypress-io/github-action/v2.11.7/dist/index.js:7365:5)
    at Object.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v2.11.7/dist/index.js:7388:1)
    at __webpack_require__ (/home/runner/work/_actions/cypress-io/github-action/v2.11.7/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/cypress-io/github-action/v2.11.7/dist/index.js:43:19) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/work/test2/test2/package-lock.json'
}
```

I have no idea why this happens, I have created a test repo for the client folder, but with the exact same files and folders (just that the client is the root folder and not a subfolder). In this repo the cypress action runs perfectly.

Here is a link to the repo in which the action doesn't work: https://github.com/JonasHendel/test2

**Comment by JonasHendel** [comment]
I had to change project to working-directory.
```
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.11.7
        with:
          working-directory: client
          build: npm run build
          start: npm start
```
