### ISSUE TITLE
allocate a free port

### ISSUE THREAD

**Issue by gajus** [cypress-io/github-action#445]
Since we are running multiple cypress tests in parallel on the same VM, we need a way to identify a free port to use for running tests. Any suggestions how to achieve it within the constraints of cypress-io actions?

For context, this is how our actions are initiated now:

```yaml
# @see https://github.com/cypress-io/github-action/pull/409
- uses: sergiubcn/github-action@85b7752121921e41125df5d1ceb138c11665913c
  env:
    CYPRESS_INSTALL_BINARY: '0'
    CYPRESS_API_URL: 'https://local.contra.dev:8080/api'
    NODE_ENV: 'test'
  with:
    start: yarn start:for-ci-integration-tests
    build: yarn build:for-ci-integration-tests
    browser: chrome
    config: 'baseUrl=https://local.contra.dev:8080/'
    wait-on: 'https://local.contra.dev:8080/'
    headed: true
```

Somehow need to replace 8080 here with a port that's allocated for this test.
