### ISSUE TITLE
workflow failing with EACCES: permission denied

### ISSUE THREAD

**Issue by raviteja83** [cypress-io/github-action#446]
This is the workflow that is run
![image](https://user-images.githubusercontent.com/6763261/139093526-a68789a8-0a10-4dd5-ac70-535c00d3bfe3.png)

It used to work till evening today. started failing from then. Am I missing something? 

This is the error on workflow fail

![image](https://user-images.githubusercontent.com/6763261/139093350-39415de9-44cc-4638-b219-9bfee1fdaf8f.png)

**Comment by Bran1304** [comment]
I am encountering the exact same error, started after updating to node 16

**Comment by realies** [comment]
Adding this after `actions/cache@v2` and before `cypress-io/github-action@v2` makes the workflow go through:
```
      - run: chown 1001:1001 /github/home/.cache && echo "pwn dat cache"
```

Cypress `browsers` images run as root, so `actions/cache@v2` restores cache with a `root:root` owner, and `cypress-io/github-action@v2` dislikes that.

**Comment by tconroy** [comment]
Also running into this issue.. Does not seem to be fixed for me with @realies `chown` example:

```
jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome94-ff93
    steps:
      # Checkout the branch.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Reclaim cache directory
        run: chown -R 1001:1001 /github/home/.cache && echo "pwn dat cache"

      # install Cypress, run lint and build
      - name: Cypress install
        uses: cypress-io/github-action@v2  # <----- This is where mine fails, when cypress is installing
        with:
          runTests: false
      - run: yarn cypress info
      - run: node -p 'os.cpus()'
      - run: yarn lint
      - run: yarn build

      # Upload build artifacts
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build
```

**Comment by hallettj** [comment]
I ran into this issue using a Cypress browser docker image with Node v16. I fixed the problem by running job as a non-root user according to the instructions in the action readme. (The instructions in the readme tell you to do this to make Firefox work, but the same fix seems to solve this permissions issue.) It looks like the home directory in the Cypress images is owned by user ID 1001, so I configured my job to run with the same ID.

Here is my setup job:

```yaml
  setup-for-frontend-integration-tests:
    name: Set up for frontend tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
      options: --user 1001  # ← THIS IS THE IMPORTANT LINE!
    steps:
      - uses: actions/checkout@v2

      - name: Persist Next.js build cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-

      - name: Install and cache Cypress and npm dependencies, and build frontend server
        uses: cypress-io/github-action@v2
        with:
          # Don't run tests; we're only using the install and build steps here
          runTests: false
          build: yarn build

      - name: Save built frontend server
        uses: actions/upload-artifact@v2
        with:
          name: frontend-server
          path: .next
          if-no-files-found: error
```
