### ISSUE TITLE
Cypress does not pick up Node version set by Action

### ISSUE THREAD

**Issue by sergiubcn** [cypress-io/github-action#467]
**Issue:** Cypress does not pick up the NodeJS version set by another GH Action

**Versions:** Cypress 9.x

**Steps to reproduce:**
1. Configure a GH Actions pipeline as follows: (a) set up a NodeJS version other than `12` (which is used by default in the Cypress GH Action) and (b) execute any Cypress test.
2. Notice the NodeJS version that Cypress uses.

**Prerequisites:** (a) a GH repo and (b) a GH workflow `yml` config.

**Conclusions:** Regardless of the NodeJS version set by `actions/setup-node@v2` Cypress still uses the default `12`. This is working as expected with Cypress 8.x.

**Example:** https://github.com/sergiubcn/cy-ci-node/runs/4467813743?check_suite_focus=true
https://github.com/sergiubcn/cy-ci-node/blob/master/.github/workflows/cicd.yml

**Note:** This does not reproduce locally if setting various NodeJS versions via `nvm use`. 
If it actually turns out to be an issue with Cypress I'll gladly move this ticket to that repo.

**Comment by magnetikonline** [comment]
Thanks for reporting @sergiubcn - just like to add we're seeing exactly the same behaviour in our workflows.

**Comment by BioCarmen** [comment]
Is that fixed now. I am seeing the same issue when I update cypress to 9.*

**Comment by unickq** [comment]
Cypress 9.2.0

```yaml
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: node -v

      - name: Cypress run
        uses: cypress-io/github-action@v2
```

![image](https://user-images.githubusercontent.com/6696821/148548062-89119402-bf38-41bd-ae95-fb52046e8e69.png)
