### ISSUE TITLE
config parameter not passed from action to runner

### ISSUE THREAD

**Issue by huy-nguyen** [cypress-io/github-action#478]
I was running the action with the following setting but the `defaultCommandTimeout` config was not passed from the action to the runner:

```yaml
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn workspace api start, yarn workspace main-ui serve
          wait-on: "http://localhost:4000/healthcheck, http://localhost:3000"
          command: yarn workspace main-ui cy:run
          config: defaultCommandTimeout=20000
```
However, setting that value via environment variable works:

```yaml
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_DEFAULT_COMMAND_TIMEOUT: 20000
        with:
          install: false
          start: yarn workspace api start, yarn workspace main-ui serve
          wait-on: "http://localhost:4000/healthcheck, http://localhost:3000"
          command: yarn workspace main-ui cy:run
```
