### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/__w/{repo_name}/{repo_name}/cypress/videos'

### ISSUE THREAD

**Issue by DjNaGuRo** [cypress-io/github-action#480]
I'm facing the following problem on GitHub Actions when the job reaches this line of code : ` npx cypress run -P . -C cypress.json -r spec  --record`. The below error message is thrown and the workflow failed ( `Error: Process completed with exit code 1`)
```
Warning: We failed to record the video.

This error will not alter the exit code.

Error: EACCES: permission denied, mkdir '/__w/{repo_name}/{repo_name}/cypress/videos'
```
I didn't finf any fix of this on the web, can someone help for that ?

PS: I used the Cypress image : `cypress/browsers:node16.5.0-chrome94-ff93`

**Comment by Develliot** [comment]
to sure if this is related to #446

**Comment by gkatsanos** [comment]
@Develliot related possibly, but the fix proposed does not address it :(

**Comment by hash-bang** [comment]
For some reason the default video storage path gets screwed up in the Docker image. It seems to point to an unwritable location rather than somewhere it can work with the video compression.

If you force the videoStorage config in your .yml file to something usable it seems to work:

```yaml
      - name: 'E2E Tests - Chrome'
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: npm run cypress:record
          browser: chrome
          record: true
          parallel: true
          group: 'E2E - Chrome'
          config: videosFolder=/tmp/cypress-videos        # <-- Fix for https://github.com/cypress-io/github-action/issues/480
```
