### ISSUE TITLE
Document restrictions on start command

### ISSUE THREAD

**Issue by fbiville** [cypress-io/github-action#482]
Hi,

I just wasted hours trying to understand why my server would not start despite the file being there and executable:
```yaml
      - uses: cypress-io/github-action@v2
        env:
          [...]
          DEBUG: '@cypress/github-action'
        with:
          [...]
          path: e2e
          start: ../some/executable/script
```

It turns out `io.which` from `@actions/io`, called by this GitHub action, refuses to parse paths from relative script files.
I assume this is for security reasons.
See code [here](https://github.com/actions/toolkit/blob/daf8bb00606d37ee2431d9b1596b88513dcf9c59/packages/io/src/io.ts#L257-L260):
```typescript
  if (tool.includes(path.sep)) {
    return []
  }
```

I believe the documentation of `start` should clearly state that scripts cannot be executed like this.
