### ISSUE TITLE
Videos don't seem to work on GitHub Action default runners

### ISSUE THREAD

**Issue by webbertakken** [cypress-io/github-action#483]
**Context**

Bug report regarding videos on GitHub Actions default runners.

**Steps**

I have just set up cypress for my repository. 

Everything seems to be set up correctly, and `yarn cypress run` yields a video that works.

Now I'd like to reproduce this in CI, and created a [workflow](https://github.com/webbertakken/lomanpsychologie-nl/blob/main/.github/workflows/e2e.yml) with the same settings apart from the URL:

**Relevant part of the workflow**

```
      - name: Run Cypress 🌲
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
      - name: Upload video 📼
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test videos
          path: cypress/videos
          retention-days: 14
```

I'm using default `ubuntu-latest` runner with default settings.

** Results**

The tests run fine (all 91 succeed as expected) and the video uploads. However the video cuts out after a few seconds. Only the last frame is updated to show the tests. Presumably because the machine runs out of resources while loading the page.

Video artifact

[Test videos.zip](https://github.com/cypress-io/github-action/files/7891723/Test.videos.zip)

Video file

https://user-images.githubusercontent.com/20756439/150003505-a2fcf6b4-08da-4596-925b-9e9cb2dd473b.mp4

Screenshot of last frame

![image](https://user-images.githubusercontent.com/20756439/150003560-f67e0220-6f25-43b2-8049-230fa2b75f58.png)

**Related**

I believe that most reports [here](https://github.com/cypress-io/cypress/issues/16884) are also related to this issue.
