### ISSUE TITLE
Do we have input for the "spec" argument?

### ISSUE THREAD

**Issue by golfzaptw** [cypress-io/github-action#49]
```yml
// example
      - uses: cypress-io/github-action@v1
        with:
          spec: cypress/integration/custom/**/*.custom.spec.js
```
or
```yml
// example
      - uses: cypress-io/github-action@v1
        with:
          args: --spec cypress/integration/custom/**/*.custom.spec.js
```
