### ISSUE TITLE
How to start and wait on with multiple folders?

### ISSUE THREAD

**Issue by mauriciosoares** [cypress-io/github-action#490]
In my CI setup I need to setup 2 different services in order to run my e2e steps, and each one of these services are installed in a different folder (UI in this case is the repo the action is running on, and where my e2e tests are)

```yml
      - name: Checkout UI
        uses: actions/checkout@v2
        with:
          path: ui

      - name: Checkout API
        uses: actions/checkout@v2
        with:
          repository: other/repo
          path: api
```

Is there any way to setup these services that are running on different folders? I tried to run it using the `command` option, but doesn't look like it has even executed the commands... Maybe because I'm also using the `wait-on` option?

```yml
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          working-directory: ui
          command: cd ../api && NODE_ENV=ci npm start, cd ../ui && npm start
          wait-on: 'http://localhost:3000, http://localhost:4000'
```

The action fails with the following log:

```
http://localhost:3000 timed out on retry 91 of 3, elapsed 90258ms, limit 90000ms
```

So it looks like cypress is waiting on these services before even running `command` 🤔
