### ISSUE TITLE
Show parallel testing example across multiple operating systems

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#5]
Run tests in parallel on each operating system

Can be done as separate jobs or can it be a single matrix with several containers per OS? How to group them?

**Comment by bahmutov** [comment]
depends on #4 and #3

**Comment by bahmutov** [comment]
```yml
  parallel-runs-across-platforms:
    name: every OS
    strategy:
      matrix:
        # run 2 copies of the current job in parallel
        # and they will load balance all specs
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        containers: [1, 2]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: run tests
        uses: cypress-io/github-action@v1
        with:
          record: true
          parallel: true
          group: Parallel 2x on ${{ matrix.os }}
          # on Mac and Linux we can use "npm start"
          start: npm start
          # but for this particular project on Windows we need a different start command
          start-windows: npm run start:ci:windows
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.dashboardRecordKey }}
```

from https://github.com/cypress-io/cypress-example-kitchensink/pull/326
