### ISSUE TITLE
Fails to find cypress.json on windows-latest

### ISSUE THREAD

**Issue by masonicboom** [cypress-io/github-action#50]
With the config below, my tests run successfully on ubuntu-latest and macos-latest, but fail on windows latest with this message

```
Could not find a Cypress configuration file, exiting.
466

467
We looked but did not find a "cypress.json" file in this folder: d:\a\repo\repo
468
Error: The process 'C:\Program Files\nodejs\npx.cmd' failed with exit code 1
469
    at ExecState._setResult (d:\a\_actions\cypress-io\github-action\v1\dist\index.js:894:25)
470
    at ExecState.CheckComplete (d:\a\_actions\cypress-io\github-action\v1\dist\index.js:877:18)
471
    at ChildProcess.<anonymous> (d:\a\_actions\cypress-io\github-action\v1\dist\index.js:777:27)
472
    at ChildProcess.emit (events.js:210:5)
473
    at maybeClose (internal/child_process.js:1021:16)
474
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
475
##[error]The process 'C:\Program Files\nodejs\npx.cmd' failed with exit code 1
476
##[error]Node run failed with exit code 1
```

```
name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        machines: [1, 2] # Add items to this list to increase parallelism.
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          parallel: true
          group: ${{ matrix.platform }}
          start: $START_COMMAND
          wait-on: http://$HOST:$PORT
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
```

Any idea what's wrong? Got the same result when using `actions/checkout@v1` as well.
