### ISSUE TITLE
Github action worker hangs when tests in parallel have finished

### ISSUE THREAD

**Issue by alessioerosferri** [cypress-io/github-action#507]
Current behaviour:
My GitHub workflow runs in parallel using multiple containers connected to Cypress dashboard and, when the run shows as finished on Cypress dashboard, I can still see a few containers that are hanging forever. Nothing is being logged from these containers. As soon as I cancel the workflow, the final GitHub log shows that the pod had finished correctly but Github did not receive an exit 0 command from the cypress process. 

Expected behaviour:
I would like the workers to finish correctly when the run finishes and all tests have run.

Cypress version: 9.3.1

**Comment by alessioerosferri** [comment]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/28859897/154662050-7175da9b-ab91-4448-be21-af5dfb6e729d.png">

**Comment by alessioerosferri** [comment]
Up to now, it seems that this hanging problem happens only when the `cypress.json` file has key `video` set to false

**Comment by d-ivashchuk** [comment]
not running anything in parallel but as soon as I set `video` to false in config the whole action can't proceed to finish and hangs with error `CypressError: cy.screenshot() timed out waiting 30000ms to complete.`:

```
name: E2E Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn run build
          start: npm run start
          wait-on: http://localhost:3000
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Cypress E2E Videos
          path: cypress/videos

```
