### ISSUE TITLE
`dashboardUrl` not set in step outputs?

### ISSUE THREAD

**Issue by jazanne** [cypress-io/github-action#511]
I just enabled recording on Cypress dashboard for my project, but am having trouble printing the `dashboardUrl`.

It prints at the end of a run (in the Cypress step itself), but when I try to print it in another step it's blank

**Cypress step:**
```
  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  smoke.test.ts                            00:14        3        3        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:14        3        3        -        -        -  


───────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                       
  Recorded Run: https://dashboard.cypress.io/projects/xxx/runs/7           
```

**Print step:**
```
Cypress finished with: success
See results at
```

My configuration

```yml
name: Deploy
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build-deploy:
    ...
  smoke-test:
    needs: build-deploy
    runs-on: ubuntu-latest
    name: Smoke test
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        id: cypress
        continue-on-error: true
        with:
          command-prefix: yarn dlx # need this bc using yarn pnp w/o node_modules
          install-command: yarn install --immutable --immutable-cache
          build: yarn build-custom
          headless: true
          config: baseUrl=https://env.com/
          spec: cypress/integration/smoke.test.ts
          record: true
        env:
          CYPRESS_PROJECT_ID: xxx
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Dashboard URL
        run: |
          echo Cypress finished with: ${{ steps.cypress.outcome }}
          echo See results at ${{ steps.cypress.outputs.dashboardUrl }}
```

Update: I also tried `echo ${{ toJSON(steps.cypress.outputs) }}` in my step and it just prints an empty object `{}`

Update 2: added missing configuration for command-prefix and custom install

**Comment by Themezv** [comment]
Hmm +1
I have the same issue when a command-prefix parameter passed

```yaml
      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          env: fileConfig=development
          install: false
          working-directory: e2e
          record: true
          wait-on: yarn e2e:wait
          command-prefix: dotenv-flow -p ../ --
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by jazanne** [comment]
> Hmm +1 I have the same issue when a command-prefix parameter passed

Same! Realized i was missing my command-prefix in configuration example so i added it.

**Comment by lmeynberg** [comment]
Same here ➕ 👍

**Comment by admah** [comment]
@jazanne @lmeynberg what is your use-case for this? 

Based on the code from #166 it's working as expected - at the end of a run via `onTestsFinished` ([line](https://github.com/cypress-io/github-action/blob/7479fb6cd111c87e4eca28d235c5f05edacee7d3/index.js#L570)).

**Comment by jazanne** [comment]
i expect this step to print a link to the dashboard 

```
- name: Print Dashboard URL
        run: |
          echo Cypress finished with: ${{ steps.cypress.outcome }}
          echo See results at ${{ steps.cypress.outputs.dashboardUrl }}
```

**Comment by admah** [comment]
@jazanne that's considered a separate step so the output isn't going to be available there. Have you seen the dashboard link that comes with the Workflow summary #566?

**Comment by jazanne** [comment]
@admah not sure i understand, typically outputs are available in following steps of the same job

btw, i copied this original snippet from docs, where it seems to indicate that this should be allowed

https://github.com/cypress-io/github-action#outputs

**Comment by admah** [comment]
@jazanne this does look like a bug. We'll have to look into it a bit more.

**Comment by dzzk** [comment]
Hi @admah, is there a chance to start previous/next versions of action or it's totally surprisingly new from GH itself?

**Comment by admah** [comment]
@dzzk yes. Here are the instructions for specifying the version: https://github.com/cypress-io/github-action#explicit-version

**Comment by sansarip** [comment]
Bump! 😄

**Comment by MikeMcC399** [comment]
@far11ven 

> Was it fixed somehow in some newer versions? 

It seems to be working fine in `cypress-io/github-action@v5`. Check out job [7838187516](https://github.com/cypress-io/github-action/actions/runs/4463161679/jobs/7838187516) which shows:

![image](https://user-images.githubusercontent.com/66998419/226348580-f12c1201-60d2-4f94-abd1-263646467599.png)

This is a log of running the example workflow [.github/workflows/example-recording.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-recording.yml).

BTW: @admah unassigned himself from this issue. He is no longer a member of [cypress-io](https://github.com/cypress-io).

Are you having problems with this?

Also it would be good to hear if @jazanne also still considers this to be an issue with the current @v5 version.

**Comment by MikeMcC399** [comment]
@far11ven 

You can also try this out for yourself if you have a fork of this repository. Follow the instructions in 

- [example-recording.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-recording.yml)
- [examples/recording](https://github.com/cypress-io/github-action/tree/master/examples/recording)

**Comment by far11ven** [comment]
@MikeMcC399 Thanks for the quick response, I'm using v5.5.0

![image](https://user-images.githubusercontent.com/26922130/226355080-3ada7c32-88ef-4641-bfee-9b962a8b5782.png)


![image](https://user-images.githubusercontent.com/26922130/226354876-ef8022a2-0c59-4a98-bceb-776120ef490d.png)

**Comment by MikeMcC399** [comment]
@far11ven 

Are you setting the `record`  parameter of `cypress-io/github-action` to `true` or are you recording by hand?
Could you expand the arrow in the log to the left of "Run cypress-io/github-action@v5.5.0"?

In the example, it looks like this:

![image](https://user-images.githubusercontent.com/66998419/226411062-e27a840e-81f3-493e-a3f9-c6f46cdedda9.png)

At the end of the step log "Cypress tests" it logs

"Recorded Run: https://cloud.cypress.io/projects/3tb7jn/runs/2287"

Please check the step where you are calling `cypress-io/github-action@v5.5.0` to make sure that you are also seeing "Recorded Run:" logged for your project.

If it is not logged then the step "Print Cypress Cloud URL" will not be able to pick anything up because nothing has been saved.

**Comment by Erenndriel** [comment]
Thanks for hinting to the solution @MikeMcC399 , which was not obvious at glance when reading brief documentation of this action.

Previous version failed because we were supplying our custom `command` input which was the culprit of not registering the `dashboardUrl` and leading to a blank output:

```yaml
- name: Cypress run
  uses: cypress-io/github-action@v5
  continue-on-error: true
  with:
    command: npm run cy:run:ci -- --parallel --record --env CI=true,url=${{ inputs.url }},market=${{ inputs.market }},appMode=${{ inputs.appMode }},viewport=${{ inputs.viewport }}
  env:
    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_CLOUD_RECORD_KEY }}
```

The new version that worked for me and my team:
```yaml
- name: Cypress run
  uses: cypress-io/github-action@v5
  continue-on-error: true
  with:
    parallel: true
    record: true
    env: ${{ env.CY_ENV }}
  env:
    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_CLOUD_RECORD_KEY }}
```

What is _**NOT OBVIOUS**_ in the docs (at least to me and 2 other devs trying to setup the workflow) is that the action by default executes `cypress run` command. So we were ought to believe we should pass the custom script from `package.json` as the command. Allthough it worked like a charm, but it failed to set `dashboardUrl`. What I believe the issue behind with a custom command is that when passing `--record` as flag to your command, is not the same as setting the input via `record: true`.

Do you think this is a bug or intentional?
