### ISSUE TITLE
Can't run `start` command with `*` wildcard

### ISSUE THREAD

**Issue by stefan-niedermann** [cypress-io/github-action#514]
Hello there :wave: 
I am trying to run a small spring boot server with the `start` and `wait-on` commands, like

```yml
[...]
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: java -jar server.jar
          wait-on: 'http://localhost:8080'
```

This works pretty well.

Unfortunately I don't know the very exact name of the `.jar` file, because it contains some version information like `server-1.2.3-SNAPSHOT.jar`.

Therefore I tried to use a wildcard, as I am used to on my physical machine: `java -jar server*.jar`. This didn't work (Couldn't find the `.jar` file). I also tried `java -jar $(find "*.jar")` without success.

It seems like I can't use a usual command with wildcards, so:
- Is there a way to achieve my goal?
- Did I miss something?
- Is this a `bash` or `sh` or what exactly leads to the different behavior of the `start` command compared to a default step with a `run` command?

**Comment by stefan-niedermann** [comment]
My current workaround is a predecessor step to rename the file utilizing `mv` with a `*` wildcard:

```yml
[...]
      - name: Rename jar file to strip version information
        run: mv server*.jar server.jar
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: java -jar server.jar
          wait-on: 'http://localhost:8080'
```

However the actual issue is still valid from my point of view and I would appreciate being able to start the `server.jar` directly with a `*` wildcard.
