### ISSUE TITLE
wait-on won't allow && sleep after wait command

### ISSUE THREAD

**Issue by jdborneman-terminus** [cypress-io/github-action#517]
cypress-io/github-action@v2 example:
```
# Run Tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          config: video=true
          browser: ${{ matrix.browser }}
          headless: true
          tag: 'UI-${{ matrix.browser }}'
          record: true
          parallel: true
          command-prefix: npx
          working-directory: apps/[myapp]
          start: yarn start:[myapp]
          wait-on: 'npx wait-on https:/[myapp]:4200/ && sleep 15'
          wait-on-timeout: 615
          install: false
        env:
          ...
```

Instead of doing the npx wait-on and then sleeping for 15 seconds, I instead see this error:

```
Run cypress-io/github-action@v2
Skipping install because install parameter is false
start server "yarn start:[myapp] command "yarn start:[myapp]"
current working directory "/home/runner/work/[myapp]"
Waiting using command "npx wait-on https://[myapp]:4200/ && sleep 15"
executing command "npx wait-on https://[myapp]:4200/ && sleep 15"
current working directory "/home/runner/work/[myapp]"
/usr/local/bin/yarn start:[myapp]
/usr/local/bin/npx wait-on https://[myapp]:4200/ && sleep 15
yarn run v1.22.17
warning package.json: "dependencies" has dependency "tslib" with range "^2.0.0" that collides with a dependency in "devDependencies" of the same name with version "2.1.0"
$ yarn prepare:[myapp] && nx serve [myapp] --configuration=[localMyApp]
ValidationError: "resources[3]" must be a string
Error: The process '/usr/local/bin/npx' failed with exit code 1
```

The line that stands out is *ValidationError: "resources[3]" must be a string*, which doesn't occur when I take out `&& sleep 15` from the wait-on command.

WHen I run `npx wait-on https://[myapp]:4200/ && sleep 15 ` it works fine locally on my Mac.

Is there a recommended way to make things sleep for just a **little** longer after the wait-on completes? We're seeing an issue where we need a slight wait because even though the wait-on completes apparently the app isn't completely ready. 

Another thing I've tried is wait-on a specific location at the end `npx wait-on https://[myApp]:4200/log-in/` but that hangs indefinitely.

Thanks!
