### ISSUE TITLE
Chrome parallel-group-params-mismatch error

### ISSUE THREAD

**Issue by jebarjonet** [cypress-io/github-action#518]
We use parallelized actions with `browser: chrome`, it worked well until yesterday. Now sometimes (not always) we have this behavior : 

A first container starts with apparently Chrome 98 :

<img width="455" alt="Capture d’écran 2022-03-11 à 15 12 17" src="https://user-images.githubusercontent.com/4401230/157884477-7284d25f-f033-4dcf-a269-0bb80dc4d4bd.png">

The other containers start a minute later and show us this error :

<img width="834" alt="Capture d’écran 2022-03-11 à 15 12 46" src="https://user-images.githubusercontent.com/4401230/157884483-7109923b-13b6-4a9c-88d7-dc160dc8fc93.png">

It says the specs mismatch, I guess it is because of the Chrome version here being Chrome 99 ?

So only 1 container (the first starting) goes ✅ and the others fail like above ❌

The configuration of our Github Action is like this : 

```yml
- name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  browser: chrome
                  build: npm run build
                  config-file: cypress/cypress-ci.json
                  group: "Chrome"
                  parallel: true
                  record: true
                  start: [our starting script]
                  wait-on: [our local url]
```

I don't see a way of specifying a particular browser version with this action, am I missing something ?

**Comment by spruce-bruce** [comment]
I came to ask this same question. My test jobs failed this morning with the same issue. I'm not sure what weird stars aligning behavior had to happen to make chrome 99 available while spinning up my runners this morning, but I'm sure it's related to how github caches packages from apt or something. 

I don't know if we can have a deterministic set of dependencies in gha when setting up parallel boxes... but really I'd rather this be a gha solve, but specifying browser version would be a decent work around for us failing that

**Comment by amaps** [comment]
We had the same issue this morning with our Cypress suites running on Github Actions.

As a temporary workaround, we have switched to Electron browser to unblock teams.

**Comment by jebarjonet** [comment]
For information the situation solved itself after a day or two but it is still happening sometimes, like today for a mismatch between Chrome 101 and Chrome 102

**Comment by codybrouwers** [comment]
Also looking into this issue today. It seems that whenever Chrome releases a new browser version there is a period of time where Github's runners install can run both the old and new versions and Github is in the process of [updating chrome](https://github.com/actions/virtual-environments/issues/5651) this week it looks like. 

I was able to modify the script from [this comment](https://github.com/actions/virtual-environments/issues/5651#issuecomment-1142075171) to ensure that Github is always running the latest stable version of Chrome from Google.

Luckily downloading the new Chrome version is only ~10-20 seconds so it doesn't add too much time to our CI runs if one worker isn't up to date.

<details>
  <summary>Bash Script</summary>

  ```sh
    #!/bin/bash
    # Copied and modified from: https://github.com/actions/virtual-environments/issues/5651#issuecomment-1142075171
    # Used to ensure that Cypress tests are always using the latest version of Chrome.
    # This is important because sometimes when Chrome releases a new version, Github Action runners can run the
    # previous version or the new version and when sharding the tests to run in parallel results in this error:
    # https://github.com/cypress-io/github-action/issues/518

    download_with_retries() {
    # Due to restrictions of bash functions, positional arguments are used here.
    # In case if you using latest argument NAME, you should also set value to all previous parameters.
    # Example: download_with_retries $ANDROID_SDK_URL "." "android_sdk.zip"
        local URL="$1"
        local DEST="${2:-.}"
        local NAME="${3:-${URL##*/}}"
        local COMPRESSED="$4"

        if [[ $COMPRESSED == "compressed" ]]; then
            local COMMAND="curl $URL -4 -sL --compressed -o '$DEST/$NAME' -w '%{http_code}'"
        else
            local COMMAND="curl $URL -4 -sL -o '$DEST/$NAME' -w '%{http_code}'"
        fi

        echo "Downloading '$URL' to '${DEST}/${NAME}'..."
        retries=20
        interval=30
        while [ $retries -gt 0 ]; do
            ((retries--))
            # Temporary disable exit on error to retry on non-zero exit code
            set +e
            http_code=$(eval $COMMAND)
            exit_code=$?
            if [ $http_code -eq 200 ] && [ $exit_code -eq 0 ]; then
                echo "Download completed"
                return 0
            else
                echo "Error — Either HTTP response code for '$URL' is wrong - '$http_code' or exit code is not 0 - '$exit_code'. Waiting $interval seconds before the next attempt, $retries attempts left"
                sleep 30
            fi
            # Enable exit on error back
            set -e
        done

        echo "Could not download $URL"
        return 1
    }

    INSTALLED_CHROME_VERSION=$(google-chrome --product-version)
    INSTALLED_CHROME_VERSION=${INSTALLED_CHROME_VERSION%.*}
    INSTALLED_CHROME_MAJOR_VERSION=$(echo $INSTALLED_CHROME_VERSION | cut -d. -f1)

    # Determine latest release of chromedriver
    # Compatibility of Google Chrome and Chromedriver: https://sites.google.com/a/chromium.org/chromedriver/downloads/version-selection
    LATEST_VERSION_URL="https://chromedriver.storage.googleapis.com/LATEST_RELEASE"
    echo "Fetching latest chromedriver version from: $LATEST_VERSION_URL"
    LATEST_CHROMEDRIVER_VERSION=$(curl "$LATEST_VERSION_URL")
    LATEST_CHROMEDRIVER_MAJOR_VERSION=$(echo $LATEST_CHROMEDRIVER_VERSION | cut -d. -f1)

    echo "Installed Chrome Version: $INSTALLED_CHROME_VERSION"
    echo "Latest ChromeDriver Version: $LATEST_CHROMEDRIVER_VERSION"

    if [ "$INSTALLED_CHROME_MAJOR_VERSION" == "$LATEST_CHROMEDRIVER_MAJOR_VERSION" ]; then
      echo "The latest major version of Chrome is already installed."
      exit 0
    fi

    # Download and install Google Chrome
    CHROME_DEB_URL="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    CHROME_DEB_NAME="google-chrome-stable_current_amd64.deb"
    download_with_retries $CHROME_DEB_URL "/tmp" "${CHROME_DEB_NAME}"
    sudo apt install "/tmp/${CHROME_DEB_NAME}" -f

    # Download and unpack latest release of chromedriver
    echo "Downloading chromedriver v$LATEST_CHROMEDRIVER_VERSION..."
    wget "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
    unzip chromedriver_linux64.zip
    rm chromedriver_linux64.zip

    CHROMEDRIVER_DIR="/usr/local/share/chrome_driver"
    CHROMEDRIVER_BIN="$CHROMEDRIVER_DIR/chromedriver"

    sudo rm -rf $CHROMEDRIVER_DIR/*
    sudo rm -rf $CHROMEDRIVER_BIN/*

    sudo mkdir -p $CHROMEDRIVER_DIR
    sudo mv "chromedriver" $CHROMEDRIVER_BIN
    sudo chmod +x $CHROMEDRIVER_BIN
    chromedriver --version
  ```
</details>

**Comment by alexbjorlig** [comment]
I really hope Cypress can take this issue seriously. Having stable non-flaky test is 50% good-running CI...

**Comment by paulzakin** [comment]
I solved this problem by avoiding the browser bundled with GitHub Actions. 

Basically, I install the latest version of chromium and just use that. 

```yml
 - uses: browser-actions/setup-chrome@latest
    - run: |
        echo "BROWSER_PATH=$(which chrome)" >> $GITHUB_ENV

 - name: Run Cypress tests 🚀
        uses: cypress-io/github-action@v4
        with:
          install: false
          record: true
          parallel: true
          browser: "${{ env.BROWSER_PATH }}"
          start: "your start command"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.recordKey }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
```
