### ISSUE TITLE
Cypress Start and Build inputs should resolve to working directory

### ISSUE THREAD

**Issue by patricksimonian** [cypress-io/github-action#55]
I'm unable to run this action because my server is started in a working directory because it is in a mono repo. 

I've noticed this [line](https://github.com/cypress-io/github-action/blob/master/index.js#L286) hinting at those commands running under the working directory.

Is there a current workaround for starting a server that is not in the root directory?

**Comment by patricksimonian** [comment]
I've made a fork with some changes that utilize using the working directory. To me this seems pretty straight forward. I haven't taken a ton of time to look into cypress's contributing docs yet so I'm not going to make a PR.

https://github.com/patricksimonian/github-action/blob/feat/start-build-wd/index.js#L286

**Comment by bahmutov** [comment]
@patricksimonian could you explain the folder structure in your monorepo and where you want to start the server? Is it something like
```
root/
  packages/
    server/
    e2e/
```
and you want to execute `npm start` inside `packages/server` and then run Cypress tests from `packages/e2e`?

**Comment by patricksimonian** [comment]
sure thing. This may be a case where I've read instructions incorrectly. 

my structure is as follows
```
/
   web/
     package.json
     cypress/
        integration/
              spec1.js
              spec2.js
```

The cypress project and the web project are at the same `root` __relative to each other__. 

The server is just a simple __GatsbyJS__ one for illustration. 
```yaml
- name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          working-directory: web
          start: npm start
```

When attempting to start the server, it looks like it used `cwd` as the root (as logged out during the runtime of the action). Because the `npm start` command is using the `@actions/exec` you are unable to change commands like `cd web && npm start`. 


Does that clarify?

**Comment by jung-han** [comment]
@bahmutov 
Hi. I have the same problem with a @patricksimonian.
Our project link is [here](https://github.com/nhn/tui.grid) and structure is as follows

```
/
    packages
        toast-ui.grid
            package.json
            cypress/
                integration/
                    ~.spec.ts
```

I solved the problem by creating another node action like as follow

```
name: Cypress test

on: [push]

jobs:
  build:
    name: Cypress tests
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install & test
      working-directory: ./packages/toast-ui.grid
      run: |
        npm install
        npm run start
        npm run test
```

But I think It doesn't seem elegant, and I want to use your library to create an action.🤨
How can i solve this? Can you tell me if there is a document I missed?
