### ISSUE TITLE
Cannot run on default Cypress E2E Vue project

### ISSUE THREAD

**Issue by artis3n** [cypress-io/github-action#56]
I am trying to set up a CI workflow for a Vue project using this Action. I am able to run the `cypress` commands manually and directly in the GitHub workflow without issue, but this Action fails to resolve the necessary dependencies for a Vue project due to its caching behavior.

First, I can run `cypress` with the following workflow steps:

```yaml
# https://github.com/actions/cache/blob/master/examples.md#node---npm
- name: Cache Dependencies
  uses: actions/cache@v1
  id: cache
  with:
    path: ~/.npm
    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    restore-keys: |
      ${{ runner.os }}-node-

- name: Install and Build
  run: |
    npm ci
    npm run build --if-present
  env:
    CI: true
#...
- name: Cypress E2E Test
  run: |
    npm run serve &
    PID=`echo $!`
    npx cypress run
    kill -9 $PID
  env:
    CI: true
    NODE_ENV: production
    CYPRESS_baseUrl: http://localhost:8080/
```

Successful result:
![image](https://user-images.githubusercontent.com/6969296/71759927-50d5be00-2e83-11ea-8863-70b6c9e02fa5.png)

#### Explanation of the parameters:

Creating a default project with the [Vue CLI](https://cli.vuejs.org/guide/creating-a-project.html) sets up Cypress at certain defaults. `npm run serve` triggers the command `vue-cli-service serve`. I am not sure what `vue-cli-service` command ends up running (it adds several things to the command line beyond the vue serve).

To run E2E tests, Vue creates a `vue run test:e2e` command that triggers `vue-cli-service e2e`. I am not sure the full changes this command makes to the command line, but it at least sets the `CYPRESS_baseUrl` environment variable based on what port that e2e command successfully launches the local Vue server. `NODE_ENV=production` is used to trigger prod optimizations in the `serve` command.

Attempting with this Action:

```yaml
- name: Cypress E2E Test
  uses: cypress-io/github-action@v1
  with:
    start: npm run serve
    wait-on: http://localhost:8080/
    browser: ${{ matrix.browser }}
    config_file: cypress.json
    spec: "tests/e2e/**/*"
  env:
    CYPRESS_baseUrl: http://localhost:8080/
    CI: true
    # For E2E testing
    NODE_ENV: production
```

The `config_file` and `spec` may not be needed. I am not sure because this fails with the below error:

```
restoring cache /home/runner/.npm
primary key npm-linux-x64-08664ecdc08feabb2c70ddb0bb5e9cf01740547f7e1be85204da6a61a375a7114e8bedeb70bb98b0693188508010712f0fc80afc8468f8191a57ef90f1a1adc6
restoring cache /home/runner/.cache/Cypress
primary key cypress-linux-x64-08664ecdc08feabb2c70ddb0bb5e9cf01740547f7e1be85204da6a61a375a7114e8bedeb70bb98b0693188508010712f0fc80afc8468f8191a57ef90f1a1adc6
/bin/tar -xz -f /home/runner/work/_temp/0eeda399-804e-4102-b9bb-6116542e0157/cache.tgz -C /home/runner/.npm
/bin/tar -xz -f /home/runner/work/_temp/c4b055c6-1e34-4c92-b9bd-38833f856062/cache.tgz -C /home/runner/.cache/Cypress
Cache restored from key: npm-linux-x64-08664ecdc08feabb2c70ddb0bb5e9cf01740547f7e1be85204da6a61a375a7114e8bedeb70bb98b0693188508010712f0fc80afc8468f8191a57ef90f1a1adc6
Cache restored from key: cypress-linux-x64-08664ecdc08feabb2c70ddb0bb5e9cf01740547f7e1be85204da6a61a375a7114e8bedeb70bb98b0693188508010712f0fc80afc8468f8191a57ef90f1a1adc6
/opt/hostedtoolcache/node/12.14.0/x64/bin/npm ci
npm WARN prepare removing existing node_modules/ before installation

> core-js@3.6.1 postinstall /home/runner/work/proj/proj/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

added 64 packages in 10.417s
starting server with command "npm run serve"
current working directory "/home/runner/work/proj/proj"
/opt/hostedtoolcache/node/12.14.0/x64/bin/npm run serve
waiting on "http://localhost:8080/" with timeout of 60 seconds
6 ms GET localhost:8080 ECONNREFUSED

> proj@0.1.0 serve /home/runner/work/proj/proj
> vue-cli-service serve

sh: 1: vue-cli-service: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! proj@0.1.0 serve: `vue-cli-service serve`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the proj@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-01-04T04_58_34_563Z-debug.log
(node:3196) UnhandledPromiseRejectionWarning: Error: The process '/opt/hostedtoolcache/node/12.14.0/x64/bin/npm' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:894:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:877:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:777:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:3196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am not sure why this is failing. I see this Action running `npm ci`, just as I am. I see that completes successfully, which should place `vue-cli-service` in the `node_modules` folder. However, for some reason that is not the case.

Since Cypress is one of the 2 default options for E2E testing in Vue, this Action should probably be able to support the default project construction provided by `@vue/cli`. As it stands currently that does not appear to be the case.

As a side note, because Cypress is one of the default Vue E2E testing options, it may be beneficial to add a note to the README regarding the necessity of adding the `CYPRESS_baseUrl` environment variable to get this action working with `npm run serve` in a Vue project.
