### ISSUE TITLE
Error "Cannot find module 'cypress'" using yarn v1.22.18

### ISSUE THREAD

**Issue by onattech** [cypress-io/github-action#562]
Github actions is failing with the following error for cypress v.10.0.2
![image](https://user-images.githubusercontent.com/53895969/171919519-210c113e-c46d-4f16-8997-e8256a842280.png)

This is my yaml file as mentioned here in the docs https://github.com/marketplace/actions/cypress-io#basic
```yaml
name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
```
