### ISSUE TITLE
does not find cypress.config.js when using Cypress v10

### ISSUE THREAD

**Issue by alxndr** [cypress-io/github-action#568]
When [upgrading to Cypress v10](https://github.com/alxndr/almost-dead-net/pull/484) I saw this error message in CI:

> You are attempting to use Cypress with an older config file: cypress.json
> When you upgraded to Cypress v10.0 the config file was updated and moved to a new location: cypress.config.js
> You may need to update any CLI scripts to ensure that they are referring the new version. This would typically look something like:
> "cypress open --config-file=cypress.config.js"
> https://on.cypress.io/migration-guide

After I [added `config-file: cypress.config.js`](https://github.com/alxndr/almost-dead-net/pull/484/commits/89d760194844d27bdff97b5f764a7b338fca6457#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R21) the integration works.

**Comment by ChillyBots** [comment]
Adding in the `config-file` setting for me still doesn't work:

```
   uses: cypress-io/github-action@v2
   with:
          config-file: cypress.config.ts
          record: true
          parallel: true
          group: 'UI - Chrome'
          install-command: yarn --immutable
          browser: chrome
          headless: true
 ``` 
 
 ``` 
 You are attempting to use Cypress with an older config file: cypress.json
When you upgraded to Cypress v10.0 the config file was updated and moved to a new location: cypress.config.ts
You may need to update any CLI scripts to ensure that they are referring the new version. This would typically look something like:
"cypress open --config-file=cypress.config.ts"
```

**Comment by developer-ocansey** [comment]
@ChillyBots update cypress-io/github-action@v2 to v4.1.0

**Comment by developer-ocansey** [comment]
@alxndr, maybe watching for new releases via https://github.com/cypress-io/github-action/releases might be helpful.

**Comment by zubair538** [comment]
@developer-ocansey

**Comment by lgenzelis** [comment]
> @ChillyBots update cypress-io/github-action@v2 to v4.1.0

Worked for me! Thanks @developer-ocansey :)

**Comment by SirawichDev** [comment]
> @ChillyBots update cypress-io/github-action@v2 to v4.1.0

thanks you're my life saver

**Comment by medmoe** [comment]
I had the same issue but adding this line `config-file: cypress.config.ts` fixed the issue and this is the code block:
```
- name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.ts
          working-directory: truck_mate_front
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
 ```

**Comment by MikeMcC399** [comment]
@medmoe 

You are using an old version of the action which is not compatible with Cypress `10` and later versions:

```
- name: Run Cypress tests
        uses: cypress-io/github-action@v2
```

Your workaround is unnecessary if you use the current version of the action:

```
- name: Run Cypress tests
        uses: cypress-io/github-action@v5
```

`v2` will be blocked from executing by GitHub at the end of May 2023. See  the [CHANGELOG](https://github.com/cypress-io/github-action#changelog). You should update the version of the action which you are using.

**Comment by MikeMcC399** [comment]
Hi @alxndr 

I looked at your https://github.com/alxndr/almost-dead-net/blob/main/.github/workflows/main.yml and you are using
`cypress-io/github-action@v4.1.0`

so although the issue here is solved, your workflow will soon fail. There is a note in the [CHANGELOG](https://github.com/cypress-io/github-action#changelog) which says:

> *Note: [GitHub announced](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) their plan to disable `save-state` and `set-output` commands by May 31, 2023. This will prevent [cypress-io/github-action](https://github.com/cypress-io/github-action) version [v4.2.1](https://github.com/cypress-io/github-action/releases/tag/v4.2.1), and earlier, running after this date since they use `set-output`. Affected users should update to using `v5` of the [cypress-io/github-action](https://github.com/cypress-io/github-action) action before the deadline.*

Unless you have a reason to tie your workflow to a specific minor version and patch version, then I would recommend using simply `cypress-io/github-action@v5`. See [README > Action version](https://github.com/cypress-io/github-action/blob/master/README.md#action-version).

I suggest anyway to close this issue as the original problem is resolved.

**Comment by darryl-mtrs** [comment]
I'm currently encountering the same issue with `cypress-io/github-action@v5`
My config looks like this:
```
name: Cypress
uses: cypress-io/github-action@v5
with:
          config-file: cypress.config.ts
          command: npm run cy:run-unit
          component: true
          record: false
          parallel: false
          browser: chrome
```

On the github action log, CI/CD doesn't use the config file even though stated in the github action yaml file.
