### ISSUE TITLE
[Question] Can I fetch dependacies from a private repo?

### ISSUE THREAD

**Issue by khamiltonuk** [cypress-io/github-action#569]
Firstly thank you for your repo

**What's the problem**
I have supplied my github token and my .npmrc but it I still get 401 Unauthorized when trying to fetch my dependancies 

this is my config
```yaml
name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress install
        uses: cypress-io/github-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_RC: ${{ secrets.NPM_RC }}
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
```

but this is my output
```bash 
Run cypress-io/github-action@v4
/usr/local/bin/yarn --frozen-lockfile
yarn install v1.22.18
[1/4] Resolving packages...
warning Resolution field "@babel/runtime@7.18.3" is incompatible with requested version "@babel/runtime@7.4.5"
warning Resolution field "date-fns@2.28.0" is incompatible with requested version "date-fns@2.22.1"
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.pkg.github.com/download/XXXXXX: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/runner/work/workflow-client/workflow-client/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: The process '/usr/local/bin/yarn' failed with exit code 1
```

**Comment by max-sym** [comment]
@khamiltonuk did you solve it? Thanks!

**Comment by khamiltonuk** [comment]
@max-sym nope, Never managed to solve it, just abandoned it. I will give it another try tomorrow. Perhaps the future version of me is more competent than the past version of me

**Comment by bogem** [comment]
It may sound radical, but my solution was to not use cypress github action and do everything manually :D
```yaml
name: 'E2E Tests'

on:
  pull_request:

jobs:
  E2E:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          # IMPORTANT: We must not use yarn cache here, otherwise you will get an error with Cypress binary not found
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YOUR_TOKEN }}
      - name: Build app
        run: yarn build
      - name: Run app in background
        run: yarn start & yarn wait-on http://localhost:8000 --timeout 5000
      - name: Run Cypress tests
        run: yarn test:e2e
      - name: Upload screenshots of failed e2e tests
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload videos of e2e tests
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

```

**Comment by bogem** [comment]
And with cache:
```yaml
name: 'E2E Tests'

on:
  pull_request:

jobs:
  E2E:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: e2e-cache-${{ hashFiles('yarn.lock') }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YOUR_TOKEN }}
      - name: Build app
        run: yarn build
      - name: Run app in background
        run: yarn start & yarn wait-on http://localhost:8000 --timeout 5000
      - name: Run Cypress tests
        run: yarn test:e2e
      - name: Upload screenshots of failed e2e tests
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload videos of e2e tests
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

```
