### ISSUE TITLE
"Re-run failed jobs" will not work with a parallel workflow

### ISSUE THREAD

**Issue by mellis481** [cypress-io/github-action#574]
After implementing a custom build ID to ensure I could re-run workflows which I've integrated with Cypress Dashboard and configured to run parallelly, I've run into an issue (oddly different than [this](https://github.com/cypress-io/github-action/issues/531) one).

Here is my job FWIW:
```
- id: cypress-mocked-api-tests
  uses: cypress-io/github-action@v2
  with:
    wait-on: 'https://localhost:9001/index.js'
    start: npm run start:${{ env.NODE_ENV }}
    config-file: cypress/config/${{ env.NODE_ENV }}.json
    config: video=true,videoUploadOnPasses=false
    spec: '**/*.spec.ts'
    install: false
    record: true
    parallel: true
    group: 'Mocked-API'
    ci-build-id: ${{ needs.prepare.outputs.uuid }}
```

This job will load balance all my spec files across five containers under a "Mocked-API" group.  This works great and I can re-run all jobs without issue.

On a recent run, one of the five containers failed because one test failed.  I thought I'd test how "Re-run failed jobs" worked on just the failed container job.  My hope/expectation was that it would be smart enough to know which spec files it ran when the entire workflow executed originally (which would have been six spec files which included 22 test) and run those.  Instead it ran zero spec files and completed successfully.  It seems like the matrix-level orchestration that is needed is not occurring when only a failed container job is re-run.  It looks like [someone else](https://github.community/t/how-to-disable-re-run-failed-jobs/238537) has run into this issue too and is trying to solve it by disabling the "Re-run failed jobs" option in Github (which doesn't seem possible).

This is a fairly big problem because it resulted in the group (which I've configured as a status check in my trunk branch protection rule) passing and the PR being able to be merged when it had never successfully run all tests.
