### ISSUE TITLE
Could not determine executable to run npx error

### ISSUE THREAD

**Issue by HarrisonFretwell** [cypress-io/github-action#580]
When running the install step for cypress I get the following error:
```
/opt/hostedtoolcache/node/16.15.1/x64/bin/npx cypress cache list
(https://github.com/PyroAnalytics/PyroCode/runs/7146691687?check_suite_focus=true#step:7:38)
npm ERR! could not determine executable to run
```
This action has been working fine for me for few months, and then suddenly started failing a few weeks ago.
So far I've attempted different versions of ubuntu in the action, disabling caching, using a different version of node, updating my version of cypress to the latest and the version of the GitHub action all to no avail.

Below is the relevant parts of my GitHub action.
```yml
jobs:
  cypress:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
        # Cache node-modules, invalidate on any yarn.lock changing
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 60000
        env:
          CI: true
      - name: Build repo
        run: yarn build

      # Install cypress
      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          working-directory: cypress
```
