### ISSUE TITLE
Is is possible to start a Python server before running tests ?

### ISSUE THREAD

**Issue by LeMeteore** [cypress-io/github-action#593]
According to the [documentation](https://github.com/cypress-io/github-action#start-server), I can start a server before running the tests. Is it possible to start a different kind of server ? For example, start a Python server ? If yes, what is the correct way of doing please ? I've tried the following without success:

```
     - name: "NPM Serve"                                                                                                  
        run: |                                                                                                             
          cd admin_ui                                                                                                      
          npm run serve &                                                                                                  
          cd ..                                                                                                            
      - name: "Run Cypress tests"                                                                                          
        uses: "cypress-io/github-action@v4"                                                                                
        with:                                                                                                              
          browser: chrome                                                                                                  
          headed: true                                                                                                     
          working-directory: ./admin_ui                                                                                    
          start: export PYTHONPATH='..' && python -m piccolo_admin.example --inflate=10000 &        
          ```
