### ISSUE TITLE
EACCESS when running in a rootless self-hosted runner

### ISSUE THREAD

**Issue by jwoodrow** [cypress-io/github-action#596]
Hi 👋 

First off a bit of context.
We've configured our self-hosted server to make it as secure as possible and so we have docker configured in rootless mode. This was causing us issues with the checkout stage before when we did this:

```yaml
      - name: Checkout code
        uses: actions/checkout@v3
```

The error we would get would be along the lines of this:

```bash
EACCES: permission denied, open '/__w/_temp/some/hashed/path'
```

but it was fixed by changing it to this:

```yaml
      - name: chown workspace
        run: |
          sudo chown -R $(whoami):$(whoami) $GITHUB_WORKSPACE

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          set-safe-directory: false
```

Now that our unit tests are working again on the self-hosted runner (and checkout is too) I started converting our cypress workflow to make it run on self-hosted but we're now encountering a similar issue once again.
```yaml
      - name: Cypress (Chrome)
        uses: cypress-io/github-action@v4
        with:
          start: bundle exec rails s
          wait-on: 'http://localhost:5002/health_check'
          wait-on-timeout: 60
          browser: chrome
```

and the error we're getting is this:

```bash
EACCES: permission denied, open '/__w/_temp/_runner_file_commands/set_env_06dd188a-6b79-4322-b277-726a592d78d2'
```

My question was two-fold:
1. Is there a similar option to the `set-safe-directory: false` that the checkout action has in place which seems to avoid using temp files and directory during the checkout phase ?
2. If there isn't, would I be better off configuring cypress and all, myself during my tests and not use any actions ?

I have control over the UID/GID of the docker container user, since we're using our own base image but from my experience trying to debug a similar error with the checkout phase setting it to 1001/1001 didn't actually solve anything last time and only brought more problems because I had to change permissions everywhere on the self-hosted runner to work (which ended up in me simply ripping it down and starting from scratch...)

Thanks for any insight and feel free to ask me to test some things out !
