### ISSUE TITLE
Should we include checkout step?

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#6]
Right now we check out code using 
```yml
- name: Checkout
  uses: actions/checkout@v1
# the rest of the steps
```
Can we include the checkout step ourselves by default?
