### ISSUE TITLE
Permission error when creating screenshots

### ISSUE THREAD

**Issue by matiasgarcia** [cypress-io/github-action#614]
I get a permission error when Cypress tries to take a screenshot:

```
 1) SoloMail
       Start with a profile:
     Error: EACCES: permission denied, mkdir '/__w/compliance-onboarding-ui/compliance-onboarding-ui/cypress/screenshots/spec.cy.ts'
```

Action:
```
name: E2E Tests

on:
  workflow_call:

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome94-ff93
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm run start:test
          command: npm run cypress:run -- -b chrome
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
```

Command from package.json:

```
"cypress:run": "cypress run --config-file cypress/cypress.config.ts"
```

cypress.config.ts

```
import { defineConfig } from 'cypress'

export default defineConfig({
  e2e: {
    baseUrl: "http://localhost:3000",
    video: false,
    chromeWebSecurity: false,
    experimentalSourceRewriting: true,
  }
})

```
