### ISSUE TITLE
Failed on running actions through act locally

### ISSUE THREAD

**Issue by convers39** [cypress-io/github-action#615]
I am testing the actions locally with [act](https://github.com/nektos/act).

What I was trying to do is launch docker containers and run `npx cypress run` against the localhost server. But could not make it through.

My folder structure looks like below:

```
.
├── README.md
├── docker-compose.prod.yaml
├── docker-compose.test.yaml
├── docker-compose.yaml
├── e2e
│   ├── Dockerfile
│   ├── cypress
│   ├── cypress.config.js
│   ├── cypress.env.json
│   ├── package-lock.json
│   ├── package.json
│   └── tsconfig.json
├── backend
│   ├── Dockerfile
│   ├── package-lock.json
│   ├── package.json
│   ├── src
│   └── tsconfig.json
├── client
│   ├── Dockerfile
│   ├── README.md
│   ├── package-lock.json
│   ├── package.json
│   ├── public
│   ├── src
│   ├── tsconfig.json
│   └── yarn.lock
```

I run with `act -j e2e --container-architecture linux/amd64`.

Here is my workflow file:

```yml
name: E2E on Chrome
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-20.04
    name: Cypress e2e test
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install OS dependencies
        run: |
          apt search libnss3
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: "2.1.0"
      - name: Create dotenv file
        run: |
          touch .env
          echo USER_POOL_ID=${{secrets.USER_POOL_ID}} >> .env
          echo AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} >> .env
          cat env
      - name: Start containers
        run: docker compose -f 'docker-compose.test.yaml' up -d --build
      - name: Run tests
        uses: cypress-io/github-action@v4
        env:
# ...
        with:
          browser: chrome
          command: npx cypress run
          working-directory: e2e
          wait-on: "http://localhost:3000, http://localhost:3001"
          spec: |
            cypress/**/*cy.{js,ts}

```

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/42597395/196161677-17926291-0160-44ec-bf7d-e1c128234e0d.png">

No idea about those error detail:

```
| qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
| qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
| qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

I also tried to start servers without docker but encountered connection issues when running `yarn install`

```yml
name: E2E on Chrome
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-20.04
    name: Cypress e2e test
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install OS dependencies
        run: |
          apt search libnss3
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install yarn
        run: npm i --global yarn
      - name: Install client dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: client
          useLockFile: false
          install-command: yarn install
      - name: Install backend dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: backend
          useLockFile: false
          install-command: npm install
      # - name: Install Compose
      #   uses: KengoTODA/actions-setup-docker-compose@main
      #   with:
      #     version: "2.1.0"
      - name: Create dotenv file
        run: |
          touch client/.env
          touch backend/.env
          echo AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} >> backend/.env
          echo AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} >> backend/.env
          echo REACT_APP_BACKEND_ENDPOINT_PRD=${{secrets.REACT_APP_BACKEND_ENDPOINT_PRD}} >> client/.env
          echo REACT_APP_BACKEND_ENDPOINT_LOCAL=${{secrets.REACT_APP_BACKEND_ENDPOINT_LOCAL}} >> client/.env
          echo REACT_APP_BACKEND_KEY=${{secrets.REACT_APP_BACKEND_KEY}} >> client/.env
          echo REACT_APP_BACKEND_PASSWORD=${{secrets.REACT_APP_BACKEND_PASSWORD}} >> client/.env

          cat client.env
          cat backend.env
      # - name: Start containers
      #   run: docker compose -f 'docker-compose.test.yaml' up -d --build
      # - name: Start xvfb
      #   run: |
      #     Xvfb :1 -screen 0 1280x800x24 & export DISPLAY=:1
      #     set NODE_OPTIONS=
      - name: Start server
        run: |
          cd backend
          npm run start
      - name: Start client
        run: |
          cd client
          npm run start
        with:
          wait-on: "http://localhost:3001"
      - name: Run tests
        uses: cypress-io/github-action@v4
        env:
# ...
        with:
          browser: chrome
          command: npx cypress run
          working-directory: e2e
          wait-on: "http://localhost:3000, http://localhost:3001"
          spec: |
            cypress/**/*cy.{js,ts}
```

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/42597395/196158321-0dbb8394-359c-427d-b43e-66a1de7ab776.png">

Another issue is that I am not sure if I have to install the dependencies required by cypress as below:

```
sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
```

But I did encounter issues with a lack of dependencies like `xvfb`, `libnss3`, `libasound2`,  so just added this command. While this installation takes a long time (2-3mins) every time when I execute the workflow. Is there any workaround to avoid this installation process?
