### ISSUE TITLE
The Cypress App could not be unzipped when using github action

### ISSUE THREAD

**Issue by chelshaw** [cypress-io/github-action#618]
My action is as follows:
```yml
name: CI
on: push
jobs:
  e2e:
    name: End-to-end
    runs-on: ubuntu-latest
    container: cypress/included:10.11.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build:emulator
          start: npm run start:emulator
        env:
          ...
```

I get the following error on the `Cypress run` step:
```
/usr/bin/docker exec  6e4516bcecc675ae610ccf016dec6495663db5841bc7bdfb59dd6c38bc66988c sh -c "cat /etc/*release | grep ^ID"
/usr/local/bin/npm ci
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /__w/deep-transparency-site/deep-transparency-site/node_modules/cypress
npm ERR! command failed
npm ERR! command sh -c node index.js --exec install
npm ERR! [STARTED] Task without title.
npm ERR! [SUCCESS] Task without title.
npm ERR! [STARTED] Task without title.
npm ERR! The Cypress App could not be unzipped.
npm ERR! 
npm ERR! Search for an existing issue or open a GitHub issue at
npm ERR! 
npm ERR! https://github.com/cypress-io/cypress/issues
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! Error: EACCES: permission denied, mkdir '/root/.cache/Cypress/10.8.0'
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! Platform: linux-x64 (Debian - 11.4)
npm ERR! Cypress Version: 10.8.0
npm ERR! [FAILED] The Cypress App could not be unzipped.
npm ERR! [FAILED] 
npm ERR! [FAILED] Search for an existing issue or open a GitHub issue at
npm ERR! [FAILED] 
npm ERR! [FAILED] https://github.com/cypress-io/cypress/issues
npm ERR! [FAILED] 
npm ERR! [FAILED] ----------
npm ERR! [FAILED] 
npm ERR! [FAILED] Error: EACCES: permission denied, mkdir '/root/.cache/Cypress/10.8.0'
npm ERR! [FAILED] 
npm ERR! [FAILED] ----------
npm ERR! [FAILED] 
npm ERR! [FAILED] Platform: linux-x64 (Debian - 11.4)
npm ERR! [FAILED] Cypress Version: 10.8.0
```
