### ISSUE TITLE
Should "install-command" support "npm ci --ignore-scripts"?

### ISSUE THREAD

**Issue by jnahumphreys** [cypress-io/github-action#619]
I need to pass a custom install script to prevent certain npm prepare scripts running. 

I have followed the docs to pass a [custom install command](https://github.com/cypress-io/github-action#custom-install-command) passing `npm ci --ignore-scripts` to `install-command`. The step fails when attempting to get the cached Cypress binary.

**Full GitHub Action**

```yml
name: Lint Build and Test

on:
  pull_request:
    branches: ["main"]

jobs:
  lint_build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          install-command: npm ci --ignore-scripts

      - name: Lint TypeScript and JavaScript
        run: npm run lint

      - name: Check formatting with Prettier
        run: npm run format:check

      - name: Run Component Tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          component: true
```

**GitHub Action failure feedback for "Install dependencies step"**

```bash
Run cypress-io/github-action@v4
install command command "npm ci --ignore-scripts"
current working directory "/home/runner/work/binaryjim.github.io/binaryjim.github.io"
/opt/hostedtoolcache/node/16.1[7](https://github.com/BinaryJim/binaryjim.github.io/actions/runs/3376738825/jobs/5604824065#step:4:8).1/x64/bin/npm ci --ignore-scripts

added 653 packages, and audited 654 packages in 11s

25[8](https://github.com/BinaryJim/binaryjim.github.io/actions/runs/3376738825/jobs/5604824065#step:4:9) packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/opt/hostedtoolcache/node/16.17.1/x64/bin/npx cypress cache list
No cached binary versions were found.
/opt/hostedtoolcache/node/16.17.1/x64/bin/npx cypress verify
The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /home/runner/.cache/Cypress/[10](https://github.com/BinaryJim/binaryjim.github.io/actions/runs/3376738825/jobs/5604824065#step:4:11).[11](https://github.com/BinaryJim/binaryjim.github.io/actions/runs/3376738825/jobs/5604824065#step:4:12).0/Cypress/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /home/runner/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/runner/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error

----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 10.11.0
Error: The process '/opt/hostedtoolcache/node/[16](https://github.com/BinaryJim/binaryjim.github.io/actions/runs/3376738825/jobs/5604824065#step:4:17).[17](https://github.com/BinaryJim/binaryjim.github.io/actions/runs/3376738825/jobs/5604824065#step:4:18).1/x64/bin/npx' failed with exit code 1
```

If I omit the custom `install-command` the full action runs without error, albeit executing my npm prepare scripts.

Does the `install-command` support npm, specifically as a CI install with `--ignore-scripts flag`?

Thanks in advance
