### ISSUE TITLE
Job hangs after tests pass

### ISSUE THREAD

**Issue by gigamesh** [cypress-io/github-action#620]
I have a job that uses a custom command to run on multiple `.cy` files. The job fans out using the matrix strategy. 

The timeout is set to 20 minutes. Some of the jobs finish, but a couple are mysteriously timing out even after the tests complete. This example has only 2 tests that finish long before 20 minutes:

![image](https://user-images.githubusercontent.com/32403632/199572590-b2093e98-4438-4c27-8c04-bc6b32de9ce9.png)

Here is the cypress step:
```

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          install: false
          working-directory: services/webapp
          record: true
          group: ${{ matrix.file-path }}
          command:
            pnpx cypress run --spec ${{ matrix.file-path }} --record ${{ secrets.CYPRESS_RECORD_KEY
            }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: UTC
        timeout-minutes: 20
```

I was previously running cypress directly and this issue only started after I switched to using `cypress-io/github-action`. I can't determine what is unique about the files that time out. Any ideas would be much appreciated. 🙏

**Comment by jonasberglund** [comment]
Did you find any solution to this issue? I'm having the same problem currently...

**Comment by MikeMcC399** [comment]
@jonasberglund 

> Did you find any solution to this issue? I'm having the same problem currently...

Can you share your full `*.yml` workflow together with the version of Cypress you are using?

**Comment by MikeMcC399** [comment]
@jonasberglund 

It looks like you have 3 test specs. The first two pass and complete. The third (last) one starts and then hangs.

This doesn't look like it's an issue caused by `github-action`.

For further troubleshooting, you could run each of your test specs individually, and see if the third one also hangs up when run on its own.

You could also enable Cypress debug logs in addition:

```yml
  env:
    DEBUG: '@cypress/github-action, cypress:*'
```

I expect that it would need a reproducible example posting online if you want to ask for the Cypress team to get involved in troubleshooting.

It may be that you are hitting hardware limits for the standard GitHub-hosted runners.

Cypress has some recommendations for [hardware dimensioning](https://docs.cypress.io/guides/getting-started/installing-cypress#Hardware)

GitHub offers [Larger runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners)

**Comment by jonasberglund** [comment]
@MikeMcC399 that sounds correct

Yeah, might be more likely then... It runs all perfectly locally but in CI it's been not so good.

I'll try that and see what I can find out. Thank you!

**Comment by gigamesh** [comment]
Feel free to close this issue when it seems resolved. It's no longer relevant for me. thanks :)

**Comment by MikeMcC399** [comment]
@jonasberglund 

Coincidentally there was an announcement today 
https://github.blog/changelog/2023-06-21-github-hosted-larger-runners-for-actions-are-generally-available/

**Comment by TellVanDenBerghMM** [comment]
@jonasberglund 

Did you manage to solve this issue?
I have the same problem.

<img width="800" alt="image" src="https://github.com/cypress-io/github-action/assets/115472774/56bd92e0-e380-4d7a-9344-482d7c17255b">

**Comment by MikeMcC399** [comment]
@TellVanDenBerghMM 

- Did you enable debug logs?

```yml
  env:
    DEBUG: '@cypress/github-action, cypress:*'
```

- Which version of Cypress are you using?
- Which version of `github-action` are you using?

**Comment by TellVanDenBerghMM** [comment]
@MikeMcC399 

Im using Cypress version 12.16.0
and Github action v5

I added the DEBUG and while it's stuck it logs this every 10 seconds.

<img width="1425" alt="image" src="https://github.com/cypress-io/github-action/assets/115472774/f91af60d-6878-4c87-b126-1c81a86d5971">

**Comment by MikeMcC399** [comment]
@TellVanDenBerghMM 
You can compare it to
https://github.com/cypress-io/github-action/actions/runs/5279381053/jobs/9549976962
which shows how github-action normally finishes up.

Do you have video enabled? If yes, then you could try disabling it.

**Comment by TellVanDenBerghMM** [comment]
I disabled the video earlier because I also thought that it got stuck there.
I have some tests that finish normally. But sometimes they get stuck.
Doesn't seems to be consistent.

This is a test that succeded normally.
<img width="797" alt="image" src="https://github.com/cypress-io/github-action/assets/115472774/d0fe8b41-6d16-4557-8a74-12bf72516293">

**Comment by MikeMcC399** [comment]
I don't know how to troubleshoot this further if there are no error messages (apart from the timeout). Hopefully the Cypress.io team will have some ideas.

**Comment by jonasberglund** [comment]
@TellVanDenBerghMM I still have the same issue and it sounds very similar to yours. I also get that they are stuck and it's not consistent, but it seem to be whenever `maxMemRssMb` reaches around 2000...

**Comment by juliette-derancourt** [comment]
I'm facing the same issue with:
- Cypress v12.15.0
- Cypress GitHub action v5.6.1
- Video disabled

It runs all tests successfully, and then stop before printing the test summary (similar to the screenshot in https://github.com/cypress-io/github-action/issues/620#issuecomment-1613228905)

**Comment by MikeMcC399** [comment]
@juliette-derancourt 

It's possible that the reason for the hang may be resource limitations. For troubleshooting you may like to run only a subset of tests and see if they run to completion. If that is the case, then the previous comments in https://github.com/cypress-io/github-action/issues/620#issuecomment-1600520825 may also be applicable to your situation.

**Comment by MikeMcC399** [comment]
@ricardo-dematos 

If you find that using  `browser: 'chrome'` adversely affects how your tests run, then you might like to try 

[Experiments:](https://docs.cypress.io/guides/references/experiments) 

`experimentalMemoryManagement` 
"Enables support for improved memory management within Chromium-based browsers."

**Comment by jodelamo** [comment]
Happens here as well. In my case the whole job times out (after passing!) when adding `firefox` to the browser matrix.

Times out:

```yaml
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, edge, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browser }}
          start: npm test
```

Works:

```yaml
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browser }}
          start: npm test
```
