### ISSUE TITLE
PNPM cache issue

### ISSUE THREAD

**Issue by grahamsmallenroly** [cypress-io/github-action#633]
Hi 

We are using github-action 4.20 with PNPM. We get the following caching error on subsequent runs (once the cache has been created).

Run cypress-io/github-action@v4
  with:
    install: false
    working-directory: typescript/frontend/student
    config: baseUrl=....
    wait-on-timeout: 120
    spec: cypress/e2e/full-regression/cas-checklist/history/**/*
  
    record: false
    component: false
  env:
    CI: false
    NODE_OPTIONS: --max-old-space-size=1638[4](https://github.com/enroly/cas-shield/actions/runs/3427047079/jobs/5709568783#step:7:4)
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
Skipping install because install parameter is false
Error: The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /home/runner/.cache/Cypress/10.9.0/Cypress/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /home/runner/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/runner/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error

----------

Platform: linux-x[6](https://github.com/enroly/cas-shield/actions/runs/3427047079/jobs/5709568783#step:7:6)4 (Ubuntu - 20.04)
Cypress Version: 10.9.0
    at /home/runner/work/cas-shield/cas-shield/node_modules/.pnpm/cypress@10.9.0/node_modules/cypress/lib/errors.js:348:1[7](https://github.com/enroly/cas-shield/actions/runs/3427047079/jobs/5709568783#step:7:7) {
  known: true
}
Error: The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /home/runner/.cache/Cypress/10.[9](https://github.com/enroly/cas-shield/actions/runs/3427047079/jobs/5709568783#step:7:9).0/Cypress/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /home/runner/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/runner/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error

----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: [10](https://github.com/enroly/cas-shield/actions/runs/3427047079/jobs/5709568783#step:7:10).9.0

**Comment by thmsobrmlr** [comment]
@grahamsmallenroly Did you make any progress on this? We're running into the same issue.

**Comment by grahamsmallenroly** [comment]
Hey. I no longer have this issue. We are using the following template

      - name: Cypress run history
        uses: cypress-io/github-action@v4
        with:
          install: false
          working-directory: [...]
          config: baseUrl=[...]
          wait-on-timeout: 120
          spec: |
            cypress/e2e/full-regression/[...]
        env:
          CYPRESS_RECORD_KEY: [...]
          GITHUB_TOKEN: [...]

**Comment by grahamsmallenroly** [comment]
> @grahamsmallenroly Did you make any progress on this? We're running into the same issue.

**Comment by RobbieTheWagner** [comment]
So what was the fix here? I can never seem to get the binary

**Comment by MikeMcC399** [comment]
@RobbieTheWagner 

> So what was the fix here? I can never seem to get the binary

There is a working example shown in the [README](https://github.com/cypress-io/github-action/blob/master/README.md#pnpm). If that doesn't help, then you can open a new issue.

**Comment by RobbieTheWagner** [comment]
The README example does not work. I need to `cypress install` every time, which is fine I guess.

**Comment by MikeMcC399** [comment]
@RobbieTheWagner

> The README example does not work. I need to `cypress install` every time, which is fine I guess.

That is not supposed to be the way it works and the example does work correctly here in this repository. If you could open a new issue and post a link to your workflow I can take a look. It may be a caching issue.

**Comment by MikeMcC399** [comment]
In the example from https://github.com/cypress-io/github-action/blob/master/README.md#pnpm for this monorepo, the references to the directory `examples/basic-pnpm` need to be removed if the workflow is copied elsewhere, otherwise the caching will not work:

```yml
name: pnpm-workflow
on: push
jobs:
  basic-pnpm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm@8
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Cypress run
        uses: cypress-io/github-action@v6
```
