### ISSUE TITLE
Angular + Node.js fails without any output

### ISSUE THREAD

**Issue by dauledk** [cypress-io/github-action#69]
After trying out Cypress on Github actions some months ago, we have today decided to switch from Circle CI to github actions and cypress dashboard. 

But now the github actions does not work 🤷🏾‍♂️

We have a simple Angular + Nodejs server setup, with the server in a folder called `aveiro-server`, and the angular app in the root. The relevant part of the `yml` file thus contains this:

```yml
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install aveiro dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./aveiro-server
      - name: Install & run e2e tests
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
          record: true # Record results to cypress dashboard
          start: npm run -s serve:test & npm run -s start:test --prefix aveiro-server
          wait-on: 'http://localhost:4200'
          config-file: cypress.json
          wait-on-timeout: 180
```

When the above runs, it fails right after the `npm run -s serve:test & npm run -s start:test --prefix aveiro-server` commands. I tried running it on my local machine, and here it works with no problems. 

The only thing I get from the logs is something about an `UnhandledPromiseRejectionWarning`. 

Here is the relevant logs:

![Screenshot 2020-01-24 at 08 50 31](https://user-images.githubusercontent.com/9967422/73053473-22e30880-3e88-11ea-989c-ead0062290b0.png)
