### ISSUE TITLE
Requests from Cypress unable to connect to server

### ISSUE THREAD

**Issue by dylanirlbeck** [cypress-io/github-action#71]
Hi all. So I'm having some trouble getting the Cypress GH action integrated into my project. For some context, I have a monorepo which contains both the front-end client code and back-end server code, with a directory structure like this (leaving out a lot of unnecessary stuff):
```
root/
   frontend/
      cypress/
      cypress.json
      package.json
   server/
      package.json
```

Basically, I have a lot of `cy.request`s throughout my tests, and when I run the GH action I get the following error during the `run cypress tests` step:

```
http://localhost:3001/graphql

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:3001
```

This is a condensed version of my workflow file:

```yml
name: Cypress tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-16.04

    services:
      postgres:
        # postgres specific stuff

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.14.1
        uses: actions/setup-node@v1.1.1
        with:
          node-version: "12.14.1"
      - name: build and start client
        run: |
          cd frontend
          npm install -g yarn
          yarn install
          yarn run build
          yarn start &
      - name: build and start server
        run: |
          cd server
          yarn install
          yarn build
          yarn dev &
      - name: run cypress tests
        uses: cypress-io/github-action@v1.16.1
        with:
          browser: chrome
          config-file: cypress.json
          working-directory: frontend
          wait-on: "http://localhost:3000"
```

The web app is supposed to be running at `localhost:3000` and the server is supposed to be running at `localhost:3001` (with the `/graphql` endpoint). Everything works locally when I do either `cypress open` or `cypress run` after setting up my client and server, so I'm a bit confused on why things break during the workflow.

Any help you all can give me is much appreciated! I'm not sure if this is something Cypress-related (it very well could be due to something I'm doing), but I'm a newcomer to GH actions so I thought I'd try and ask for some help here. Thanks in advance!
