### ISSUE TITLE
wait-on timing out with Vite 4.0 and yarn in Github Actions

### ISSUE THREAD

**Issue by brianaronowitzopen** [cypress-io/github-action#728]
Error:
<img width="1250" alt="Screen Shot 2023-01-17 at 3 13 12 PM" src="https://user-images.githubusercontent.com/113203308/213032842-dbe0e5e0-eac5-468a-af2b-07d5b06c3be9.png">

vite version:
 ```
"vite": "^4.0.0",
```

Github Action YAML:
```
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          working-directory: frontend-studio-software
          build: yarn install
          start: yarn run preview
          wait-on: "http://127.0.0.1:4173/login"
          record: true
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.CYPRESS_WRITE_KEY }}
```

My guess was the vite runner port (4173) isn't being correctly exposed in the runner but not 100% sure.
