### ISSUE TITLE
Excessive HTTP request logging

### ISSUE THREAD

**Issue by ollyrowe** [cypress-io/github-action#729]
### Problem

Is it possible to silence the HTTP logging outputted by Cypress? This is making it difficult to see test pass / failure output. I've tried setting the `quite` option to `true`, however this doesn't seem to have any effect. Any support would be appreciated.

### Image

![image](https://user-images.githubusercontent.com/46567570/213267350-f8046921-95b2-4821-8549-d3c80591c70b.png)

### Workflow File

```
name: Test - E2E

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - src/answers/**

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          build: npm run build
          start: npx serve -s build
          quiet: true
```
