### ISSUE TITLE
Cypress can't take a screenshot "CypressError: cy.screenshot() timed out waiting '30000ms' to complete."

### ISSUE THREAD

**Issue by alexbjorlig** [cypress-io/github-action#73]
When running Cypress with the following config file:

```
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install & run e2e tests
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          record: true # Record results to cypress dashboard
          start: npm run -s cypress:run:ci
          wait-on: 'http://localhost:4200'
          config-file: cypress.json
          wait-on-timeout: 180
```

Cypress can't take any screenshots?

```
     CypressError: cy.screenshot() timed out waiting '30000ms' to complete.
      at Object.cypressErr (http://localhost:4200/__cypress/runner/cypress_runner.js:86207:11)
      at Object.throwErr (http://localhost:4200/__cypress/runner/cypress_runner.js:86162:18)
      at Object.throwErrByPath (http://localhost:4200/__cypress/runner/cypress_runner.js:86194:17)
      at http://localhost:4200/__cypress/runner/cypress_runner.js:72611:21
      at tryCatcher (http://localhost:4200/__cypress/runner/cypress_runner.js:120203:23)
      at http://localhost:4200/__cypress/runner/cypress_runner.js:115344:41
      at tryCatcher (http://localhost:4200/__cypress/runner/cypress_runner.js:120203:23)
      at Promise._settlePromiseFromHandler (http://localhost:4200/__cypress/runner/cypress_runner.js:118139:31)
      at Promise._settlePromise (http://localhost:4200/__cypress/runner/cypress_runner.js:118196:18)
      at Promise._settlePromise0 (http://localhost:4200/__cypress/runner/cypress_runner.js:118241:10)
      at Promise._settlePromises (http://localhost:4200/__cypress/runner/cypress_runner.js:118316:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:4200/__cypress/runner/cypress_runner.js:114928:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:4200/__cypress/runner/cypress_runner.js:114938:10)
      at Async.drainQueues (http://localhost:4200/__cypress/runner/cypress_runner.js:114812:14)
```

I found this [issue](https://github.com/cypress-io/cypress/issues/5016) related issue, regarding codeship CI. 

This issue is only related to github actions. I suspect that the ubuntu version could influence this error?
