### ISSUE TITLE
Can't connect to Chrome "Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 20 seconds."

### ISSUE THREAD

**Issue by alexbjorlig** [cypress-io/github-action#74]
Sometimes when running Cypress github action, with the following config file:

```
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install & run e2e tests
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          record: true # Record results to cypress dashboard
          start: npm run -s cypress:run:ci
          wait-on: 'http://localhost:4200'
          config-file: cypress.json
          wait-on-timeout: 180
```

Cypress can't connect to Chrome, and errors out after 20 seconds?

![Screenshot 2020-01-28 at 15 20 39](https://user-images.githubusercontent.com/9967422/73272014-f578c080-41e1-11ea-8cb9-c7482eb96ba2.png)

What can be done to solve this / improve the stability of Cypress running on Github actions
