### ISSUE TITLE
Unable to locate executable file: npm

### ISSUE THREAD

**Issue by reediculous456** [cypress-io/github-action#764]
I am trying to set up this action for the first time and am getting the following error when it tries to start my application:
```
Error: Unable to locate executable file: npm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

I can run npm commands in all of my other build steps so I'm not sure what's happening.
```yaml
- name: Run Cypress Tests
  uses: cypress-io/github-action@v5
  with:
    install: false
    working-directory: ./packages/cypress
    command: npm run cypress:critical
    start: npm start -- --scope packages/backend
    wait-on: 'http://localhost:4000'
```

**Comment by MikeMcC399** [comment]
@reediculous456 

You might find it helpful to refer to the [README: Debugging](https://github.com/cypress-io/github-action/blob/master/README.md#debugging) section to get more detailed logs to look at, which could help explain what happened when your error message was output.

**Comment by MikeMcC399** [comment]
@reediculous456 

Another option is to fork this repo and run a suitable example workflow to compare it with your workflow. Each of the examples can now be individually triggered since they are set up with `workflow_dispatch`.

[.github/workflows/example-custom-command.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-custom-command.yml) for instance includes the following `yaml` instructions, similar to yours:

```yml
  start:
    # example where instead of forming the default "cypress run ..."
    # the user can specify their own command
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Custom tests 🧪
        uses: ./
        with:
          command: npm run custom-test
          working-directory: examples/custom-command
```

`uses: ./` is equivalent to `uses: cypress-io/github-action@master` so that the examples always run with the latest code, even if it has not yet been released.

**Comment by reediculous456** [comment]
I think I have this figured out now. I have a weird setup because I am using Lerna and my file tree looks like this:
```
packages
    ├── client
    ├── server
    └── cypress
```
so I needed to use this configuration:
```yaml
- name: Run Cypress Tests
    uses: cypress-io/github-action@v5
    with:
      install: false
      project: ./packages/cypress
      command: npm run cypress:critical
      start: npm run start:prod -- --scope server
      wait-on: 'http://localhost:4000, http://nginx'
```
