### ISSUE TITLE
Configuration of Github integration.

### ISSUE THREAD

**Issue by alexbjorlig** [cypress-io/github-action#77]
After moving our cypress tests from Circle CI to Github actions, we don't receive any of the sweat Cypress comments with failed tests on our pull requests. Do I need to provide anything special for the Github integration to work?

**Comment by jennifer-shehane** [comment]
This is due to a known issue when CI providers build special Pull Request builds outlined in our private repo here: https://github.com/cypress-io/cypress-services/issues/2107

To briefly summarize, some CI providers, in some circumstances do what are called "Pull Requests builds". Pull Requests builds are useful in answering the question “What if this PR merged into target (base) branch”. Builds solely made off of the single commit are not enough to answer this question, because while the PR is being developed some other commits could be made to the base branch.

The CI provider then generates a build for the merge of the head branch with the base branch specified in the pull request - leading to commit messages that look like like

```
Merge 2f5a7afe97740f99f5c4f5e40a3d7347bc058b30 into 1f40d78961e5d268ac072dca86176f9fb2aa7b13
```

Because the SHA of this build is not actually part of any of the code of the PR, Cypress does not associate the build correctly to the PR to run status checks. 

---

Please provide an example of your GitHub Actions configuration so we can set up an example repo reproducing this behavior to investigate.

**Comment by alexbjorlig** [comment]
Github actions configuration looks like this:

```
jobs:
  e2eTests:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install & run e2e tests
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          record: true # Record results to cypress dashboard
          start: npm run -s cypress:run:ci
          wait-on: 'http://localhost:4200'
          config-file: cypress.json
          wait-on-timeout: 180
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
```
