### ISSUE TITLE
Example test-personal-site outdated

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#774]
## Problem description

The example website [test-personal-site](https://github.com/bahmutov/test-personal-site) listed in the [README: More examples](https://github.com/cypress-io/github-action/blob/master/README.md#more-examples) section is outdated. There have been no changes made on this site for the past 2 years.

It uses:

- Cypress 6.4.0
- npm lockfileVersion 1 from npm v6 for Node.js 14 (see https://nodejs.org/en/download/releases/)
- actions/checkout@v2
- cypress-io/github-action@v2
- ubuntu-20.04

[Cypress 6.4.0](https://docs.cypress.io/guides/references/changelog#6-4-0) was released in Feb 2021 so is 2 years old.
Node.js 14 enters End-of-life on April 30, 2023.
Due to GitHub deprecations the site will fail after May 31, 2023.

The repo owner stated that he does not want to update the repo.

## Suggested fix

Remove the example website [test-personal-site](https://github.com/bahmutov/test-personal-site) from the [README: More examples](https://github.com/cypress-io/github-action/blob/master/README.md#more-examples) section.

**Comment by MikeMcC399** [comment]
I suggest to review all [README: More examples](https://github.com/cypress-io/github-action/blob/master/README.md#more-examples) and to make a bulk change if necessary.

**Comment by MikeMcC399** [comment]
The workflow https://github.com/bahmutov/test-personal-site/blob/main/.github/workflows/ci.yml does not demonstrate any aspect which is not covered by existing examples.

- All examples now include the event trigger `workflow_dispatch` in them.
- [example-cron.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-cron.yml) includes an example of `cron` usage

```yml
name: ci
# specify the events this workflow should run on
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  # manual button click from the GitHub UI
  workflow_dispatch:
  # pushing commit to the main branch
  push:
    branches:
      - main
  # test site every night
  schedule:
      - cron: '0 4 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
```
