### ISSUE TITLE
Webpack is not installed

### ISSUE THREAD

**Issue by manskron** [cypress-io/github-action#78]
When trying to trigger our build-step which uses webpack, I get the error `webpack not installed`.
This is what the workflow file looks like:
```
name: Cypress gh action test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: yarn build-dev
          env: BABEL_ENV=client
          browser: chrome
          headless: true
          start: yarn start-dev
          wait-on: 'http://localhost:3000'
```
I've tried using the full path `./node_modules/.bin/webpack` in our build script, but without success.
