### ISSUE TITLE
Component tests README section incomplete

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#784]
## Current situation

The section in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) for Component tests shows only a partial example and combines this with E2E testing.

The index shows:

- Run E2E and [Component tests](https://github.com/cypress-io/github-action/blob/master/README.md#component-tests)

which links to a section with the following contents:

---

### Component tests

You can run [Cypress component tests](https://on.cypress.io/component-testing) in a job separate from E2E tests by adding `component: true`:

```yml
- name: Run E2E tests 🧪
  uses: cypress-io/github-action@v5

- name: Run Component tests 🧪
  uses: cypress-io/github-action@v5
  with:
    # we have already installed everything
    install: false
    # to run component tests we need to use "component: true"
    component: true
```

See the example project [component-test](examples/component-tests/) and the [example-component-test-workflow](.github/workflows/example-component-test.yml) for more details.

---

The example project [examples/component-tests/](examples/component-tests/) runs a pure component test without E2E. The [current example text in the README](https://github.com/cypress-io/github-action/blob/master/README.md#component-tests) is not a complete setup for component testing.

## Suggested change

Add a separate complete example for Component Testing and clearly separate it from the example about running component testing in combination with E2E testing.

Place the new complete example for Component Testing near the top in the order of listing. Since the release of [Cypress 11.0.0](https://docs.cypress.io/guides/references/changelog#11-0-0) Component Testing is Generally Available (GA) and no longer in beta status, it could be given a higher level of visibility on a par with E2E testing.
