### ISSUE TITLE
Action all the sudden reporting job status using "(merge)" suffix 

### ISSUE THREAD

**Issue by mellis481** [cypress-io/github-action#805]
I have a number of workflow jobs that use `cypress-io/github-action` which I have tied to branch protection status checks. Here is an example of a job:

```
- name: Cypress end-to-end tests
  uses: cypress-io/github-action@v4
  with:
    wait-on: 'https://localhost:9000/index.js'
    start: npm run start:local
    config-file: cypress/config/e2e.ts
    record: true
    install: false
    group: 'E2E'
    ci-build-id: ${{ needs.prepare.outputs.uuid }}
    tag: 'pull-request'
```

The name of the status check that I previously set for this job is "cypress: E2E" which uses the `group` property of the action.  This has been working fine.  All of the sudden, however, the previous status checks are not reporting.  Instead, I'm seeing status checks being reported that have my expected checks, but with a "(merge)" suffix. eg:

![image](https://user-images.githubusercontent.com/39313898/220199955-feb6db88-dd56-412c-9f16-15b3f99f8b54.png)

Why is this happening?

**Comment by mellis481** [comment]
I manually re-ran the workflow and this time it reported the status checks without the "(merge)" suffix.

**Comment by MikeMcC399** [comment]
@mellis481

Was this just a one-time occurrence or are you having repeatable issues? You would need to examine the workflow logs for the run which hung in order to see what might have gone wrong. If you find a need to re-run your workflow with debug logging enabled, then you can add:

```yml
env:
  DEBUG: '@cypress/github-action, cypress:*'
```

Your post shows that you are using `cypress-io/github-action@v4` which is effectively [v4.2.2](https://github.com/cypress-io/github-action/releases/tag/v4.2.2) published on Nov 28, 2022 and unchanged since then.

To take advantage of on-going improvements and bug-fixes you should consider migrating to `cypress-io/github-action@v5` which is the latest version available.

Which version of Cypress are you using?

**Comment by mellis481** [comment]
v4.

This happened multiple times. I pushed an empty commit to the PR after seeing the problem initially and the corresponding workflow run again had the "(merge)" suffix. It wasn't until I manually re-ran the workflow where the statuses were reported without the "(merge)" suffix.

**Comment by MikeMcC399** [comment]
@mellis481 

Is your screenshot from the pull request status on GitHub? Are you using a GitHub hosted runner or self-hosted? What do you have in your workflow event trigger section `on:`? I suspect that `merge` is a GitHub PR status. In open PRs in this repository I see (pull_request) where you see (merge):

![image](https://user-images.githubusercontent.com/66998419/220369478-65fba871-eec9-436f-971a-d1c2aa53978a.png)

> v4.

I was actually asking about the version of Cypress in use, like 9.7.0 or 12.6.0 for instance. That is just for background information.

**Comment by mellis481** [comment]
> Is your screenshot from the pull request status on GitHub? 

Yes.

> Are you using a GitHub hosted runner or self-hosted?

Self-hosted.

> What do you have in your workflow event trigger section `on:`? I suspect that `merge` is a GitHub PR status. In open PRs in this repository I see (pull_request) where you see (merge):

```
on:
  pull_request:
    branches:
      - master
```

> I was actually asking about the version of Cypress in use, like 9.7.0 or 12.6.0 for instance. That is just for background information.

10.4.0.

**Comment by MikeMcC399** [comment]
@mellis481 

Thanks for the additional information! It doesn't look like this is an issue caused by `cypress-io/github-action`. Again, I think you would need to dig into your log files to gain more insight.

**Comment by MikeMcC399** [comment]
@mellis481 

One more thought: when I hover over the GitHub icon in my screenshot it says "@github-actions generated this status".

![image](https://user-images.githubusercontent.com/66998419/220425492-4db558d8-7bdd-4652-9157-6fa3cad0aad1.png)

In your screenshot I can see only Cypress icons, so there is a difference.

Your issue has now been assigned to a Cypress engineer, so hopefully he will be able to chip in with more expertise than I have!

**Comment by mellis481** [comment]
@MikeMcC399 Thanks! Yes, when I hover over the Cypress icons the popover says "@cypress generated status".

I'm not sure if it was clear from my workflow code, but our workflow job is parallelized and integrated with Cypress Dashboard.

**Comment by flotwig** [comment]
@mellis481 I think I concur with @MikeMcC399 that this isn't related to the GitHub Action, since these status checks come directly from Cypress Cloud itself.

I spoke with @davidr-cy and he showed me that the relevant code paths that generate these status checks haven't changed in almost 2 years. `(merge)` is added if it's detected that the commit message is generated from a merge commit, and our logic around that hasn't changed.

So now we are wondering if GitHub is sending us different metadata all of a sudden, causing the change in behavior you're seeing. Could you please share your Cloud organization ID so we can debug further? You can find it under "Organization ID" inside of the Cypress Cloud.

**Comment by mellis481** [comment]
c5365dbf-9c5b-4769-a95d-130d46f70241

**Comment by flotwig** [comment]
@mellis481 can you try switching to `on: push` instead of `on: pull_request` and seeing if it resolves the issue? It's what the docs recommend, for reasons explained there: https://github.com/cypress-io/github-action#record-test-results-on-cypress-cloud

**Comment by mellis481** [comment]
@flotwig I'm confused with the recommendation in the article you shared. Those triggers are used in different use cases.  `on: pull_request` should be used for PR gate workflows. `on: push` should be used for workflows that should be run when a PR is merged.

**Comment by mjhenkes** [comment]
[on push](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push), happens whenever you push changes to a branch, be it the feature branch, master or main

[on pull_request](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) happens when 'the workflow runs when a pull request is opened or reopened or when the head branch of the pull request is updated'.

So after you've created a pull request, `on push` and `on pull_request` will both happen whenever you update the head branch.

According to the article the information provided by `on push` is more accurate than `on pull_request` but I haven't double checked that myself.

It's worth a shot to try though right? 🤷‍♂

**Comment by mellis481** [comment]
@mjhenkes The example workflow in the article you shared doesn't specify a branch so it will run the Cypress action on any pushed commit to any branch. That's basically the only scenario I can think of wherethe `push` and `pull_request` triggers could be used interchangeably.

In my situation (which is exceedingly common I can only assume), I only want to run Cypress tests for 1. PRs 2. against certain branches (in my case, just one: `master`). This means I _have_ to use the `pull_request` trigger which will run when there is "activity on a pull request in the workflow's repository occurs" (on the `master` branch).  If I were to use the `push` trigger like you recommend, the only way it would run would be is if I changed the branch targeted by the trigger from `master` to the branch the PR is for.  And then for the next PR, the workflow would need to target that PR branch name. That, of course, isn't how PR gate workflows would ever work.

**Comment by MikeMcC399** [comment]
- It looks like this issue is also related to a previous conversation in https://github.com/cypress-io/github-action/issues/124 involving @mellis481

**Comment by mellis481** [comment]
@MikeMcC399 As you can see, I contribute at the end of that thread. I didn't include it in my original post listing code, but I do include COMMIT_MESSAGE which is the solution Gleb gives in that thread.  Here is my whole job FWIW:

```
- id: cypress-e2e-tests
  name: Cypress end-to-end tests
  uses: cypress-io/github-action@v4
  with:
    wait-on: 'https://localhost:9000/ui/vtx-ui-root-app/index.js'
    start: npm run start:local
    config-file: cypress/config/e2e.ts
    record: true
    install: false
    group: 'E2E'
    ci-build-id: ${{ needs.prepare.outputs.uuid }}
    tag: 'pull-request'
  env:
    NODE_TLS_REJECT_UNAUTHORIZED: 0
    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
    COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
```
