### ISSUE TITLE
Output summary results

### ISSUE THREAD

**Issue by rajeshshou** [cypress-io/github-action#810]
Is it possible to support setting the summary results in the output of the github so they can be used in other jobs?

As a workaround, I have to parse the results from junit xml which is fine but it would be great to just consume it from cypress
github action as cypress github is already parsing it.

**Comment by MikeMcC399** [comment]
@rajeshshou

The action uses "`core.summary`	Accessible using environment file `GITHUB_STEP_SUMMARY`". See [Workflow commands for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary) and [Adding a job summary](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary) which gives more detail on what is being used.

The `GITHUB_STEP_SUMMARY` is lost when the workflow moves to the next step, so what you are asking for would need to be added to the action to preserve the summary details somewhere else.

**Comment by rajeshshou** [comment]
@MikeMcC399  Exactly. One possible and easy solution is adding it to output similar to what is done for dashboard url here.
https://github.com/cypress-io/github-action/blob/master/index.js#L759

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

**Comment by MikeMcC399** [comment]
@rajeshshou 

If you have a tested solution for your request you could submit this as a Pull Request, or are you requesting that somebody else implement your idea?

**Comment by carvalhogsc** [comment]
o problema não seria aqui?

https://github.com/cypress-io/github-action/blob/c6dd77a3b45cf0b37e980c468202755765df3fb0/index.js#L16

const { SUMMARY_ENV_VAR } = require('@actions/core/summary')

**Comment by mihaisee** [comment]
@MikeMcC399 I have [this PoC PR](https://github.com/mihaisee/github-action/pull/2). 
Can you take a quick look and let me know if I'm on the right path with this, before creating a PR in this project?
Thanks!

**Comment by Dale-777** [comment]
please can this feature be reviewed and approved

**Comment by airtonix** [comment]
Not sure why you're mentioning `GITHUB_STEP_SUMMARY` and this in the same solution: 

> Is it possible to support setting the summary results in the output of the github so they can be used in other jobs?

I'm not sure you can utilise the information printed from one job into `GITHUB_STEP_SUMMARY` in another job.

What you really wanted was `GITHUB_OUTPUT`

```yaml


jobs:
  One:
    runs-on: ubuntu-latest

	outputs:
	  Foo: steps.some-action.outputs.Something

    steps:
      - uses: actions/checkout@v3
      - name: get something
        id: some-action
        run: |
          echo "Something=aye" >> "$GITHUB_OUTPUT"

  Two:
    runs-on: ubuntu-latest

	outputs:
	  Bar: steps.another-action.outputs.Thing

    steps:
      - uses: actions/checkout@v3
      - name: get another thing
        id: another-action
        run: |
          echo "Thing=lmao" >> "$GITHUB_OUTPUT"

  Three:
    runs-on: ubuntu-latest

	needs: 
      - One
      - Two

    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{ needs.One.outputs.Foo }}"
          echo "${{ needs.One.outputs.Bar }}"
```


If how ever you meant to say "Workflows" instead of "Jobs", then you really need define what the circumstances are.

if you have separate workflow files that need outputs from other workflow files, then you should probably be thinking about abstracting those workflow files into callable workflows that accept inputs.
