### ISSUE TITLE
wait-on issues with Node.js 18

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#811]
## Problem description

With the GitHub migration of runners to use Node.js 18 as default on Feb 18, 2023, some workflows using the built-in `wait-on` parameter of [cypress-io/github-action](https://github.com/cypress-io/github-action) ~~are now~~ were failing: for example, https://github.com/cypress-io/github-action/issues/760 with `Error: connect ECONNREFUSED 127.0.0.1:4200.` Edit: no longer failing due to workaround implementation.

This affects development webservers which are not listening on both IPv4 and IPv6. Some, like vite, can be set to start and listen on `0.0.0.0` which solves the issue. Others don't seem to be so flexible.

It also affects the alternate method of using [start-server-and-test](https://github.com/bahmutov/start-server-and-test) as an argument to the built-in `wait-on` parameter. Due to the fact that [start-server-and-test](https://github.com/bahmutov/start-server-and-test) depends on the separate npm module [wait-on](https://github.com/jeffbski/wait-on) and this external `wait-on` also trips up on Node.js 18 in certain configurations, it also becomes a problem for [start-server-and-test](https://github.com/bahmutov/start-server-and-test).

Workarounds can be found, such as using the IPv6 loopback address `::1` instead of the more generic `localhost` hostname. The workarounds differ depending on the dev webserver and the environment it is being run under.

## Questions

1. Is it necessary for [cypress-io/github-action](https://github.com/cypress-io/github-action) to adapt to dev webservers which are not listening on both IPv4 and IPv6, or is the onus on the dev webserver providers to make changes and on users to find suitable workarounds?
2. If changes are made to [cypress-io/github-action](https://github.com/cypress-io/github-action), is the older [got](https://github.com/sindresorhus/got) v11 still the right choice for [src/ping.js](https://github.com/cypress-io/github-action/blob/master/src/ping.js)?
3. Should [cypress-io/github-action](https://github.com/cypress-io/github-action) migrate to the current [got](https://github.com/sindresorhus/got) ~~v12~~ v13 version? This is a breaking change due to the migration from CommonJS to native ESM.
4. Or should another technology be used to check if a webserver is running?

**Comment by MikeMcC399** [comment]
# Workarounds

This is a suggestion for workarounds when using the built-in `wait-on` parameter of `cypress-io/github-action@v5` in Node.js 18 environments on GitHub:

1. Remove `wait-on` parameter completely as a test and possible permanent solution. Some workflows do not need this step at all.
2. Find out from documentation or community interaction if your development server can be started so that it listens to both IPv4 and IPv6 network traffic. Implement changed start-up if available.
3. Instead of waiting for `localhost`, wait for the IPv4 loopback address `127.0.0.1` or the IPv6 loopback address `::1`. It will be the opposite to the one mentioned in the connect error message.
4. Use an alternate dev webserver which listens on both IPv4 and IPv6.

Below are specific examples:

## Angular

Angular 15 built with `ng new angular-test` (see [Angular: Setting up the local environment and workspace](https://angular.io/guide/setup-local)).

```yml
      - name: Test
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          wait-on: 'http://localhost:4200'
```

fails on GitHub `ubuntu-22.04`, `windows-2022` and `macos-12` with

`Error: connect ECONNREFUSED 127.0.0.1:4200`

Workaround: use the IPv6 loopback address `::1` as in `wait-on: 'http://[::1]:4200'` instead of using `localhost`.

At this time the literal IPv6 address `::1` cannot be used in `config: baseUrl=http://[::1]:4200` (see issue https://github.com/cypress-io/cypress/issues/25950), so `baseUrl` has to be unchanged using `localhost` in cypress config.

```yml
      - name: Test
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          wait-on: 'http://[::1]:4200'
```

## Vite

Vite v3 & v4 built with `npm create vite` with options Vanilla and JavaScript (see [Vite: Getting Started](https://vitejs.dev/guide/)).

```yml
    - name: Test
      uses: cypress-io/github-action@v5
      with:
        wait-on: http://localhost:5173
        start: npm run dev
```

fails on GitHub `ubuntu-22.04`, `windows-2022` and `macos-12` with

`Error: connect ECONNREFUSED 127.0.0.1:5173`

Workaround: start server with `npx vite --host` (server then listens on `0.0.0.0`):

```yml
    - name: Test
      uses: cypress-io/github-action@v5
      with:
        wait-on: http://localhost:5173
        start: npx vite --host
```
