### ISSUE TITLE
Could not run Firefox browser

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#84]
For workflow like this
```yml
name: Firefox

on: push

jobs:
  # hmm, seems when using container (that should have FF installed)
  # Cypress cannot find Firefox. This job just prints browser versions
  check-firefox:
    runs-on: ubuntu-latest
    # https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:node13.6.0-chrome80-ff72
    steps:
      # help us who how we are running in the container
      - run: whoami
      - run: id
      - run: google-chrome --version
      - run: firefox --version
```

Getting the following error

```
whoami
root

id
uid=0(root) gid=0(root) groups=0(root)

google-chrome --version
Google Chrome 80.0.3987.87 

firefox --version
Running Firefox as root in a regular user's session is not supported.  ($HOME is /github/home which is owned by uid 1001.)
##[error]Process completed with exit code 1.
```

**Comment by bahmutov** [comment]
testing in https://github.com/cypress-io/cypress-example-kitchensink/pull/361

**Comment by bahmutov** [comment]
asked the question on GH forum https://github.community/t5/GitHub-Actions/How-to-run-action-as-a-non-root-user/m-p/45561

**Comment by Bkucera** [comment]
Solved, this solution works:

```yml
container:
	image: cypress/browsers:node13.6.0-chrome80-ff72
	options: --user 1001
```
