### ISSUE TITLE
set env vars to use in tests.

### ISSUE THREAD

**Issue by th-m** [cypress-io/github-action#85]
I have tests that need to run behind a password protected login. I cannot find documentation on how the github action works, and how / where env variables are injected. 

When running from the github action I get:

` CypressError: cy.type() can only accept a String or Number. You passed in: 'undefined'`  

referring to this code: 
```js
  cy.get('#username').type(Cypress.env('TEST_USER'));
  cy.get('#password').type(Cypress.env('TEST_USER_PASSWORD'));
```

```
name: End-to-end tests
on: [push]
# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     # runs in utc time, so this is 8, 11, and 3pm mt time
#     - cron: '0 15,18,22 * * *'
jobs:
  test:
    name: spec tests
    runs-on: macos-latest
    strategy:
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          record: true
          parallel: true
          group: 'Actions example'
          start: npm run start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:9001'
          # wait for 6 minutes for the server to respond
          wait-on-timeout: 360
        env:
          TEST_USER: ${{ secrets.TEST_USER }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} 
```

**Comment by jennifer-shehane** [comment]
Is your `cypress.env.json` file is checked into source control?

**Comment by th-m** [comment]
@jennifer-shehane no. We were hoping to not check passwords into version control.

**Comment by th-m** [comment]
@jennifer-shehane maybe this should be marked as a feature request?

**Comment by jennifer-shehane** [comment]
@th-m How are you passing the Cypress env var then into your CI environment then?

**Comment by andersr** [comment]
I am experiencing the same issue.  My current config is as per below

```yaml
name: End-to-end tests
on:
  [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Cypress run
        uses: cypress-io/github-action@v1.16.1
        with:
          build: yarn build
          start: yarn serve:test
          wait-on: 'http://localhost:5000'
        env:
          CYPRESS_BASE_URL: 'http://localhost:5000/'
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
          CYPRESS_TEST_USER_EMAIL:  ${{ secrets.TEST_USER_EMAIL }}
          CYPRESS_TEST_USER_PASSWORD:  ${{ secrets.TEST_USER_PASSWORD }}
```

However, the cypress command run by this action appears to be setting env to false:
According to the logs:

```sh
Cypress test command: npx cypress run --config-file cypress.json --env false
/usr/local/bin/npx cypress run --config-file cypress.json --env false
```

How can one update this command so that it looks for env vars?

**Comment by andersr** [comment]
Was able to get `env` set to true by over-riding it in the `with` block.
 
```yaml
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          env: true
        env:
          CYPRESS_BASE_URL: 'http://localhost:5000/'
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
          CYPRESS_TEST_USER_EMAIL:  ${{ secrets.TEST_USER_EMAIL }}
          CYPRESS_TEST_USER_PASSWORD:  ${{ secrets.TEST_USER_PASSWORD }}
```
However, still not able to get Cypress to detect the actual env var values (eg

**Comment by bahmutov** [comment]
Yes looks like a bug where with:env block clobbers outside normal env variables

**Comment by devsrihari4** [comment]
Hi, using the below workflow I am unable to get password value from GitHub secrets.

name: Run tests
on:
  push:
    branches:
      - 'master'
jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        machines: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: 'Actions example'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CY_PASS: ${{secrets.CY_PASS}}

**Comment by ahsanfarooq3423** [comment]
How do we access these environment variables inside the cypress code ?

**Comment by humoyun91** [comment]
Hi,
Did anybody tried [this](https://github.com/cypress-io/github-action#env) syntax. It worked for me:

```
name: Cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run with env
        uses: cypress-io/github-action@v2
        with:
          env: host=api.dev.local,port=4222
```

**Comment by gwvt** [comment]
I had a similar issue in using secrets for some env vars and needing to pass in `configFile=ci` with the `cypress run` command. The following worked for me, to set `env: configFile=ci` in the `with` block and the env vars requiring secrets in an `env` block:

``` yaml
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: node
      uses: actions/setup-node@v3
      with:
        node-version: '16.15.0'
        cache: 'npm'

    - name: install
      run: npm ci

    - name: e2e
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npx vite preview
        env: configFile=ci
      env:
        CYPRESS_SECRET_1: ${{ secrets.CYPRESS_SECRET_1 }}
```
