### ISSUE TITLE
Cypress not found by yarn

### ISSUE THREAD

**Issue by antarr** [cypress-io/github-action#864]
I'm trying to configure a rails project that uses cypress to run on PR's using github actions. I'm getting an error with yarn not finding the cypress package. How can I fix this?

### error
```
npm WARN exec The following package was not found and will be installed: cypress@12.9.0
┌─────────┬───────────────────┐
│ version │ last used         │
├─────────┼───────────────────┤
│ 12.9.0  │ a few seconds ago │
└─────────┴───────────────────┘
start server "bundle exec rails s -e test -p 5017 command "bundle exec rails s -e test -p 5017"
current working directory "/home/runner/work/cubie/cubie"
waiting on "http://localhost:5017" with timeout of 60 seconds
/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/bundle exec rails s -e test -p 5017
Your RubyGems version (3.1.6) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
=> Booting Puma
=> Rails 5.2.8.1 application starting in test 
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Puma version: 6.2.1 (ruby 2.7.8-p225) ("Speaking of Now")
*  Min threads: 0
*  Max threads: 5
*  Environment: test
*          PID: 26[32](https://github.com/Organization/cubie/actions/runs/4668943745/jobs/8266714503#step:9:33)
* Listening on http://0.0.0.0:5017/
Use Ctrl-C to stop
Error: Cannot find module 'cypress'
Require stack:
- /home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js
```

### .github/workflows/ci.yml
```yaml
# Run rspec tests on push to master and pull requests to master using mysql as the database
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    env:
      RAILS_ENV: test
      DATABASE_URL: mysql2://root:password@127.0.0.1:3306/cubie_test
      CYPRESS_DATABASE_URL: mysql2://root:password@127.0.0.1:3306/cubie_e2e
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: cubie_test
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Configure database
        run: |
          gem install foreman --no-document
          cp config/ci.database.yml config/database.yml
          bundle exec rake db:create db:schema:load db:migrate
      - name: Save Videos and Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: |
            /home/runner/work/cubie/cubie/spec/cypress/videos
            /home/runner/work/cubie/cubie/spec/cypress/screenshots
      - name: Run Rspec Tests
        run: |
           bundle exec rspec spec --format progress
      - name: Install yarn packages in /spec
        run: |
          cd spec
          yarn install
          cd ..
      - name: Save Videos and Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
      # - name: Run Rspec Tests
      #   working-directory: ./
      #   run: |
      #     bundle exec rspec spec --format progress
      #     foreman start -f Procfile.ci
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          project: ./spec
          start: bundle exec rails s -e test -p 5017
          wait-on: http://localhost:5017
```
