### ISSUE TITLE
Webpack Compilation Error / Module not found

### ISSUE THREAD

**Issue by greendrake** [cypress-io/github-action#875]
**Workflow:**

```
name: Cypress Test

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/included:cypress-12.4.0-node-16.18.1-chrome-109.0.5414.74-1-ff-109.0-edge-109.0.1518.52-1
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
    # Build it....

  ui-chrome-test:
    runs-on: ubuntu-latest
    container: cypress/included:cypress-12.4.0-node-16.18.1-chrome-109.0.5414.74-1-ff-109.0-edge-109.0.1518.52-1
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1]
    steps:
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v5.6.1
        with:
          # we have already installed all dependencies above
          install: false
          browser: chrome
```

**Error:**
```
Error: Webpack Compilation Error
./cypress/support/e2e.js
Module not found: Error: Can't resolve 'cypress-plugin-stripe-elements' in
```
The module `cypress-plugin-stripe-elements` is properly installed as a dev dependency of the project. Furthermore, running the same Cypress container locally works just fine, all tests run and pass:

```
#!/bin/bash
DIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
docker run -it --dns 172.17.0.1 --rm -v $DIR:/e2e -w /e2e -e CYPRESS_VIDEO=false -e CYPRESS_screenshotOnRunFailure=false cypress/included:cypress-12.4.0-node-16.18.1-chrome-109.0.5414.74-1-ff-109.0-edge-109.0.1518.52-1 --browser chrome

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.4.0                                                                         │
  │ Browser:        Chrome 109 (headless)                                                          │
  │ Node Version:   v16.18.1 (/usr/local/bin/node)                                                 │
```

One difference that might cause the GA run fail is the `node` binary location:
```    ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.4.0                                                                         │
  │ Browser:        Chrome 109 (headless)                                                          │
  │ Node Version:   v16.16.0 (/__e/node16/bin/node)                                                │
```

Why would the same container use different `node` binaries when running as a standalone container (locally) and from GA?

Why does the error occur in GA only?
