### ISSUE TITLE
Github action not starting Vite server properly

### ISSUE THREAD

**Issue by lucasfelber** [cypress-io/github-action#879]
I have the following .yml file:

```
name: Cypress Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./app
        run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./app
          build: yarn build
          start: yarn dev
          wait-on: 'http://localhost:5173'
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The Vite server start properly but for some reason it still times out when waiting on it.

![image](https://user-images.githubusercontent.com/56022081/233837056-c4d0237d-abc2-4597-8834-77ba97fb853e.png)

**Comment by MikeMcC399** [comment]
@lucasfelber 

Please check out

- [README: `wait-on` with Node.js 18+](https://github.com/cypress-io/github-action/blob/master/README.md#wait-on-with-nodejs-18)
- https://github.com/cypress-io/github-action/issues/811#issuecomment-1450704835

and let us know if that resolves your issue.

## Vite

Vite v3 & v4 built with `npm create vite` with options Vanilla and JavaScript (see [Vite: Getting Started](https://vitejs.dev/guide/)).

```yml
    - name: Test
      uses: cypress-io/github-action@v5
      with:
        wait-on: http://localhost:5173
        start: npm run dev
```

fails on GitHub `ubuntu-22.04`, `windows-2022` and `macos-12` with

`Error: connect ECONNREFUSED 127.0.0.1:5173`

Workaround: start server with `npx vite --host` (server then listens on `0.0.0.0`):

```yml
    - name: Test
      uses: cypress-io/github-action@v5
      with:
        wait-on: http://localhost:5173
        start: npx vite --host
```
