### ISSUE TITLE
Cypress screenshots are only 1050x888 and not 1920x1080

### ISSUE THREAD

**Issue by alexbjorlig** [cypress-io/github-action#88]
I am struggling with low-resolution video and images when using the cypress dashboard.

When I download the images, I can never get a resolution above 1050x888, and often it looks like the resolution is actually worse. The best result I can get is when running `cy.screenshot({log: true})`, but the size is never above 1050x888.

It's a shame, because one of the reasons I could convince our team to prioritize investing in Cypress was the amazing video/screenshot support, and I don't want people to laugh about this super low resolution 😥

It's especially bad when a test fails. The error-screenshot is still 1050x888, but the cypress test runner takes up such a large amount of the screenshot, so the part with the app is _really_ low resolution.

Something interesting to note here, is that in the top right corner the size is listed as 1920x1080 🤔?

I don't really know anything about XVFB servers and such, but I'm willing to help if possible 🤓

**Details**

CI: Github actions
OS: Linux Debian - 10.2
Browser: Chrome 80.0.3987.87
Cypress: v4.0.1
Headless: false

**cypress.json**
```
{
    "baseUrl": "http://localhost:4200/",
    "watchForFileChanges": true,
    "testFiles": "e2e/**/*.spec.ts",
    "projectId": "mpq3yb",
    "pluginsFile": "cypress/plugins/index.js",
    "viewportWidth": 1920,
    "viewportHeight": 1080,
    "defaultCommandTimeout": 40000,
    "env": {
        "NODE_ENV": "test"
    }
}
```

**e2e-tests.yml**
```
jobs:
  e2eTests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node13.6.0-chrome80-ff72
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install aveiro dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./aveiro-server
      - name: Install & run e2e tests
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          record: true # Record results to cypress dashboard
          parallel: false
          start: npm run -s cypress:run:ci
          wait-on: 'http://localhost:4200'
          config-file: cypress.json
          wait-on-timeout: 300
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
```

**cypress/plugins/index.js**
```js
const cypressTypeScriptPreprocessor = require('./cy-ts-preprocessor');

module.exports = on => {
    on('file:preprocessor', cypressTypeScriptPreprocessor);
    // Workaround described here: https://github.com/cypress-io/cypress/issues/6210#issuecomment-583269127
    on('before:browser:launch', (browser, launchOptions) => {
        if (browser.name === 'chrome' && browser.isHeadless) {
            console.log('TRUE');
            launchOptions.args.push('--window-size=1280,720');

            return launchOptions;
        }
    });
};
```

**spec file**
```
cy.screenshot({log: true});
```

**output from above**
```
  (Screenshots)

  -  /__w/eddystone/eddystone/cypress/screenshots/e2e/CRUD-operations/account.spec.ts     (1050x888)
```
