### ISSUE TITLE
Replace dashboardUrl using a Cypress Cloud oriented name

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/github-action#909]
This is an enhancement suggestion related to the GitHub step output `dashboardUrl` which is used when `github-action` records in the Cypress Cloud, which used to be called Cypress Dashboard.

## Suggested change

1. Add a new parameter reflecting Cypress Cloud instead of Cypress Dashboard, for example `cloudRunUrl`
2. Declare `dashboardUrl` as deprecated and retain its functionality until a future major version of `github-action` is released
3. Update documentation and Cypress 12.x examples accordingly

## Reason for change

- Using the name `dashboardUrl` is confusing when Cypress Dashboard has been renamed to Cypress Cloud.

- This follows on from PR https://github.com/cypress-io/github-action/pull/907 started by @mattvCypress and completed by @elylucas.

## Background

- The [README > Outputs](https://github.com/cypress-io/github-action#outputs) section states:

"This action sets a GitHub step output `dashboardUrl` if the run was recorded on [Cypress Cloud](https://on.cypress.io/cloud-introduction) using the action parameter setting `record: true` (see [Record test results on Cypress Cloud](#record-test-results-on-cypress-cloud))."

- Cypress Dashboard was renamed Cypress Cloud (see [Cypress Dashboard will soon become Cypress Cloud](https://www.cypress.io/blog/2022/11/01/cypress-dashboard-will-soon-become-cypress-cloud/#:~:text=Cypress%20Dashboard%20was%20introduced%20in,are%20renaming%20it%20Cypress%20Cloud.) from Nov 1, 2022).

- Cypress displays the URL with the text "Recorded Run:". It does not mention the name "Dashboard or Cloud" in the text.

- `github-action` uses Cypress' [Module API](https://docs.cypress.io/guides/guides/module-api) to run Cypress recording. The `cypress.run()` results are defined in [cypress-npm-api.d.ts](https://github.com/cypress-io/cypress/blob/master/cli/types/cypress-npm-api.d.ts) including `runUrl`.

---

Current example

```yml
      - name: Cypress tests
        # normally you would write
        # uses: cypress-io/github-action@v5
        uses: ./
        # let's give this action an ID so we can refer
        # to its output values later
        id: cypress
        # Continue the build in case of an error, as we need to set the
        # commit status in the next step, both in case of success and failure
        continue-on-error: true
        with:
          working-directory: examples/recording
          record: true
          parallel: true
          group: Recording example
          tag: action

      # see "outcome" and "conclusion" of a step doc
      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context
      # "output" can be success, failure, cancelled, or skipped
      - name: Print Cypress Cloud URL
        run: |
          echo Cypress finished with: ${{ steps.cypress.outcome }}
          echo See results at ${{ steps.cypress.outputs.dashboardUrl }}

```

![image](https://github.com/cypress-io/github-action/assets/66998419/18435f69-b9e0-4b06-956d-a11f3a6f2103)
