### ISSUE TITLE
Getting different Chrome versions when running in parallel/matrix

### ISSUE THREAD

**Issue by chrisotto6** [cypress-io/github-action#911]
Yesterday an issue started happening with our cypress runs while consuming this action. The chrome version would be different for a specific runner and blow up the run:

![Screenshot 2023-05-11 at 10 13 44 AM](https://github.com/cypress-io/github-action/assets/5222069/000cde6b-25bf-4ab4-9dce-fb07b4ab0d32)

Relevant Github Action configuration:

```YML
cypress:
    runs-on: ubuntu-latest
    needs: [set-env, build]
    environment:
      name: ${{ needs.set-env.outputs.env }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run E2E Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: true
          parallel: true
          working-directory: etoe
```
