### ISSUE TITLE
The action failed because of `npm ci` sync problem

### ISSUE THREAD

**Issue by dadiorchen** [cypress-io/github-action#922]
But we didn't change code, a week ago, the action failed, we tried checkout the code locally, run `npm ci`, it works well:
<img width="1134" alt="image" src="https://github.com/cypress-io/github-action/assets/5744708/bf179675-aa65-48f2-b44e-137c6e98550f">

Here is our action code:

```
name: API CI for New Pull Requests

on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - main

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      # only install dependencies
      # https://github.com/cypress-io/github-action
      - name: Install 📦
        uses: cypress-io/github-action@v4
        with:
          runTests: false
```

**Comment by MikeMcC399** [comment]
@dadiorchen 

Your log file uses `cypress-io/github-action@v5` whereas the workflow source you posted shows `cypress-io/github-action@v4`. It would be best to use `v5` in any case.

It looks like you have something out of sync in your repository. Make sure also that you only have one type of lock file in the branch.

Try to run `npm install` locally to make sure that your `package-lock.json` is in sync, then commit the changes to your repository.

If that does not help, then you may need to enable debugging. You can add
```
  env:
    DEBUG: '@cypress/github-action'
```

to your workflow.

**Comment by MikeMcC399** [comment]
@dadiorchen 

Was this by any chance a create-react-app? I just had the same issue after I did an update.

It is most probable that the issue is **not** caused by github-action itself as the action just reports what `npm ci` did.

**Comment by dadiorchen** [comment]
No I'm using next.js. I tried it again, using: 
* v5 of this action
* Delete lock file and do install again
* Try to change the node version locally to use `18`, I was using v16 previously.
The result is the same, locally, it works, fails on github action, maybe I can try the tool to run action locally later.

**Comment by MikeMcC399** [comment]
@dadiorchen 

Did you make any progress?

You could test without `github-action` using something like:

```yml
name: check-lockfile
on: workflow_dispatch
jobs:
  check-lockfile:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
```
