### ISSUE TITLE
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync.

### ISSUE THREAD

**Issue by ricardo-dematos** [cypress-io/github-action#962]
Since yesterday, 2023-07-13, when I resumed testing/using `cypress-io/github-action@v5`, I'm getting this error:

```
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

To be certain it's not related to our `package-lock.json`, I runned this workflow:

```yaml
      - name: 'Run end-to-end tests'
        id: cypress
        if: ${{ (success() || failure()) }}
        uses: cypress-io/github-action@v5  # see https://github.com/cypress-io/github-action/issues/620
        with:
          working-directory: 'e2e-tests'
          install: true
          runTests: false

      - name: 'Test package-lock.json'
        id: clean-install
        if: ${{ (success() || failure()) }}
        run: 'npm clean-install --no-fund --ignore-scripts --legacy-peer-deps --prefix "e2e-tests/"'
        shell: 'bash'
```

Here's the output:

![image](https://github.com/cypress-io/github-action/assets/108014795/583bb2eb-a311-42d9-b1aa-35de76242dc3)
![image](https://github.com/cypress-io/github-action/assets/108014795/cfbdea23-bb59-44dc-a3fb-73a01a11eaf5)
![image](https://github.com/cypress-io/github-action/assets/108014795/946ac41e-8a07-4d2c-a554-ace07ccfaa4f)

Could this be related with #958  ?
