### ISSUE TITLE
`cypress-io/github-action` does not distinguish `steps.<step_id>.conclusion` from `steps.<step_id>.outcome`

### ISSUE THREAD

**Issue by ricardo-dematos** [cypress-io/github-action#964]
Given the following configuration, when one of the tests fails both `steps.cypress.conclusion` and `steps.cypress.outcome` report `failure` , thus contradicting the [documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context).

```yaml
      - name: 'Run end-to-end tests'
        id: cypress
        timeout-minutes: 15  # must be adjusted with e2e tests progress
        uses: cypress-io/github-action@v5  # see https://github.com/cypress-io/github-action/issues/620
        env:
          ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'  # see https://github.com/cypress-io/cypress/issues/25357
        with:
          working-directory: 'e2e-tests'
          cache-key: "node-cache-${{ runner.os }}-npm-${{ hashFiles('e2e-tests/package-lock.json') }}"  # see https://github.com/cypress-io/github-action/pull/24
          command: 'npx cypress run --e2e --browser ${{ inputs.browser }} --headless --config video=false --env host="${{ inputs.deployment_url }}",username="${{ inputs.deployment_username }}",password="${{ inputs.deployment_password }}"'  # see https://github.com/cypress-io/github-action/issues/489

      - name: 'Print previous step outcome/conclusion'
        id: print
        run: |
          echo "outcome: ${{ steps.cypress.outcome }}"
          echo "conclusion: ${{ steps.cypress.conclusion }}"
        shell: bash
```

As long `cypress-io/github-action` completes with success, it should report `steps.cypress.conclusion=success` .

This may be related to the use of a [custom command](https://github.com/cypress-io/github-action/pull/884).
