### ISSUE TITLE
Cypress is executing twice, making an additional electron execution

### ISSUE THREAD

**Issue by Shashikapiletilevi** [cypress-io/github-action#974]
I have the following Workflow, 

```
name: End-to-end tests
on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: epic/routing-tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        continue-on-error: true
        with:
          working-directory: shop
          start: npm run cypress:run
#          record: false
          #parallel: true # Runs test in parallel using settings above
#        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
#          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-snapshots
          path: shop/cypress/screenshots



```
This is somehow been executed in github actions twice, once with the browser I have defined and another time with electron browser. I can see the node versions are different.

![cypress2023-07-25 000858](https://github.com/cypress-io/github-action/assets/134265393/f8bf30f8-b1a2-4578-873a-593c12b67dac)
