### ISSUE TITLE
Node version conflict (app/cypress)

### ISSUE THREAD

**Issue by h2oearth** [cypress-io/github-action#983]
I am using the latest Cypress in my project, which uses Node 18.x to test my components. Everything works well locally, but somehow GitHub Actions complains about node version conflicts.  I attached to this post the error message as well as my workflow.

This is my project structure

```
root -> {src/components, package.json}
    | --> cypress/{solutions, package.json}
```

Do I need to use a different node version for cypress?

**Error Message**

```
Run `npm audit` for details.
/opt/hostedtoolcache/node/18.17.0/x64/bin/npx cypress cache list
┌─────────┬───────────────────┐
│ version │ last used         │
├─────────┼───────────────────┤
│ 12.17.1 │ a few seconds ago │
└─────────┴───────────────────┘

DevTools listening on ws://127.0.0.1:43627/devtools/browser/18dea1f8-15b8-48e8-960f-399d42068f20
[2101:0730/225806.881368:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
An invalid configuration value was set.

Expected nodeVersion to be one of these values: "bundled", "system".

Instead the value was: "16.16.0"
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

**Workflow**

```
name: cypress-component-testing

on: push

env:
  APP_NODE_VERSION: 18.x
  CYPRESS_NODE_VERSION: 16.16.0

permissions:
  id-token: write
  contents: read

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.APP_NODE_VERSION }}
      - name: Cypress Run
        uses: cypress-io/github-action@v5
        with:
          # command: npm run cy:run
          component: true
          record: false
          working-directory: cypress
```
