### ISSUE TITLE
wait-on never resolves when providing multiple urls

### ISSUE THREAD

**Issue by venelinpetrov** [cypress-io/github-action#986]
Hello team, 

I observed a strange behavior, where if I provide more than one url in `wait-on` the job never completes and never actually runs the cypress tests. There are no errors.

```yml
 uses: cypress-io/github-action@v4
      with:
        working-directory: ./web
        start: |
          npm start -w @cubby/storefront-components-test-app
          node ./apps/storefront-components/server/main.js
        wait-on: 'http://localhost:3033, http://localhost:8090' <<<<<< If I remove the second url, it works normally
        wait-on-timeout: 10000
        command: npm run test:e2e -- --spec cypress/e2e/storefrontComponents/**/*.cy.ts --config baseUrl=http://localhost:3033
```
