### ISSUE TITLE
Start command executing in working-directory while CWD log statement seems to hint otherwise

### ISSUE THREAD

**Issue by josh-byster** [cypress-io/github-action#99]
Hi!
I tried using the following configuration, where I have an alternate Docker Compose file in my root directory:

```
- name: Cypress Run 
   uses: cypress-io/github-action@v1
   with:
      record: true
      working-directory: frontend
      env: BASE_URI=http://localhost:3000
      start: docker-compose -f docker-compose.cypress.yml up -d
      wait-on: 'http://localhost:3000'
```

This is the resulting stack trace:
```
starting server with command "docker-compose -f docker-compose.cypress.yml up"
current working directory "/home/runner/work/life-after-hate/life-after-hate"
/usr/local/bin/docker-compose -f docker-compose.cypress.yml up
Cypress test command: npx cypress run --record --config-file cypress.json --env BASE_URI=http://frontend:3000
/usr/local/bin/npx cypress run --record --config-file cypress.json --env BASE_URI=http://frontend:3000
.FileNotFoundError: [Errno 2] No such file or directory: './docker-compose.cypress.yml'
(node:4234) UnhandledPromiseRejectionWarning: Error: The process '/usr/local/bin/docker-compose' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1188:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1171:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1071:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

It works completely fine if I change `docker-compose.cypress.yml` to an absolute path `/home/runner/work/life-after-hate/life-after-hate/docker-compose.cypress.yml`, but it doesn't seem like I should need to do that. 

`docker-compose` on its own (i.e. not running in the Cypress action context) recognizes the relative path (I have a build step before the Cypress action where I just say `docker-compose -f docker-compose.cypress.yml build` and that works fine). 

**Edit:** I was able to fix by doing `../docker-compose.cypress.yml` since I realized it's attempting to execute within the context of `working-directory`. 

But I think the logged line is inadvertently misleading since it's not executing in the current working directory.  I'm wondering if maybe [here](https://github.com/cypress-io/github-action/blob/master/index.js#L240) it were to instead log out that it will run in `cypressCommandOptions.cwd`. 

Thanks!
